services:
  client:
    container_name: frontend-ui
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ngs360-network
    ports:
      - '8085:8080'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/

networks:
  ngs360-network:
    external: true
