// This file is auto-generated by @hey-api/openapi-ts

import {
  
  
  
  infiniteQueryOptions,
  queryOptions
} from '@tanstack/react-query'
import {
  
  addRun,
  addSampleToProject,
  addVendor,
  createFile,
  createProject,
  createWorkflow,
  deleteVendor,
  downloadFile,
  getAllWorkflowConfigs,
  getDemultiplexWorkflowConfig,
  getFile,
  getJob,
  getJobs,
  getLatestManifest,
  getProjectActions,
  getProjectByProjectId,
  getProjectPlatforms,
  getProjectTypes,
  getProjects,
  getRun,
  getRunMetrics,
  getRunSamplesheet,
  getRuns,
  getSamples,
  getSetting,
  getSettingsByTag,
  getVendor,
  getVendors,
  getWorkflowByWorkflowId,
  getWorkflowConfig,
  getWorkflows,
  healthCheck,
  listDemultiplexWorkflows,
  listFiles,
  listWorkflowConfigs,
  postRunSamplesheet,
  reindexProjects,
  reindexRuns,
  reindexSamples,
  root,
  search,
  searchProjects,
  searchRuns,
  submitDemultiplexWorkflowJob,
  submitJob,
  updateJob,
  updateProject,
  updateRun,
  updateSampleInProject,
  updateSetting,
  updateVendor,
  uploadManifest,
  validateManifest
} from '../sdk.gen'
import { client as _heyApiClient } from '../client.gen'
import type {DefaultError, InfiniteData, UseMutationOptions} from '@tanstack/react-query';
import type {Options} from '../sdk.gen';
import type {
  AddRunData,
  AddRunError,
  AddRunResponse,
  AddSampleToProjectData,
  AddSampleToProjectError,
  AddSampleToProjectResponse,
  AddVendorData,
  AddVendorError,
  AddVendorResponse,
  CreateFileData,
  CreateFileError,
  CreateFileResponse,
  CreateProjectData,
  CreateProjectError,
  CreateProjectResponse,
  CreateWorkflowData,
  CreateWorkflowError,
  CreateWorkflowResponse,
  DeleteVendorData,
  DeleteVendorError,
  DeleteVendorResponse,
  DownloadFileData,
  GetAllWorkflowConfigsData,
  GetDemultiplexWorkflowConfigData,
  GetFileData,
  GetJobData,
  GetJobsData,
  GetLatestManifestData,
  GetProjectActionsData,
  GetProjectByProjectIdData,
  GetProjectPlatformsData,
  GetProjectTypesData,
  GetProjectsData,
  GetProjectsError,
  GetProjectsResponse,
  GetRunData,
  GetRunMetricsData,
  GetRunSamplesheetData,
  GetRunsData,
  GetRunsError,
  GetRunsResponse,
  GetSamplesData,
  GetSamplesError,
  GetSamplesResponse,
  GetSettingData,
  GetSettingsByTagData,
  GetVendorData,
  GetVendorsData,
  GetVendorsError,
  GetVendorsResponse,
  GetWorkflowByWorkflowIdData,
  GetWorkflowConfigData,
  GetWorkflowsData,
  GetWorkflowsError,
  GetWorkflowsResponse,
  HealthCheckData,
  ListDemultiplexWorkflowsData,
  ListFilesData,
  ListWorkflowConfigsData,
  PostRunSamplesheetData,
  PostRunSamplesheetError,
  PostRunSamplesheetResponse,
  ReindexProjectsData,
  ReindexRunsData,
  ReindexSamplesData,
  RootData,
  SearchData,
  SearchProjectsData,
  SearchProjectsError,
  SearchProjectsResponse,
  SearchRunsData,
  SearchRunsError,
  SearchRunsResponse,
  SubmitDemultiplexWorkflowJobData,
  SubmitDemultiplexWorkflowJobError,
  SubmitDemultiplexWorkflowJobResponse,
  SubmitJobData,
  SubmitJobError,
  SubmitJobResponse,
  UpdateJobData,
  UpdateJobError,
  UpdateJobResponse,
  UpdateProjectData,
  UpdateProjectError,
  UpdateProjectResponse,
  UpdateRunData,
  UpdateRunError,
  UpdateRunResponse,
  UpdateSampleInProjectData,
  UpdateSampleInProjectError,
  UpdateSampleInProjectResponse,
  UpdateSettingData,
  UpdateSettingError,
  UpdateSettingResponse,
  UpdateVendorData,
  UpdateVendorError,
  UpdateVendorResponse,
  UploadManifestData,
  UploadManifestError,
  UploadManifestResponse,
  ValidateManifestData,
  ValidateManifestError,
  ValidateManifestResponse,
} from '../types.gen'
import type { AxiosError } from 'axios'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const rootQueryKey = (options?: Options<RootData>) =>
  createQueryKey('root', options)

/**
 * Root
 */
export const rootOptions = (options?: Options<RootData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await root({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: rootQueryKey(options),
  })
}

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) =>
  createQueryKey('healthCheck', options)

/**
 * Health Check
 */
export const healthCheckOptions = (options?: Options<HealthCheckData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: healthCheckQueryKey(options),
  })
}

export const createFileQueryKey = (options: Options<CreateFileData>) =>
  createQueryKey('createFile', options)

/**
 * Create a new file record
 * Create a new file record with optional file content upload.
 * - **filename**: Name of the file
 * - **description**: Optional description of the file
 * - **file_type**: Type of file (fastq, bam, vcf, etc.)
 * - **entity_type**: Whether this file belongs to a project or run
 * - **entity_id**: ID of the project or run this file belongs to
 * - **relative_path**: Optional subdirectory path within the entity folder
 * (e.g., "raw_data/sample1" or "results/qc")
 * - **overwrite**: If True, replace existing file with same name/location (default: False)
 * - **is_public**: Whether the file is publicly accessible
 * - **created_by**: User who created the file
 *
 * Returns:
 * FilePublic with metadata including the assigned file_id
 *
 * Raises:
 * 409 Conflict: If file already exists and overwrite=False
 *
 * Examples:
 * - File at entity root: relative_path=None
 * => s3://bucket/project/P-20260109-0001/abc123_file.txt
 * - File in subdirectory: relative_path="raw_data/sample1"
 * => s3://bucket/project/P-20260109-0001/raw_data/sample1/abc123_file.txt
 */
export const createFileOptions = (options: Options<CreateFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createFileQueryKey(options),
  })
}

/**
 * Create a new file record
 * Create a new file record with optional file content upload.
 * - **filename**: Name of the file
 * - **description**: Optional description of the file
 * - **file_type**: Type of file (fastq, bam, vcf, etc.)
 * - **entity_type**: Whether this file belongs to a project or run
 * - **entity_id**: ID of the project or run this file belongs to
 * - **relative_path**: Optional subdirectory path within the entity folder
 * (e.g., "raw_data/sample1" or "results/qc")
 * - **overwrite**: If True, replace existing file with same name/location (default: False)
 * - **is_public**: Whether the file is publicly accessible
 * - **created_by**: User who created the file
 *
 * Returns:
 * FilePublic with metadata including the assigned file_id
 *
 * Raises:
 * 409 Conflict: If file already exists and overwrite=False
 *
 * Examples:
 * - File at entity root: relative_path=None
 * => s3://bucket/project/P-20260109-0001/abc123_file.txt
 * - File in subdirectory: relative_path="raw_data/sample1"
 * => s3://bucket/project/P-20260109-0001/raw_data/sample1/abc123_file.txt
 */
export const createFileMutation = (
  options?: Partial<Options<CreateFileData>>,
): UseMutationOptions<
  CreateFileResponse,
  AxiosError<CreateFileError>,
  Options<CreateFileData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateFileResponse,
    AxiosError<CreateFileError>,
    Options<CreateFileData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createFile({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listFilesQueryKey = (options: Options<ListFilesData>) =>
  createQueryKey('listFiles', options)

/**
 * List Files
 * Browse files and folders at the specified URI.
 *
 * For S3:
 * - Full s3:// URI is required
 * - No navigation outside the initial uri is allowed
 */
export const listFilesOptions = (options: Options<ListFilesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listFilesQueryKey(options),
  })
}

export const downloadFileQueryKey = (options: Options<DownloadFileData>) =>
  createQueryKey('downloadFile', options)

/**
 * Download File
 * Download a file from S3.
 *
 * Returns the file as a streaming download with appropriate content type and filename.
 *
 * Args:
 * path: Full S3 URI to the file (e.g., s3://bucket/folder/file.txt)
 *
 * Returns:
 * StreamingResponse with the file content
 */
export const downloadFileOptions = (options: Options<DownloadFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await downloadFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: downloadFileQueryKey(options),
  })
}

export const getFileQueryKey = (options: Options<GetFileData>) =>
  createQueryKey('getFile', options)

/**
 * Get File
 * Retrieve file metadata by file ID.
 */
export const getFileOptions = (options: Options<GetFileData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getFileQueryKey(options),
  })
}

export const getJobsQueryKey = (options?: Options<GetJobsData>) =>
  createQueryKey('getJobs', options)

/**
 * Get Jobs
 * Retrieve a list of batch jobs with optional filtering and sorting.
 *
 * Args:
 * session: Database session
 * skip: Number of records to skip
 * limit: Maximum number of records to return
 * user: Optional user filter
 * status_filter: Optional status filter
 * sort_by: Field to sort by (defaults to 'submitted_on')
 * sort_order: Sort order 'asc' or 'desc' (defaults to 'desc')
 *
 * Returns:
 * List of jobs and total count
 */
export const getJobsOptions = (options?: Options<GetJobsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getJobs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getJobsQueryKey(options),
  })
}

export const submitJobQueryKey = (options: Options<SubmitJobData>) =>
  createQueryKey('submitJob', options)

/**
 * Submit Job
 * Submit a new batch job to AWS Batch and create a database record.
 *
 * This endpoint submits a job directly to AWS Batch and creates a tracking
 * record in the database. The job will be queued in AWS Batch and its status
 * can be monitored using the GET endpoints.
 *
 * Args:
 * session: Database session
 * job_in: Job submission data including AWS Batch parameters
 *
 * Returns:
 * Created job information with AWS job ID
 */
export const submitJobOptions = (options: Options<SubmitJobData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await submitJob({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: submitJobQueryKey(options),
  })
}

/**
 * Submit Job
 * Submit a new batch job to AWS Batch and create a database record.
 *
 * This endpoint submits a job directly to AWS Batch and creates a tracking
 * record in the database. The job will be queued in AWS Batch and its status
 * can be monitored using the GET endpoints.
 *
 * Args:
 * session: Database session
 * job_in: Job submission data including AWS Batch parameters
 *
 * Returns:
 * Created job information with AWS job ID
 */
export const submitJobMutation = (
  options?: Partial<Options<SubmitJobData>>,
): UseMutationOptions<
  SubmitJobResponse,
  AxiosError<SubmitJobError>,
  Options<SubmitJobData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmitJobResponse,
    AxiosError<SubmitJobError>,
    Options<SubmitJobData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await submitJob({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getJobQueryKey = (options: Options<GetJobData>) =>
  createQueryKey('getJob', options)

/**
 * Get Job
 * Retrieve information about a specific batch job.
 *
 * Args:
 * session: Database session
 * job_id: Job UUID
 *
 * Returns:
 * Job information
 */
export const getJobOptions = (options: Options<GetJobData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getJob({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getJobQueryKey(options),
  })
}

/**
 * Update Job
 * Update a batch job.
 *
 * Args:
 * session: Database session
 * job_id: Job UUID
 * job_update: Job update data
 *
 * Returns:
 * Updated job information
 */
export const updateJobMutation = (
  options?: Partial<Options<UpdateJobData>>,
): UseMutationOptions<
  UpdateJobResponse,
  AxiosError<UpdateJobError>,
  Options<UpdateJobData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateJobResponse,
    AxiosError<UpdateJobError>,
    Options<UpdateJobData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateJob({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getProjectsQueryKey = (options?: Options<GetProjectsData>) =>
  createQueryKey('getProjects', options)

/**
 * Get Projects
 * Returns a paginated list of projects.
 */
export const getProjectsOptions = (options?: Options<GetProjectsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjects({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getProjectsQueryKey(options),
  })
}

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const getProjectsInfiniteQueryKey = (
  options?: Options<GetProjectsData>,
): QueryKey<Options<GetProjectsData>> =>
  createQueryKey('getProjects', options, true)

/**
 * Get Projects
 * Returns a paginated list of projects.
 */
export const getProjectsInfiniteOptions = (
  options?: Options<GetProjectsData>,
) => {
  return infiniteQueryOptions<
    GetProjectsResponse,
    AxiosError<GetProjectsError>,
    InfiniteData<GetProjectsResponse>,
    QueryKey<Options<GetProjectsData>>,
    | number
    | Pick<
        QueryKey<Options<GetProjectsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetProjectsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getProjects({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getProjectsInfiniteQueryKey(options),
    },
  )
}

export const createProjectQueryKey = (options: Options<CreateProjectData>) =>
  createQueryKey('createProject', options)

/**
 * Create Project
 * Create a new project with optional attributes.
 */
export const createProjectOptions = (options: Options<CreateProjectData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createProject({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createProjectQueryKey(options),
  })
}

/**
 * Create Project
 * Create a new project with optional attributes.
 */
export const createProjectMutation = (
  options?: Partial<Options<CreateProjectData>>,
): UseMutationOptions<
  CreateProjectResponse,
  AxiosError<CreateProjectError>,
  Options<CreateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateProjectResponse,
    AxiosError<CreateProjectError>,
    Options<CreateProjectData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createProject({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const searchProjectsQueryKey = (options: Options<SearchProjectsData>) =>
  createQueryKey('searchProjects', options)

/**
 * Search Projects
 * Search projects by project_id or name.
 */
export const searchProjectsOptions = (options: Options<SearchProjectsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchProjects({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: searchProjectsQueryKey(options),
  })
}

export const searchProjectsInfiniteQueryKey = (
  options: Options<SearchProjectsData>,
): QueryKey<Options<SearchProjectsData>> =>
  createQueryKey('searchProjects', options, true)

/**
 * Search Projects
 * Search projects by project_id or name.
 */
export const searchProjectsInfiniteOptions = (
  options: Options<SearchProjectsData>,
) => {
  return infiniteQueryOptions<
    SearchProjectsResponse,
    AxiosError<SearchProjectsError>,
    InfiniteData<SearchProjectsResponse>,
    QueryKey<Options<SearchProjectsData>>,
    | number
    | Pick<
        QueryKey<Options<SearchProjectsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<SearchProjectsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await searchProjects({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: searchProjectsInfiniteQueryKey(options),
    },
  )
}

export const reindexProjectsQueryKey = (
  options?: Options<ReindexProjectsData>,
) => createQueryKey('reindexProjects', options)

/**
 * Reindex Projects
 * Reindex projects in database with OpenSearch
 */
export const reindexProjectsOptions = (
  options?: Options<ReindexProjectsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await reindexProjects({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: reindexProjectsQueryKey(options),
  })
}

/**
 * Reindex Projects
 * Reindex projects in database with OpenSearch
 */
export const reindexProjectsMutation = (
  options?: Partial<Options<ReindexProjectsData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<ReindexProjectsData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<ReindexProjectsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await reindexProjects({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listWorkflowConfigsQueryKey = (
  options?: Options<ListWorkflowConfigsData>,
) => createQueryKey('listWorkflowConfigs', options)

/**
 * List Workflow Configs
 * List all available project workflow configs from S3.
 *
 * Returns a list of workflow IDs (config filenames without extensions).
 */
export const listWorkflowConfigsOptions = (
  options?: Options<ListWorkflowConfigsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWorkflowConfigs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWorkflowConfigsQueryKey(options),
  })
}

export const getAllWorkflowConfigsQueryKey = (
  options?: Options<GetAllWorkflowConfigsData>,
) => createQueryKey('getAllWorkflowConfigs', options)

/**
 * Get All Workflow Configs
 * Retrieve and parse all project workflow configurations from S3.
 *
 * Returns:
 * PipelineConfigsResponse containing all parsed workflow configurations
 */
export const getAllWorkflowConfigsOptions = (
  options?: Options<GetAllWorkflowConfigsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllWorkflowConfigs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAllWorkflowConfigsQueryKey(options),
  })
}

export const getWorkflowConfigQueryKey = (
  options: Options<GetWorkflowConfigData>,
) => createQueryKey('getWorkflowConfig', options)

/**
 * Get Workflow Config
 * Retrieve a specific workflow configuration.
 *
 * Args:
 * workflow_id: The workflow identifier (filename without extension)
 *
 * Returns:
 * Complete workflow configuration
 */
export const getWorkflowConfigOptions = (
  options: Options<GetWorkflowConfigData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkflowConfig({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWorkflowConfigQueryKey(options),
  })
}

export const getProjectActionsQueryKey = (
  options?: Options<GetProjectActionsData>,
) => createQueryKey('getProjectActions', options)

/**
 * Get Project Actions
 * Get available project actions.
 *
 * Returns:
 * List of available project actions with labels, values, and descriptions
 */
export const getProjectActionsOptions = (
  options?: Options<GetProjectActionsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectActions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getProjectActionsQueryKey(options),
  })
}

export const getProjectPlatformsQueryKey = (
  options?: Options<GetProjectPlatformsData>,
) => createQueryKey('getProjectPlatforms', options)

/**
 * Get Project Platforms
 * Get available project platforms.
 *
 * Returns:
 * List of available platforms with labels, values, and descriptions
 */
export const getProjectPlatformsOptions = (
  options?: Options<GetProjectPlatformsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectPlatforms({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getProjectPlatformsQueryKey(options),
  })
}

export const getProjectTypesQueryKey = (
  options: Options<GetProjectTypesData>,
) => createQueryKey('getProjectTypes', options)

/**
 * Get Project Types
 * Get available project types based on action and platform.
 *
 * Args:
 * action: The project action
 * platform: The platform
 *
 * Returns:
 * List of project types with label, value, and project_type
 */
export const getProjectTypesOptions = (
  options: Options<GetProjectTypesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectTypes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getProjectTypesQueryKey(options),
  })
}

export const getProjectByProjectIdQueryKey = (
  options: Options<GetProjectByProjectIdData>,
) => createQueryKey('getProjectByProjectId', options)

/**
 * Get Project By Project Id
 * Returns a single project by its project_id.
 * Note: This is different from its internal "id".
 */
export const getProjectByProjectIdOptions = (
  options: Options<GetProjectByProjectIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getProjectByProjectId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getProjectByProjectIdQueryKey(options),
  })
}

/**
 * Update Project
 * Update information about a specific project.
 */
export const updateProjectMutation = (
  options?: Partial<Options<UpdateProjectData>>,
): UseMutationOptions<
  UpdateProjectResponse,
  AxiosError<UpdateProjectError>,
  Options<UpdateProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateProjectResponse,
    AxiosError<UpdateProjectError>,
    Options<UpdateProjectData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateProject({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getSamplesQueryKey = (options: Options<GetSamplesData>) =>
  createQueryKey('getSamples', options)

/**
 * Get Samples
 * Returns a paginated list of samples.
 */
export const getSamplesOptions = (options: Options<GetSamplesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSamples({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getSamplesQueryKey(options),
  })
}

export const getSamplesInfiniteQueryKey = (
  options: Options<GetSamplesData>,
): QueryKey<Options<GetSamplesData>> =>
  createQueryKey('getSamples', options, true)

/**
 * Get Samples
 * Returns a paginated list of samples.
 */
export const getSamplesInfiniteOptions = (options: Options<GetSamplesData>) => {
  return infiniteQueryOptions<
    GetSamplesResponse,
    AxiosError<GetSamplesError>,
    InfiniteData<GetSamplesResponse>,
    QueryKey<Options<GetSamplesData>>,
    | number
    | Pick<
        QueryKey<Options<GetSamplesData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetSamplesData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getSamples({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getSamplesInfiniteQueryKey(options),
    },
  )
}

export const addSampleToProjectQueryKey = (
  options: Options<AddSampleToProjectData>,
) => createQueryKey('addSampleToProject', options)

/**
 * Add Sample To Project
 * Create a new sample with optional attributes.
 */
export const addSampleToProjectOptions = (
  options: Options<AddSampleToProjectData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await addSampleToProject({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: addSampleToProjectQueryKey(options),
  })
}

/**
 * Add Sample To Project
 * Create a new sample with optional attributes.
 */
export const addSampleToProjectMutation = (
  options?: Partial<Options<AddSampleToProjectData>>,
): UseMutationOptions<
  AddSampleToProjectResponse,
  AxiosError<AddSampleToProjectError>,
  Options<AddSampleToProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    AddSampleToProjectResponse,
    AxiosError<AddSampleToProjectError>,
    Options<AddSampleToProjectData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await addSampleToProject({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update Sample In Project
 * Update an existing sample in a project.
 */
export const updateSampleInProjectMutation = (
  options?: Partial<Options<UpdateSampleInProjectData>>,
): UseMutationOptions<
  UpdateSampleInProjectResponse,
  AxiosError<UpdateSampleInProjectError>,
  Options<UpdateSampleInProjectData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSampleInProjectResponse,
    AxiosError<UpdateSampleInProjectError>,
    Options<UpdateSampleInProjectData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateSampleInProject({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getRunsQueryKey = (options?: Options<GetRunsData>) =>
  createQueryKey('getRuns', options)

/**
 * Get Runs
 * Retrieve a list of all sequencing runs.
 */
export const getRunsOptions = (options?: Options<GetRunsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRuns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRunsQueryKey(options),
  })
}

export const getRunsInfiniteQueryKey = (
  options?: Options<GetRunsData>,
): QueryKey<Options<GetRunsData>> => createQueryKey('getRuns', options, true)

/**
 * Get Runs
 * Retrieve a list of all sequencing runs.
 */
export const getRunsInfiniteOptions = (options?: Options<GetRunsData>) => {
  return infiniteQueryOptions<
    GetRunsResponse,
    AxiosError<GetRunsError>,
    InfiniteData<GetRunsResponse>,
    QueryKey<Options<GetRunsData>>,
    | number
    | Pick<
        QueryKey<Options<GetRunsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetRunsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getRuns({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getRunsInfiniteQueryKey(options),
    },
  )
}

export const addRunQueryKey = (options: Options<AddRunData>) =>
  createQueryKey('addRun', options)

/**
 * Add Run
 * Create a new project with optional attributes.
 */
export const addRunOptions = (options: Options<AddRunData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await addRun({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: addRunQueryKey(options),
  })
}

/**
 * Add Run
 * Create a new project with optional attributes.
 */
export const addRunMutation = (
  options?: Partial<Options<AddRunData>>,
): UseMutationOptions<
  AddRunResponse,
  AxiosError<AddRunError>,
  Options<AddRunData>
> => {
  const mutationOptions: UseMutationOptions<
    AddRunResponse,
    AxiosError<AddRunError>,
    Options<AddRunData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await addRun({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const searchRunsQueryKey = (options: Options<SearchRunsData>) =>
  createQueryKey('searchRuns', options)

/**
 * Search Runs
 * Search for sequencing runs using OpenSearch.
 */
export const searchRunsOptions = (options: Options<SearchRunsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchRuns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: searchRunsQueryKey(options),
  })
}

export const searchRunsInfiniteQueryKey = (
  options: Options<SearchRunsData>,
): QueryKey<Options<SearchRunsData>> =>
  createQueryKey('searchRuns', options, true)

/**
 * Search Runs
 * Search for sequencing runs using OpenSearch.
 */
export const searchRunsInfiniteOptions = (options: Options<SearchRunsData>) => {
  return infiniteQueryOptions<
    SearchRunsResponse,
    AxiosError<SearchRunsError>,
    InfiniteData<SearchRunsResponse>,
    QueryKey<Options<SearchRunsData>>,
    | number
    | Pick<
        QueryKey<Options<SearchRunsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<SearchRunsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await searchRuns({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: searchRunsInfiniteQueryKey(options),
    },
  )
}

export const reindexRunsQueryKey = (options?: Options<ReindexRunsData>) =>
  createQueryKey('reindexRuns', options)

/**
 * Reindex Runs
 * Reindex runs in database with OpenSearch
 */
export const reindexRunsOptions = (options?: Options<ReindexRunsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await reindexRuns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: reindexRunsQueryKey(options),
  })
}

/**
 * Reindex Runs
 * Reindex runs in database with OpenSearch
 */
export const reindexRunsMutation = (
  options?: Partial<Options<ReindexRunsData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<ReindexRunsData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<ReindexRunsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await reindexRuns({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listDemultiplexWorkflowsQueryKey = (
  options?: Options<ListDemultiplexWorkflowsData>,
) => createQueryKey('listDemultiplexWorkflows', options)

/**
 * List Demultiplex Workflows
 * List all available demultiplex workflows from S3.
 *
 * Returns a list of workflow IDs (config filenames without extensions).
 */
export const listDemultiplexWorkflowsOptions = (
  options?: Options<ListDemultiplexWorkflowsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listDemultiplexWorkflows({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listDemultiplexWorkflowsQueryKey(options),
  })
}

export const submitDemultiplexWorkflowJobQueryKey = (
  options: Options<SubmitDemultiplexWorkflowJobData>,
) => createQueryKey('submitDemultiplexWorkflowJob', options)

/**
 * Submit Demultiplex Workflow Job
 * Submit a job for the specified demultiplex workflow.
 * Args:
 * session: Database session
 * workflow_body: The demultiplex workflow execution request containing
 * workflow_id, run_barcode, and inputs
 * s3_client: S3 client for accessing workflow configs
 * Returns:
 * BatchJobPublic: The created batch job with AWS job information.
 */
export const submitDemultiplexWorkflowJobOptions = (
  options: Options<SubmitDemultiplexWorkflowJobData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await submitDemultiplexWorkflowJob({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: submitDemultiplexWorkflowJobQueryKey(options),
  })
}

/**
 * Submit Demultiplex Workflow Job
 * Submit a job for the specified demultiplex workflow.
 * Args:
 * session: Database session
 * workflow_body: The demultiplex workflow execution request containing
 * workflow_id, run_barcode, and inputs
 * s3_client: S3 client for accessing workflow configs
 * Returns:
 * BatchJobPublic: The created batch job with AWS job information.
 */
export const submitDemultiplexWorkflowJobMutation = (
  options?: Partial<Options<SubmitDemultiplexWorkflowJobData>>,
): UseMutationOptions<
  SubmitDemultiplexWorkflowJobResponse,
  AxiosError<SubmitDemultiplexWorkflowJobError>,
  Options<SubmitDemultiplexWorkflowJobData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmitDemultiplexWorkflowJobResponse,
    AxiosError<SubmitDemultiplexWorkflowJobError>,
    Options<SubmitDemultiplexWorkflowJobData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await submitDemultiplexWorkflowJob({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getDemultiplexWorkflowConfigQueryKey = (
  options: Options<GetDemultiplexWorkflowConfigData>,
) => createQueryKey('getDemultiplexWorkflowConfig', options)

/**
 * Get Demultiplex Workflow Config
 * Retrieve a specific demultiplex workflow configuration.
 *
 * Args:
 * workflow_id: The workflow identifier (filename without extension)
 * run_barcode: Optional run barcode to prepopulate s3_run_folder_path from run's run_folder_uri
 *
 * Returns:
 * Complete workflow configuration with prepopulated defaults if run_barcode is provided
 */
export const getDemultiplexWorkflowConfigOptions = (
  options: Options<GetDemultiplexWorkflowConfigData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDemultiplexWorkflowConfig({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getDemultiplexWorkflowConfigQueryKey(options),
  })
}

export const getRunQueryKey = (options: Options<GetRunData>) =>
  createQueryKey('getRun', options)

/**
 * Get Run
 * Retrieve a sequencing run.
 */
export const getRunOptions = (options: Options<GetRunData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRun({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRunQueryKey(options),
  })
}

/**
 * Update Run
 * Update the status of a specific run.
 * Valid status values are: "In Progress", "Uploading", "Ready", "Resync"
 */
export const updateRunMutation = (
  options?: Partial<Options<UpdateRunData>>,
): UseMutationOptions<
  UpdateRunResponse,
  AxiosError<UpdateRunError>,
  Options<UpdateRunData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateRunResponse,
    AxiosError<UpdateRunError>,
    Options<UpdateRunData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateRun({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getRunSamplesheetQueryKey = (
  options: Options<GetRunSamplesheetData>,
) => createQueryKey('getRunSamplesheet', options)

/**
 * Get Run Samplesheet
 * Retrieve the sample sheet for a specific run.
 */
export const getRunSamplesheetOptions = (
  options: Options<GetRunSamplesheetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRunSamplesheet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRunSamplesheetQueryKey(options),
  })
}

export const postRunSamplesheetQueryKey = (
  options: Options<PostRunSamplesheetData>,
) => createQueryKey('postRunSamplesheet', options)

/**
 * Post Run Samplesheet
 * Upload a samplesheet to a run.
 */
export const postRunSamplesheetOptions = (
  options: Options<PostRunSamplesheetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postRunSamplesheet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: postRunSamplesheetQueryKey(options),
  })
}

/**
 * Post Run Samplesheet
 * Upload a samplesheet to a run.
 */
export const postRunSamplesheetMutation = (
  options?: Partial<Options<PostRunSamplesheetData>>,
): UseMutationOptions<
  PostRunSamplesheetResponse,
  AxiosError<PostRunSamplesheetError>,
  Options<PostRunSamplesheetData>
> => {
  const mutationOptions: UseMutationOptions<
    PostRunSamplesheetResponse,
    AxiosError<PostRunSamplesheetError>,
    Options<PostRunSamplesheetData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postRunSamplesheet({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getRunMetricsQueryKey = (options: Options<GetRunMetricsData>) =>
  createQueryKey('getRunMetrics', options)

/**
 * Get Run Metrics
 * Retrieve demultiplexing metrics for a specific run.
 */
export const getRunMetricsOptions = (options: Options<GetRunMetricsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRunMetrics({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getRunMetricsQueryKey(options),
  })
}

export const reindexSamplesQueryKey = (options?: Options<ReindexSamplesData>) =>
  createQueryKey('reindexSamples', options)

/**
 * Reindex Samples
 * Reindex samples in database with OpenSearch
 */
export const reindexSamplesOptions = (
  options?: Options<ReindexSamplesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await reindexSamples({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: reindexSamplesQueryKey(options),
  })
}

/**
 * Reindex Samples
 * Reindex samples in database with OpenSearch
 */
export const reindexSamplesMutation = (
  options?: Partial<Options<ReindexSamplesData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<ReindexSamplesData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<ReindexSamplesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await reindexSamples({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const searchQueryKey = (options: Options<SearchData>) =>
  createQueryKey('search', options)

/**
 * Search
 * Search across all indices using OpenSearch.
 */
export const searchOptions = (options: Options<SearchData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await search({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: searchQueryKey(options),
  })
}

export const getSettingsByTagQueryKey = (
  options: Options<GetSettingsByTagData>,
) => createQueryKey('getSettingsByTag', options)

/**
 * Get Settings By Tag
 * Retrieve all settings that have a specific tag key-value pair.
 * For example: tag_key="category" and tag_value="storage"
 */
export const getSettingsByTagOptions = (
  options: Options<GetSettingsByTagData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSettingsByTag({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getSettingsByTagQueryKey(options),
  })
}

export const getSettingQueryKey = (options: Options<GetSettingData>) =>
  createQueryKey('getSetting', options)

/**
 * Get Setting
 * Retrieve a specific setting by key.
 */
export const getSettingOptions = (options: Options<GetSettingData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSetting({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getSettingQueryKey(options),
  })
}

/**
 * Update Setting
 * Update a specific setting. Only the value, name, description, and tags can be updated.
 * The key cannot be changed as it's the primary identifier.
 */
export const updateSettingMutation = (
  options?: Partial<Options<UpdateSettingData>>,
): UseMutationOptions<
  UpdateSettingResponse,
  AxiosError<UpdateSettingError>,
  Options<UpdateSettingData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSettingResponse,
    AxiosError<UpdateSettingError>,
    Options<UpdateSettingData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateSetting({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getVendorsQueryKey = (options?: Options<GetVendorsData>) =>
  createQueryKey('getVendors', options)

/**
 * Get Vendors
 * Retrieve a list of all vendors.
 */
export const getVendorsOptions = (options?: Options<GetVendorsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getVendors({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getVendorsQueryKey(options),
  })
}

export const getVendorsInfiniteQueryKey = (
  options?: Options<GetVendorsData>,
): QueryKey<Options<GetVendorsData>> =>
  createQueryKey('getVendors', options, true)

/**
 * Get Vendors
 * Retrieve a list of all vendors.
 */
export const getVendorsInfiniteOptions = (
  options?: Options<GetVendorsData>,
) => {
  return infiniteQueryOptions<
    GetVendorsResponse,
    AxiosError<GetVendorsError>,
    InfiniteData<GetVendorsResponse>,
    QueryKey<Options<GetVendorsData>>,
    | number
    | Pick<
        QueryKey<Options<GetVendorsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetVendorsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getVendors({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getVendorsInfiniteQueryKey(options),
    },
  )
}

export const addVendorQueryKey = (options: Options<AddVendorData>) =>
  createQueryKey('addVendor', options)

/**
 * Add Vendor
 * Create a new vendor with optional attributes.
 */
export const addVendorOptions = (options: Options<AddVendorData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await addVendor({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: addVendorQueryKey(options),
  })
}

/**
 * Add Vendor
 * Create a new vendor with optional attributes.
 */
export const addVendorMutation = (
  options?: Partial<Options<AddVendorData>>,
): UseMutationOptions<
  AddVendorResponse,
  AxiosError<AddVendorError>,
  Options<AddVendorData>
> => {
  const mutationOptions: UseMutationOptions<
    AddVendorResponse,
    AxiosError<AddVendorError>,
    Options<AddVendorData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await addVendor({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Vendor
 * Delete a specific vendor by ID.
 */
export const deleteVendorMutation = (
  options?: Partial<Options<DeleteVendorData>>,
): UseMutationOptions<
  DeleteVendorResponse,
  AxiosError<DeleteVendorError>,
  Options<DeleteVendorData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteVendorResponse,
    AxiosError<DeleteVendorError>,
    Options<DeleteVendorData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteVendor({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getVendorQueryKey = (options: Options<GetVendorData>) =>
  createQueryKey('getVendor', options)

/**
 * Get Vendor
 * Retrieve a specific vendor by ID.
 */
export const getVendorOptions = (options: Options<GetVendorData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getVendor({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getVendorQueryKey(options),
  })
}

/**
 * Update Vendor
 * Update information about a specific vendor.
 */
export const updateVendorMutation = (
  options?: Partial<Options<UpdateVendorData>>,
): UseMutationOptions<
  UpdateVendorResponse,
  AxiosError<UpdateVendorError>,
  Options<UpdateVendorData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateVendorResponse,
    AxiosError<UpdateVendorError>,
    Options<UpdateVendorData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateVendor({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getLatestManifestQueryKey = (
  options: Options<GetLatestManifestData>,
) => createQueryKey('getLatestManifest', options)

/**
 * Get Latest Manifest
 * Retrieve the latest manifest file path from the specified S3 bucket.
 *
 * Searches recursively through the bucket/prefix for files that:
 * - Contain "manifest" (case-insensitive)
 * - End with ".csv"
 *
 * Returns the full S3 path of the most recent matching file.
 *
 * Args:
 * s3_path: S3 path to search (e.g., "s3://bucket-name/path/to/manifests")
 *
 * Returns:
 * Full S3 path to the latest manifest file
 */
export const getLatestManifestOptions = (
  options: Options<GetLatestManifestData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLatestManifest({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getLatestManifestQueryKey(options),
  })
}

export const uploadManifestQueryKey = (options: Options<UploadManifestData>) =>
  createQueryKey('uploadManifest', options)

/**
 * Upload Manifest
 * Upload a manifest CSV file to the specified S3 path.
 *
 * Args:
 * s3_path: S3 path where the file should be uploaded
 * (e.g., "s3://bucket-name/path/to/manifest.csv")
 * file: The manifest CSV file to upload
 *
 * Returns:
 * ManifestUploadResponse with the uploaded file path and status
 */
export const uploadManifestOptions = (options: Options<UploadManifestData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await uploadManifest({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: uploadManifestQueryKey(options),
  })
}

/**
 * Upload Manifest
 * Upload a manifest CSV file to the specified S3 path.
 *
 * Args:
 * s3_path: S3 path where the file should be uploaded
 * (e.g., "s3://bucket-name/path/to/manifest.csv")
 * file: The manifest CSV file to upload
 *
 * Returns:
 * ManifestUploadResponse with the uploaded file path and status
 */
export const uploadManifestMutation = (
  options?: Partial<Options<UploadManifestData>>,
): UseMutationOptions<
  UploadManifestResponse,
  AxiosError<UploadManifestError>,
  Options<UploadManifestData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadManifestResponse,
    AxiosError<UploadManifestError>,
    Options<UploadManifestData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await uploadManifest({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const validateManifestQueryKey = (
  options: Options<ValidateManifestData>,
) => createQueryKey('validateManifest', options)

/**
 * Validate Manifest
 * Validate a manifest CSV file from S3.
 *
 * Checks the manifest file for:
 * - Required fields
 * - Data format compliance
 * - Value constraints
 *
 * Args:
 * s3_path: S3 path to the manifest CSV file to validate
 * valid: Mock parameter to simulate valid or invalid responses for testing
 *
 * Returns:
 * ManifestValidationResponse with validation status and any errors found
 */
export const validateManifestOptions = (
  options: Options<ValidateManifestData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await validateManifest({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: validateManifestQueryKey(options),
  })
}

/**
 * Validate Manifest
 * Validate a manifest CSV file from S3.
 *
 * Checks the manifest file for:
 * - Required fields
 * - Data format compliance
 * - Value constraints
 *
 * Args:
 * s3_path: S3 path to the manifest CSV file to validate
 * valid: Mock parameter to simulate valid or invalid responses for testing
 *
 * Returns:
 * ManifestValidationResponse with validation status and any errors found
 */
export const validateManifestMutation = (
  options?: Partial<Options<ValidateManifestData>>,
): UseMutationOptions<
  ValidateManifestResponse,
  AxiosError<ValidateManifestError>,
  Options<ValidateManifestData>
> => {
  const mutationOptions: UseMutationOptions<
    ValidateManifestResponse,
    AxiosError<ValidateManifestError>,
    Options<ValidateManifestData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await validateManifest({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWorkflowsQueryKey = (options?: Options<GetWorkflowsData>) =>
  createQueryKey('getWorkflows', options)

/**
 * Get Workflows
 * Returns a paginated list of workflows.
 */
export const getWorkflowsOptions = (options?: Options<GetWorkflowsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkflows({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWorkflowsQueryKey(options),
  })
}

export const getWorkflowsInfiniteQueryKey = (
  options?: Options<GetWorkflowsData>,
): QueryKey<Options<GetWorkflowsData>> =>
  createQueryKey('getWorkflows', options, true)

/**
 * Get Workflows
 * Returns a paginated list of workflows.
 */
export const getWorkflowsInfiniteOptions = (
  options?: Options<GetWorkflowsData>,
) => {
  return infiniteQueryOptions<
    GetWorkflowsResponse,
    AxiosError<GetWorkflowsError>,
    InfiniteData<GetWorkflowsResponse>,
    QueryKey<Options<GetWorkflowsData>>,
    | number
    | Pick<
        QueryKey<Options<GetWorkflowsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetWorkflowsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getWorkflows({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getWorkflowsInfiniteQueryKey(options),
    },
  )
}

export const createWorkflowQueryKey = (options: Options<CreateWorkflowData>) =>
  createQueryKey('createWorkflow', options)

/**
 * Create Workflow
 * Create a new workflow with optional attributes.
 */
export const createWorkflowOptions = (options: Options<CreateWorkflowData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createWorkflow({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: createWorkflowQueryKey(options),
  })
}

/**
 * Create Workflow
 * Create a new workflow with optional attributes.
 */
export const createWorkflowMutation = (
  options?: Partial<Options<CreateWorkflowData>>,
): UseMutationOptions<
  CreateWorkflowResponse,
  AxiosError<CreateWorkflowError>,
  Options<CreateWorkflowData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateWorkflowResponse,
    AxiosError<CreateWorkflowError>,
    Options<CreateWorkflowData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createWorkflow({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWorkflowByWorkflowIdQueryKey = (
  options: Options<GetWorkflowByWorkflowIdData>,
) => createQueryKey('getWorkflowByWorkflowId', options)

/**
 * Get Workflow By Workflow Id
 * Returns a single workflow by its workflow_id.
 * Note: This is different from its internal "id".
 */
export const getWorkflowByWorkflowIdOptions = (
  options: Options<GetWorkflowByWorkflowIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkflowByWorkflowId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWorkflowByWorkflowIdQueryKey(options),
  })
}
