/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RunsRouteImport } from './routes/runs.route'
import { Route as ProjectsRouteImport } from './routes/projects.route'
import { Route as IndexImport } from './routes/index'
import { Route as RunsIndexImport } from './routes/runs.index'
import { Route as ProjectsIndexImport } from './routes/projects.index'
import { Route as ProjectsProjectidRouteImport } from './routes/projects.$project_id.route'
import { Route as RunsRunbarcodeIndexImport } from './routes/runs.$run_barcode.index'
import { Route as ProjectsProjectidIndexImport } from './routes/projects.$project_id.index'
import { Route as ProjectsProjectidOverviewRouteImport } from './routes/projects.$project_id.overview.route'
import { Route as ProjectsProjectidIngestRouteImport } from './routes/projects.$project_id.ingest.route'
import { Route as ProjectsProjectidFilesRouteImport } from './routes/projects.$project_id.files.route'
import { Route as ProjectsProjectidActionsRouteImport } from './routes/projects.$project_id.actions.route'
import { Route as ProjectsProjectidOverviewIndexImport } from './routes/projects.$project_id.overview.index'
import { Route as ProjectsProjectidIngestIndexImport } from './routes/projects.$project_id.ingest.index'
import { Route as ProjectsProjectidFilesIndexImport } from './routes/projects.$project_id.files.index'
import { Route as ProjectsProjectidActionsIndexImport } from './routes/projects.$project_id.actions.index'

// Create/Update Routes

const RunsRouteRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRouteRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RunsIndexRoute = RunsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRouteRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)

const ProjectsProjectidRouteRoute = ProjectsProjectidRouteImport.update({
  id: '/$project_id',
  path: '/$project_id',
  getParentRoute: () => ProjectsRouteRoute,
} as any)

const RunsRunbarcodeIndexRoute = RunsRunbarcodeIndexImport.update({
  id: '/$run_barcode/',
  path: '/$run_barcode/',
  getParentRoute: () => RunsRouteRoute,
} as any)

const ProjectsProjectidIndexRoute = ProjectsProjectidIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectidRouteRoute,
} as any)

const ProjectsProjectidOverviewRouteRoute =
  ProjectsProjectidOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsProjectidRouteRoute,
  } as any)

const ProjectsProjectidIngestRouteRoute =
  ProjectsProjectidIngestRouteImport.update({
    id: '/ingest',
    path: '/ingest',
    getParentRoute: () => ProjectsProjectidRouteRoute,
  } as any)

const ProjectsProjectidFilesRouteRoute =
  ProjectsProjectidFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ProjectsProjectidRouteRoute,
  } as any)

const ProjectsProjectidActionsRouteRoute =
  ProjectsProjectidActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ProjectsProjectidRouteRoute,
  } as any)

const ProjectsProjectidOverviewIndexRoute =
  ProjectsProjectidOverviewIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectidOverviewRouteRoute,
  } as any)

const ProjectsProjectidIngestIndexRoute =
  ProjectsProjectidIngestIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectidIngestRouteRoute,
  } as any)

const ProjectsProjectidFilesIndexRoute =
  ProjectsProjectidFilesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectidFilesRouteRoute,
  } as any)

const ProjectsProjectidActionsIndexRoute =
  ProjectsProjectidActionsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectidActionsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRoute
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRoute
    }
    '/projects/$project_id': {
      id: '/projects/$project_id'
      path: '/$project_id'
      fullPath: '/projects/$project_id'
      preLoaderRoute: typeof ProjectsProjectidRouteImport
      parentRoute: typeof ProjectsRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof ProjectsRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexImport
      parentRoute: typeof RunsRouteImport
    }
    '/projects/$project_id/actions': {
      id: '/projects/$project_id/actions'
      path: '/actions'
      fullPath: '/projects/$project_id/actions'
      preLoaderRoute: typeof ProjectsProjectidActionsRouteImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/projects/$project_id/files': {
      id: '/projects/$project_id/files'
      path: '/files'
      fullPath: '/projects/$project_id/files'
      preLoaderRoute: typeof ProjectsProjectidFilesRouteImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/projects/$project_id/ingest': {
      id: '/projects/$project_id/ingest'
      path: '/ingest'
      fullPath: '/projects/$project_id/ingest'
      preLoaderRoute: typeof ProjectsProjectidIngestRouteImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/projects/$project_id/overview': {
      id: '/projects/$project_id/overview'
      path: '/overview'
      fullPath: '/projects/$project_id/overview'
      preLoaderRoute: typeof ProjectsProjectidOverviewRouteImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/projects/$project_id/': {
      id: '/projects/$project_id/'
      path: '/'
      fullPath: '/projects/$project_id/'
      preLoaderRoute: typeof ProjectsProjectidIndexImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/runs/$run_barcode/': {
      id: '/runs/$run_barcode/'
      path: '/$run_barcode'
      fullPath: '/runs/$run_barcode'
      preLoaderRoute: typeof RunsRunbarcodeIndexImport
      parentRoute: typeof RunsRouteImport
    }
    '/projects/$project_id/actions/': {
      id: '/projects/$project_id/actions/'
      path: '/'
      fullPath: '/projects/$project_id/actions/'
      preLoaderRoute: typeof ProjectsProjectidActionsIndexImport
      parentRoute: typeof ProjectsProjectidActionsRouteImport
    }
    '/projects/$project_id/files/': {
      id: '/projects/$project_id/files/'
      path: '/'
      fullPath: '/projects/$project_id/files/'
      preLoaderRoute: typeof ProjectsProjectidFilesIndexImport
      parentRoute: typeof ProjectsProjectidFilesRouteImport
    }
    '/projects/$project_id/ingest/': {
      id: '/projects/$project_id/ingest/'
      path: '/'
      fullPath: '/projects/$project_id/ingest/'
      preLoaderRoute: typeof ProjectsProjectidIngestIndexImport
      parentRoute: typeof ProjectsProjectidIngestRouteImport
    }
    '/projects/$project_id/overview/': {
      id: '/projects/$project_id/overview/'
      path: '/'
      fullPath: '/projects/$project_id/overview/'
      preLoaderRoute: typeof ProjectsProjectidOverviewIndexImport
      parentRoute: typeof ProjectsProjectidOverviewRouteImport
    }
  }
}

// Create and export the route tree

interface ProjectsProjectidActionsRouteRouteChildren {
  ProjectsProjectidActionsIndexRoute: typeof ProjectsProjectidActionsIndexRoute
}

const ProjectsProjectidActionsRouteRouteChildren: ProjectsProjectidActionsRouteRouteChildren =
  {
    ProjectsProjectidActionsIndexRoute: ProjectsProjectidActionsIndexRoute,
  }

const ProjectsProjectidActionsRouteRouteWithChildren =
  ProjectsProjectidActionsRouteRoute._addFileChildren(
    ProjectsProjectidActionsRouteRouteChildren,
  )

interface ProjectsProjectidFilesRouteRouteChildren {
  ProjectsProjectidFilesIndexRoute: typeof ProjectsProjectidFilesIndexRoute
}

const ProjectsProjectidFilesRouteRouteChildren: ProjectsProjectidFilesRouteRouteChildren =
  {
    ProjectsProjectidFilesIndexRoute: ProjectsProjectidFilesIndexRoute,
  }

const ProjectsProjectidFilesRouteRouteWithChildren =
  ProjectsProjectidFilesRouteRoute._addFileChildren(
    ProjectsProjectidFilesRouteRouteChildren,
  )

interface ProjectsProjectidIngestRouteRouteChildren {
  ProjectsProjectidIngestIndexRoute: typeof ProjectsProjectidIngestIndexRoute
}

const ProjectsProjectidIngestRouteRouteChildren: ProjectsProjectidIngestRouteRouteChildren =
  {
    ProjectsProjectidIngestIndexRoute: ProjectsProjectidIngestIndexRoute,
  }

const ProjectsProjectidIngestRouteRouteWithChildren =
  ProjectsProjectidIngestRouteRoute._addFileChildren(
    ProjectsProjectidIngestRouteRouteChildren,
  )

interface ProjectsProjectidOverviewRouteRouteChildren {
  ProjectsProjectidOverviewIndexRoute: typeof ProjectsProjectidOverviewIndexRoute
}

const ProjectsProjectidOverviewRouteRouteChildren: ProjectsProjectidOverviewRouteRouteChildren =
  {
    ProjectsProjectidOverviewIndexRoute: ProjectsProjectidOverviewIndexRoute,
  }

const ProjectsProjectidOverviewRouteRouteWithChildren =
  ProjectsProjectidOverviewRouteRoute._addFileChildren(
    ProjectsProjectidOverviewRouteRouteChildren,
  )

interface ProjectsProjectidRouteRouteChildren {
  ProjectsProjectidActionsRouteRoute: typeof ProjectsProjectidActionsRouteRouteWithChildren
  ProjectsProjectidFilesRouteRoute: typeof ProjectsProjectidFilesRouteRouteWithChildren
  ProjectsProjectidIngestRouteRoute: typeof ProjectsProjectidIngestRouteRouteWithChildren
  ProjectsProjectidOverviewRouteRoute: typeof ProjectsProjectidOverviewRouteRouteWithChildren
  ProjectsProjectidIndexRoute: typeof ProjectsProjectidIndexRoute
}

const ProjectsProjectidRouteRouteChildren: ProjectsProjectidRouteRouteChildren =
  {
    ProjectsProjectidActionsRouteRoute:
      ProjectsProjectidActionsRouteRouteWithChildren,
    ProjectsProjectidFilesRouteRoute:
      ProjectsProjectidFilesRouteRouteWithChildren,
    ProjectsProjectidIngestRouteRoute:
      ProjectsProjectidIngestRouteRouteWithChildren,
    ProjectsProjectidOverviewRouteRoute:
      ProjectsProjectidOverviewRouteRouteWithChildren,
    ProjectsProjectidIndexRoute: ProjectsProjectidIndexRoute,
  }

const ProjectsProjectidRouteRouteWithChildren =
  ProjectsProjectidRouteRoute._addFileChildren(
    ProjectsProjectidRouteRouteChildren,
  )

interface ProjectsRouteRouteChildren {
  ProjectsProjectidRouteRoute: typeof ProjectsProjectidRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsProjectidRouteRoute: ProjectsProjectidRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface RunsRouteRouteChildren {
  RunsIndexRoute: typeof RunsIndexRoute
  RunsRunbarcodeIndexRoute: typeof RunsRunbarcodeIndexRoute
}

const RunsRouteRouteChildren: RunsRouteRouteChildren = {
  RunsIndexRoute: RunsIndexRoute,
  RunsRunbarcodeIndexRoute: RunsRunbarcodeIndexRoute,
}

const RunsRouteRouteWithChildren = RunsRouteRoute._addFileChildren(
  RunsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/runs': typeof RunsRouteRouteWithChildren
  '/projects/$project_id': typeof ProjectsProjectidRouteRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/projects/$project_id/actions': typeof ProjectsProjectidActionsRouteRouteWithChildren
  '/projects/$project_id/files': typeof ProjectsProjectidFilesRouteRouteWithChildren
  '/projects/$project_id/ingest': typeof ProjectsProjectidIngestRouteRouteWithChildren
  '/projects/$project_id/overview': typeof ProjectsProjectidOverviewRouteRouteWithChildren
  '/projects/$project_id/': typeof ProjectsProjectidIndexRoute
  '/runs/$run_barcode': typeof RunsRunbarcodeIndexRoute
  '/projects/$project_id/actions/': typeof ProjectsProjectidActionsIndexRoute
  '/projects/$project_id/files/': typeof ProjectsProjectidFilesIndexRoute
  '/projects/$project_id/ingest/': typeof ProjectsProjectidIngestIndexRoute
  '/projects/$project_id/overview/': typeof ProjectsProjectidOverviewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/projects/$project_id': typeof ProjectsProjectidIndexRoute
  '/runs/$run_barcode': typeof RunsRunbarcodeIndexRoute
  '/projects/$project_id/actions': typeof ProjectsProjectidActionsIndexRoute
  '/projects/$project_id/files': typeof ProjectsProjectidFilesIndexRoute
  '/projects/$project_id/ingest': typeof ProjectsProjectidIngestIndexRoute
  '/projects/$project_id/overview': typeof ProjectsProjectidOverviewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/runs': typeof RunsRouteRouteWithChildren
  '/projects/$project_id': typeof ProjectsProjectidRouteRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/projects/$project_id/actions': typeof ProjectsProjectidActionsRouteRouteWithChildren
  '/projects/$project_id/files': typeof ProjectsProjectidFilesRouteRouteWithChildren
  '/projects/$project_id/ingest': typeof ProjectsProjectidIngestRouteRouteWithChildren
  '/projects/$project_id/overview': typeof ProjectsProjectidOverviewRouteRouteWithChildren
  '/projects/$project_id/': typeof ProjectsProjectidIndexRoute
  '/runs/$run_barcode/': typeof RunsRunbarcodeIndexRoute
  '/projects/$project_id/actions/': typeof ProjectsProjectidActionsIndexRoute
  '/projects/$project_id/files/': typeof ProjectsProjectidFilesIndexRoute
  '/projects/$project_id/ingest/': typeof ProjectsProjectidIngestIndexRoute
  '/projects/$project_id/overview/': typeof ProjectsProjectidOverviewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/runs'
    | '/projects/$project_id'
    | '/projects/'
    | '/runs/'
    | '/projects/$project_id/actions'
    | '/projects/$project_id/files'
    | '/projects/$project_id/ingest'
    | '/projects/$project_id/overview'
    | '/projects/$project_id/'
    | '/runs/$run_barcode'
    | '/projects/$project_id/actions/'
    | '/projects/$project_id/files/'
    | '/projects/$project_id/ingest/'
    | '/projects/$project_id/overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/runs'
    | '/projects/$project_id'
    | '/runs/$run_barcode'
    | '/projects/$project_id/actions'
    | '/projects/$project_id/files'
    | '/projects/$project_id/ingest'
    | '/projects/$project_id/overview'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/runs'
    | '/projects/$project_id'
    | '/projects/'
    | '/runs/'
    | '/projects/$project_id/actions'
    | '/projects/$project_id/files'
    | '/projects/$project_id/ingest'
    | '/projects/$project_id/overview'
    | '/projects/$project_id/'
    | '/runs/$run_barcode/'
    | '/projects/$project_id/actions/'
    | '/projects/$project_id/files/'
    | '/projects/$project_id/ingest/'
    | '/projects/$project_id/overview/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  RunsRouteRoute: typeof RunsRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  RunsRouteRoute: RunsRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projects",
        "/runs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/projects": {
      "filePath": "projects.route.tsx",
      "children": [
        "/projects/$project_id",
        "/projects/"
      ]
    },
    "/runs": {
      "filePath": "runs.route.tsx",
      "children": [
        "/runs/",
        "/runs/$run_barcode/"
      ]
    },
    "/projects/$project_id": {
      "filePath": "projects.$project_id.route.tsx",
      "parent": "/projects",
      "children": [
        "/projects/$project_id/actions",
        "/projects/$project_id/files",
        "/projects/$project_id/ingest",
        "/projects/$project_id/overview",
        "/projects/$project_id/"
      ]
    },
    "/projects/": {
      "filePath": "projects.index.tsx",
      "parent": "/projects"
    },
    "/runs/": {
      "filePath": "runs.index.tsx",
      "parent": "/runs"
    },
    "/projects/$project_id/actions": {
      "filePath": "projects.$project_id.actions.route.tsx",
      "parent": "/projects/$project_id",
      "children": [
        "/projects/$project_id/actions/"
      ]
    },
    "/projects/$project_id/files": {
      "filePath": "projects.$project_id.files.route.tsx",
      "parent": "/projects/$project_id",
      "children": [
        "/projects/$project_id/files/"
      ]
    },
    "/projects/$project_id/ingest": {
      "filePath": "projects.$project_id.ingest.route.tsx",
      "parent": "/projects/$project_id",
      "children": [
        "/projects/$project_id/ingest/"
      ]
    },
    "/projects/$project_id/overview": {
      "filePath": "projects.$project_id.overview.route.tsx",
      "parent": "/projects/$project_id",
      "children": [
        "/projects/$project_id/overview/"
      ]
    },
    "/projects/$project_id/": {
      "filePath": "projects.$project_id.index.tsx",
      "parent": "/projects/$project_id"
    },
    "/runs/$run_barcode/": {
      "filePath": "runs.$run_barcode.index.tsx",
      "parent": "/runs"
    },
    "/projects/$project_id/actions/": {
      "filePath": "projects.$project_id.actions.index.tsx",
      "parent": "/projects/$project_id/actions"
    },
    "/projects/$project_id/files/": {
      "filePath": "projects.$project_id.files.index.tsx",
      "parent": "/projects/$project_id/files"
    },
    "/projects/$project_id/ingest/": {
      "filePath": "projects.$project_id.ingest.index.tsx",
      "parent": "/projects/$project_id/ingest"
    },
    "/projects/$project_id/overview/": {
      "filePath": "projects.$project_id.overview.index.tsx",
      "parent": "/projects/$project_id/overview"
    }
  }
}
ROUTE_MANIFEST_END */
