/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RunsRouteImport } from './routes/runs.route'
import { Route as ProjectsRouteImport } from './routes/projects.route'
import { Route as AdminRouteImport } from './routes/admin.route'
import { Route as IndexImport } from './routes/index'
import { Route as RunsIndexImport } from './routes/runs.index'
import { Route as ProjectsIndexImport } from './routes/projects.index'
import { Route as AdminIndexImport } from './routes/admin.index'
import { Route as RunsRunbarcodeRouteImport } from './routes/runs.$run_barcode.route'
import { Route as ProjectsProjectidRouteImport } from './routes/projects.$project_id.route'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors.route'
import { Route as RunsRunbarcodeIndexImport } from './routes/runs.$run_barcode.index'
import { Route as ProjectsProjectidIndexImport } from './routes/projects.$project_id.index'
import { Route as AdminVendorsIndexImport } from './routes/admin.vendors.index'
import { Route as RunsRunbarcodeSamplesheetRouteImport } from './routes/runs.$run_barcode.samplesheet.route'
import { Route as RunsRunbarcodeIndexqcRouteImport } from './routes/runs.$run_barcode.indexqc.route'
import { Route as ProjectsProjectidOverviewRouteImport } from './routes/projects.$project_id.overview.route'
import { Route as ProjectsProjectidIngestRouteImport } from './routes/projects.$project_id.ingest.route'
import { Route as ProjectsProjectidFilesRouteImport } from './routes/projects.$project_id.files.route'
import { Route as ProjectsProjectidActionsRouteImport } from './routes/projects.$project_id.actions.route'
import { Route as RunsRunbarcodeSamplesheetIndexImport } from './routes/runs.$run_barcode.samplesheet.index'
import { Route as RunsRunbarcodeIndexqcIndexImport } from './routes/runs.$run_barcode.indexqc.index'
import { Route as ProjectsProjectidOverviewIndexImport } from './routes/projects.$project_id.overview.index'
import { Route as ProjectsProjectidIngestIndexImport } from './routes/projects.$project_id.ingest.index'
import { Route as ProjectsProjectidFilesIndexImport } from './routes/projects.$project_id.files.index'
import { Route as ProjectsProjectidActionsIndexImport } from './routes/projects.$project_id.actions.index'

// Create/Update Routes

const RunsRouteRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRouteRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RunsIndexRoute = RunsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRouteRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const RunsRunbarcodeRouteRoute = RunsRunbarcodeRouteImport.update({
  id: '/$run_barcode',
  path: '/$run_barcode',
  getParentRoute: () => RunsRouteRoute,
} as any)

const ProjectsProjectidRouteRoute = ProjectsProjectidRouteImport.update({
  id: '/$project_id',
  path: '/$project_id',
  getParentRoute: () => ProjectsRouteRoute,
} as any)

const AdminVendorsRouteRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRouteRoute,
} as any)

const RunsRunbarcodeIndexRoute = RunsRunbarcodeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRunbarcodeRouteRoute,
} as any)

const ProjectsProjectidIndexRoute = ProjectsProjectidIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectidRouteRoute,
} as any)

const AdminVendorsIndexRoute = AdminVendorsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminVendorsRouteRoute,
} as any)

const RunsRunbarcodeSamplesheetRouteRoute =
  RunsRunbarcodeSamplesheetRouteImport.update({
    id: '/samplesheet',
    path: '/samplesheet',
    getParentRoute: () => RunsRunbarcodeRouteRoute,
  } as any)

const RunsRunbarcodeIndexqcRouteRoute = RunsRunbarcodeIndexqcRouteImport.update(
  {
    id: '/indexqc',
    path: '/indexqc',
    getParentRoute: () => RunsRunbarcodeRouteRoute,
  } as any,
)

const ProjectsProjectidOverviewRouteRoute =
  ProjectsProjectidOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsProjectidRouteRoute,
  } as any)

const ProjectsProjectidIngestRouteRoute =
  ProjectsProjectidIngestRouteImport.update({
    id: '/ingest',
    path: '/ingest',
    getParentRoute: () => ProjectsProjectidRouteRoute,
  } as any)

const ProjectsProjectidFilesRouteRoute =
  ProjectsProjectidFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ProjectsProjectidRouteRoute,
  } as any)

const ProjectsProjectidActionsRouteRoute =
  ProjectsProjectidActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ProjectsProjectidRouteRoute,
  } as any)

const RunsRunbarcodeSamplesheetIndexRoute =
  RunsRunbarcodeSamplesheetIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RunsRunbarcodeSamplesheetRouteRoute,
  } as any)

const RunsRunbarcodeIndexqcIndexRoute = RunsRunbarcodeIndexqcIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => RunsRunbarcodeIndexqcRouteRoute,
  } as any,
)

const ProjectsProjectidOverviewIndexRoute =
  ProjectsProjectidOverviewIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectidOverviewRouteRoute,
  } as any)

const ProjectsProjectidIngestIndexRoute =
  ProjectsProjectidIngestIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectidIngestRouteRoute,
  } as any)

const ProjectsProjectidFilesIndexRoute =
  ProjectsProjectidFilesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectidFilesRouteRoute,
  } as any)

const ProjectsProjectidActionsIndexRoute =
  ProjectsProjectidActionsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectidActionsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRoute
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/projects/$project_id': {
      id: '/projects/$project_id'
      path: '/$project_id'
      fullPath: '/projects/$project_id'
      preLoaderRoute: typeof ProjectsProjectidRouteImport
      parentRoute: typeof ProjectsRouteImport
    }
    '/runs/$run_barcode': {
      id: '/runs/$run_barcode'
      path: '/$run_barcode'
      fullPath: '/runs/$run_barcode'
      preLoaderRoute: typeof RunsRunbarcodeRouteImport
      parentRoute: typeof RunsRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof ProjectsRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexImport
      parentRoute: typeof RunsRouteImport
    }
    '/projects/$project_id/actions': {
      id: '/projects/$project_id/actions'
      path: '/actions'
      fullPath: '/projects/$project_id/actions'
      preLoaderRoute: typeof ProjectsProjectidActionsRouteImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/projects/$project_id/files': {
      id: '/projects/$project_id/files'
      path: '/files'
      fullPath: '/projects/$project_id/files'
      preLoaderRoute: typeof ProjectsProjectidFilesRouteImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/projects/$project_id/ingest': {
      id: '/projects/$project_id/ingest'
      path: '/ingest'
      fullPath: '/projects/$project_id/ingest'
      preLoaderRoute: typeof ProjectsProjectidIngestRouteImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/projects/$project_id/overview': {
      id: '/projects/$project_id/overview'
      path: '/overview'
      fullPath: '/projects/$project_id/overview'
      preLoaderRoute: typeof ProjectsProjectidOverviewRouteImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/runs/$run_barcode/indexqc': {
      id: '/runs/$run_barcode/indexqc'
      path: '/indexqc'
      fullPath: '/runs/$run_barcode/indexqc'
      preLoaderRoute: typeof RunsRunbarcodeIndexqcRouteImport
      parentRoute: typeof RunsRunbarcodeRouteImport
    }
    '/runs/$run_barcode/samplesheet': {
      id: '/runs/$run_barcode/samplesheet'
      path: '/samplesheet'
      fullPath: '/runs/$run_barcode/samplesheet'
      preLoaderRoute: typeof RunsRunbarcodeSamplesheetRouteImport
      parentRoute: typeof RunsRunbarcodeRouteImport
    }
    '/admin/vendors/': {
      id: '/admin/vendors/'
      path: '/'
      fullPath: '/admin/vendors/'
      preLoaderRoute: typeof AdminVendorsIndexImport
      parentRoute: typeof AdminVendorsRouteImport
    }
    '/projects/$project_id/': {
      id: '/projects/$project_id/'
      path: '/'
      fullPath: '/projects/$project_id/'
      preLoaderRoute: typeof ProjectsProjectidIndexImport
      parentRoute: typeof ProjectsProjectidRouteImport
    }
    '/runs/$run_barcode/': {
      id: '/runs/$run_barcode/'
      path: '/'
      fullPath: '/runs/$run_barcode/'
      preLoaderRoute: typeof RunsRunbarcodeIndexImport
      parentRoute: typeof RunsRunbarcodeRouteImport
    }
    '/projects/$project_id/actions/': {
      id: '/projects/$project_id/actions/'
      path: '/'
      fullPath: '/projects/$project_id/actions/'
      preLoaderRoute: typeof ProjectsProjectidActionsIndexImport
      parentRoute: typeof ProjectsProjectidActionsRouteImport
    }
    '/projects/$project_id/files/': {
      id: '/projects/$project_id/files/'
      path: '/'
      fullPath: '/projects/$project_id/files/'
      preLoaderRoute: typeof ProjectsProjectidFilesIndexImport
      parentRoute: typeof ProjectsProjectidFilesRouteImport
    }
    '/projects/$project_id/ingest/': {
      id: '/projects/$project_id/ingest/'
      path: '/'
      fullPath: '/projects/$project_id/ingest/'
      preLoaderRoute: typeof ProjectsProjectidIngestIndexImport
      parentRoute: typeof ProjectsProjectidIngestRouteImport
    }
    '/projects/$project_id/overview/': {
      id: '/projects/$project_id/overview/'
      path: '/'
      fullPath: '/projects/$project_id/overview/'
      preLoaderRoute: typeof ProjectsProjectidOverviewIndexImport
      parentRoute: typeof ProjectsProjectidOverviewRouteImport
    }
    '/runs/$run_barcode/indexqc/': {
      id: '/runs/$run_barcode/indexqc/'
      path: '/'
      fullPath: '/runs/$run_barcode/indexqc/'
      preLoaderRoute: typeof RunsRunbarcodeIndexqcIndexImport
      parentRoute: typeof RunsRunbarcodeIndexqcRouteImport
    }
    '/runs/$run_barcode/samplesheet/': {
      id: '/runs/$run_barcode/samplesheet/'
      path: '/'
      fullPath: '/runs/$run_barcode/samplesheet/'
      preLoaderRoute: typeof RunsRunbarcodeSamplesheetIndexImport
      parentRoute: typeof RunsRunbarcodeSamplesheetRouteImport
    }
  }
}

// Create and export the route tree

interface AdminVendorsRouteRouteChildren {
  AdminVendorsIndexRoute: typeof AdminVendorsIndexRoute
}

const AdminVendorsRouteRouteChildren: AdminVendorsRouteRouteChildren = {
  AdminVendorsIndexRoute: AdminVendorsIndexRoute,
}

const AdminVendorsRouteRouteWithChildren =
  AdminVendorsRouteRoute._addFileChildren(AdminVendorsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminVendorsRouteRoute: typeof AdminVendorsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminVendorsRouteRoute: AdminVendorsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ProjectsProjectidActionsRouteRouteChildren {
  ProjectsProjectidActionsIndexRoute: typeof ProjectsProjectidActionsIndexRoute
}

const ProjectsProjectidActionsRouteRouteChildren: ProjectsProjectidActionsRouteRouteChildren =
  {
    ProjectsProjectidActionsIndexRoute: ProjectsProjectidActionsIndexRoute,
  }

const ProjectsProjectidActionsRouteRouteWithChildren =
  ProjectsProjectidActionsRouteRoute._addFileChildren(
    ProjectsProjectidActionsRouteRouteChildren,
  )

interface ProjectsProjectidFilesRouteRouteChildren {
  ProjectsProjectidFilesIndexRoute: typeof ProjectsProjectidFilesIndexRoute
}

const ProjectsProjectidFilesRouteRouteChildren: ProjectsProjectidFilesRouteRouteChildren =
  {
    ProjectsProjectidFilesIndexRoute: ProjectsProjectidFilesIndexRoute,
  }

const ProjectsProjectidFilesRouteRouteWithChildren =
  ProjectsProjectidFilesRouteRoute._addFileChildren(
    ProjectsProjectidFilesRouteRouteChildren,
  )

interface ProjectsProjectidIngestRouteRouteChildren {
  ProjectsProjectidIngestIndexRoute: typeof ProjectsProjectidIngestIndexRoute
}

const ProjectsProjectidIngestRouteRouteChildren: ProjectsProjectidIngestRouteRouteChildren =
  {
    ProjectsProjectidIngestIndexRoute: ProjectsProjectidIngestIndexRoute,
  }

const ProjectsProjectidIngestRouteRouteWithChildren =
  ProjectsProjectidIngestRouteRoute._addFileChildren(
    ProjectsProjectidIngestRouteRouteChildren,
  )

interface ProjectsProjectidOverviewRouteRouteChildren {
  ProjectsProjectidOverviewIndexRoute: typeof ProjectsProjectidOverviewIndexRoute
}

const ProjectsProjectidOverviewRouteRouteChildren: ProjectsProjectidOverviewRouteRouteChildren =
  {
    ProjectsProjectidOverviewIndexRoute: ProjectsProjectidOverviewIndexRoute,
  }

const ProjectsProjectidOverviewRouteRouteWithChildren =
  ProjectsProjectidOverviewRouteRoute._addFileChildren(
    ProjectsProjectidOverviewRouteRouteChildren,
  )

interface ProjectsProjectidRouteRouteChildren {
  ProjectsProjectidActionsRouteRoute: typeof ProjectsProjectidActionsRouteRouteWithChildren
  ProjectsProjectidFilesRouteRoute: typeof ProjectsProjectidFilesRouteRouteWithChildren
  ProjectsProjectidIngestRouteRoute: typeof ProjectsProjectidIngestRouteRouteWithChildren
  ProjectsProjectidOverviewRouteRoute: typeof ProjectsProjectidOverviewRouteRouteWithChildren
  ProjectsProjectidIndexRoute: typeof ProjectsProjectidIndexRoute
}

const ProjectsProjectidRouteRouteChildren: ProjectsProjectidRouteRouteChildren =
  {
    ProjectsProjectidActionsRouteRoute:
      ProjectsProjectidActionsRouteRouteWithChildren,
    ProjectsProjectidFilesRouteRoute:
      ProjectsProjectidFilesRouteRouteWithChildren,
    ProjectsProjectidIngestRouteRoute:
      ProjectsProjectidIngestRouteRouteWithChildren,
    ProjectsProjectidOverviewRouteRoute:
      ProjectsProjectidOverviewRouteRouteWithChildren,
    ProjectsProjectidIndexRoute: ProjectsProjectidIndexRoute,
  }

const ProjectsProjectidRouteRouteWithChildren =
  ProjectsProjectidRouteRoute._addFileChildren(
    ProjectsProjectidRouteRouteChildren,
  )

interface ProjectsRouteRouteChildren {
  ProjectsProjectidRouteRoute: typeof ProjectsProjectidRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsProjectidRouteRoute: ProjectsProjectidRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

interface RunsRunbarcodeIndexqcRouteRouteChildren {
  RunsRunbarcodeIndexqcIndexRoute: typeof RunsRunbarcodeIndexqcIndexRoute
}

const RunsRunbarcodeIndexqcRouteRouteChildren: RunsRunbarcodeIndexqcRouteRouteChildren =
  {
    RunsRunbarcodeIndexqcIndexRoute: RunsRunbarcodeIndexqcIndexRoute,
  }

const RunsRunbarcodeIndexqcRouteRouteWithChildren =
  RunsRunbarcodeIndexqcRouteRoute._addFileChildren(
    RunsRunbarcodeIndexqcRouteRouteChildren,
  )

interface RunsRunbarcodeSamplesheetRouteRouteChildren {
  RunsRunbarcodeSamplesheetIndexRoute: typeof RunsRunbarcodeSamplesheetIndexRoute
}

const RunsRunbarcodeSamplesheetRouteRouteChildren: RunsRunbarcodeSamplesheetRouteRouteChildren =
  {
    RunsRunbarcodeSamplesheetIndexRoute: RunsRunbarcodeSamplesheetIndexRoute,
  }

const RunsRunbarcodeSamplesheetRouteRouteWithChildren =
  RunsRunbarcodeSamplesheetRouteRoute._addFileChildren(
    RunsRunbarcodeSamplesheetRouteRouteChildren,
  )

interface RunsRunbarcodeRouteRouteChildren {
  RunsRunbarcodeIndexqcRouteRoute: typeof RunsRunbarcodeIndexqcRouteRouteWithChildren
  RunsRunbarcodeSamplesheetRouteRoute: typeof RunsRunbarcodeSamplesheetRouteRouteWithChildren
  RunsRunbarcodeIndexRoute: typeof RunsRunbarcodeIndexRoute
}

const RunsRunbarcodeRouteRouteChildren: RunsRunbarcodeRouteRouteChildren = {
  RunsRunbarcodeIndexqcRouteRoute: RunsRunbarcodeIndexqcRouteRouteWithChildren,
  RunsRunbarcodeSamplesheetRouteRoute:
    RunsRunbarcodeSamplesheetRouteRouteWithChildren,
  RunsRunbarcodeIndexRoute: RunsRunbarcodeIndexRoute,
}

const RunsRunbarcodeRouteRouteWithChildren =
  RunsRunbarcodeRouteRoute._addFileChildren(RunsRunbarcodeRouteRouteChildren)

interface RunsRouteRouteChildren {
  RunsRunbarcodeRouteRoute: typeof RunsRunbarcodeRouteRouteWithChildren
  RunsIndexRoute: typeof RunsIndexRoute
}

const RunsRouteRouteChildren: RunsRouteRouteChildren = {
  RunsRunbarcodeRouteRoute: RunsRunbarcodeRouteRouteWithChildren,
  RunsIndexRoute: RunsIndexRoute,
}

const RunsRouteRouteWithChildren = RunsRouteRoute._addFileChildren(
  RunsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/runs': typeof RunsRouteRouteWithChildren
  '/admin/vendors': typeof AdminVendorsRouteRouteWithChildren
  '/projects/$project_id': typeof ProjectsProjectidRouteRouteWithChildren
  '/runs/$run_barcode': typeof RunsRunbarcodeRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/projects/$project_id/actions': typeof ProjectsProjectidActionsRouteRouteWithChildren
  '/projects/$project_id/files': typeof ProjectsProjectidFilesRouteRouteWithChildren
  '/projects/$project_id/ingest': typeof ProjectsProjectidIngestRouteRouteWithChildren
  '/projects/$project_id/overview': typeof ProjectsProjectidOverviewRouteRouteWithChildren
  '/runs/$run_barcode/indexqc': typeof RunsRunbarcodeIndexqcRouteRouteWithChildren
  '/runs/$run_barcode/samplesheet': typeof RunsRunbarcodeSamplesheetRouteRouteWithChildren
  '/admin/vendors/': typeof AdminVendorsIndexRoute
  '/projects/$project_id/': typeof ProjectsProjectidIndexRoute
  '/runs/$run_barcode/': typeof RunsRunbarcodeIndexRoute
  '/projects/$project_id/actions/': typeof ProjectsProjectidActionsIndexRoute
  '/projects/$project_id/files/': typeof ProjectsProjectidFilesIndexRoute
  '/projects/$project_id/ingest/': typeof ProjectsProjectidIngestIndexRoute
  '/projects/$project_id/overview/': typeof ProjectsProjectidOverviewIndexRoute
  '/runs/$run_barcode/indexqc/': typeof RunsRunbarcodeIndexqcIndexRoute
  '/runs/$run_barcode/samplesheet/': typeof RunsRunbarcodeSamplesheetIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/admin/vendors': typeof AdminVendorsIndexRoute
  '/projects/$project_id': typeof ProjectsProjectidIndexRoute
  '/runs/$run_barcode': typeof RunsRunbarcodeIndexRoute
  '/projects/$project_id/actions': typeof ProjectsProjectidActionsIndexRoute
  '/projects/$project_id/files': typeof ProjectsProjectidFilesIndexRoute
  '/projects/$project_id/ingest': typeof ProjectsProjectidIngestIndexRoute
  '/projects/$project_id/overview': typeof ProjectsProjectidOverviewIndexRoute
  '/runs/$run_barcode/indexqc': typeof RunsRunbarcodeIndexqcIndexRoute
  '/runs/$run_barcode/samplesheet': typeof RunsRunbarcodeSamplesheetIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/runs': typeof RunsRouteRouteWithChildren
  '/admin/vendors': typeof AdminVendorsRouteRouteWithChildren
  '/projects/$project_id': typeof ProjectsProjectidRouteRouteWithChildren
  '/runs/$run_barcode': typeof RunsRunbarcodeRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/projects/$project_id/actions': typeof ProjectsProjectidActionsRouteRouteWithChildren
  '/projects/$project_id/files': typeof ProjectsProjectidFilesRouteRouteWithChildren
  '/projects/$project_id/ingest': typeof ProjectsProjectidIngestRouteRouteWithChildren
  '/projects/$project_id/overview': typeof ProjectsProjectidOverviewRouteRouteWithChildren
  '/runs/$run_barcode/indexqc': typeof RunsRunbarcodeIndexqcRouteRouteWithChildren
  '/runs/$run_barcode/samplesheet': typeof RunsRunbarcodeSamplesheetRouteRouteWithChildren
  '/admin/vendors/': typeof AdminVendorsIndexRoute
  '/projects/$project_id/': typeof ProjectsProjectidIndexRoute
  '/runs/$run_barcode/': typeof RunsRunbarcodeIndexRoute
  '/projects/$project_id/actions/': typeof ProjectsProjectidActionsIndexRoute
  '/projects/$project_id/files/': typeof ProjectsProjectidFilesIndexRoute
  '/projects/$project_id/ingest/': typeof ProjectsProjectidIngestIndexRoute
  '/projects/$project_id/overview/': typeof ProjectsProjectidOverviewIndexRoute
  '/runs/$run_barcode/indexqc/': typeof RunsRunbarcodeIndexqcIndexRoute
  '/runs/$run_barcode/samplesheet/': typeof RunsRunbarcodeSamplesheetIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/projects'
    | '/runs'
    | '/admin/vendors'
    | '/projects/$project_id'
    | '/runs/$run_barcode'
    | '/admin/'
    | '/projects/'
    | '/runs/'
    | '/projects/$project_id/actions'
    | '/projects/$project_id/files'
    | '/projects/$project_id/ingest'
    | '/projects/$project_id/overview'
    | '/runs/$run_barcode/indexqc'
    | '/runs/$run_barcode/samplesheet'
    | '/admin/vendors/'
    | '/projects/$project_id/'
    | '/runs/$run_barcode/'
    | '/projects/$project_id/actions/'
    | '/projects/$project_id/files/'
    | '/projects/$project_id/ingest/'
    | '/projects/$project_id/overview/'
    | '/runs/$run_barcode/indexqc/'
    | '/runs/$run_barcode/samplesheet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/projects'
    | '/runs'
    | '/admin/vendors'
    | '/projects/$project_id'
    | '/runs/$run_barcode'
    | '/projects/$project_id/actions'
    | '/projects/$project_id/files'
    | '/projects/$project_id/ingest'
    | '/projects/$project_id/overview'
    | '/runs/$run_barcode/indexqc'
    | '/runs/$run_barcode/samplesheet'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/projects'
    | '/runs'
    | '/admin/vendors'
    | '/projects/$project_id'
    | '/runs/$run_barcode'
    | '/admin/'
    | '/projects/'
    | '/runs/'
    | '/projects/$project_id/actions'
    | '/projects/$project_id/files'
    | '/projects/$project_id/ingest'
    | '/projects/$project_id/overview'
    | '/runs/$run_barcode/indexqc'
    | '/runs/$run_barcode/samplesheet'
    | '/admin/vendors/'
    | '/projects/$project_id/'
    | '/runs/$run_barcode/'
    | '/projects/$project_id/actions/'
    | '/projects/$project_id/files/'
    | '/projects/$project_id/ingest/'
    | '/projects/$project_id/overview/'
    | '/runs/$run_barcode/indexqc/'
    | '/runs/$run_barcode/samplesheet/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  RunsRouteRoute: typeof RunsRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  RunsRouteRoute: RunsRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/projects",
        "/runs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.route.tsx",
      "children": [
        "/admin/vendors",
        "/admin/"
      ]
    },
    "/projects": {
      "filePath": "projects.route.tsx",
      "children": [
        "/projects/$project_id",
        "/projects/"
      ]
    },
    "/runs": {
      "filePath": "runs.route.tsx",
      "children": [
        "/runs/$run_barcode",
        "/runs/"
      ]
    },
    "/admin/vendors": {
      "filePath": "admin.vendors.route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/vendors/"
      ]
    },
    "/projects/$project_id": {
      "filePath": "projects.$project_id.route.tsx",
      "parent": "/projects",
      "children": [
        "/projects/$project_id/actions",
        "/projects/$project_id/files",
        "/projects/$project_id/ingest",
        "/projects/$project_id/overview",
        "/projects/$project_id/"
      ]
    },
    "/runs/$run_barcode": {
      "filePath": "runs.$run_barcode.route.tsx",
      "parent": "/runs",
      "children": [
        "/runs/$run_barcode/indexqc",
        "/runs/$run_barcode/samplesheet",
        "/runs/$run_barcode/"
      ]
    },
    "/admin/": {
      "filePath": "admin.index.tsx",
      "parent": "/admin"
    },
    "/projects/": {
      "filePath": "projects.index.tsx",
      "parent": "/projects"
    },
    "/runs/": {
      "filePath": "runs.index.tsx",
      "parent": "/runs"
    },
    "/projects/$project_id/actions": {
      "filePath": "projects.$project_id.actions.route.tsx",
      "parent": "/projects/$project_id",
      "children": [
        "/projects/$project_id/actions/"
      ]
    },
    "/projects/$project_id/files": {
      "filePath": "projects.$project_id.files.route.tsx",
      "parent": "/projects/$project_id",
      "children": [
        "/projects/$project_id/files/"
      ]
    },
    "/projects/$project_id/ingest": {
      "filePath": "projects.$project_id.ingest.route.tsx",
      "parent": "/projects/$project_id",
      "children": [
        "/projects/$project_id/ingest/"
      ]
    },
    "/projects/$project_id/overview": {
      "filePath": "projects.$project_id.overview.route.tsx",
      "parent": "/projects/$project_id",
      "children": [
        "/projects/$project_id/overview/"
      ]
    },
    "/runs/$run_barcode/indexqc": {
      "filePath": "runs.$run_barcode.indexqc.route.tsx",
      "parent": "/runs/$run_barcode",
      "children": [
        "/runs/$run_barcode/indexqc/"
      ]
    },
    "/runs/$run_barcode/samplesheet": {
      "filePath": "runs.$run_barcode.samplesheet.route.tsx",
      "parent": "/runs/$run_barcode",
      "children": [
        "/runs/$run_barcode/samplesheet/"
      ]
    },
    "/admin/vendors/": {
      "filePath": "admin.vendors.index.tsx",
      "parent": "/admin/vendors"
    },
    "/projects/$project_id/": {
      "filePath": "projects.$project_id.index.tsx",
      "parent": "/projects/$project_id"
    },
    "/runs/$run_barcode/": {
      "filePath": "runs.$run_barcode.index.tsx",
      "parent": "/runs/$run_barcode"
    },
    "/projects/$project_id/actions/": {
      "filePath": "projects.$project_id.actions.index.tsx",
      "parent": "/projects/$project_id/actions"
    },
    "/projects/$project_id/files/": {
      "filePath": "projects.$project_id.files.index.tsx",
      "parent": "/projects/$project_id/files"
    },
    "/projects/$project_id/ingest/": {
      "filePath": "projects.$project_id.ingest.index.tsx",
      "parent": "/projects/$project_id/ingest"
    },
    "/projects/$project_id/overview/": {
      "filePath": "projects.$project_id.overview.index.tsx",
      "parent": "/projects/$project_id/overview"
    },
    "/runs/$run_barcode/indexqc/": {
      "filePath": "runs.$run_barcode.indexqc.index.tsx",
      "parent": "/runs/$run_barcode/indexqc"
    },
    "/runs/$run_barcode/samplesheet/": {
      "filePath": "runs.$run_barcode.samplesheet.index.tsx",
      "parent": "/runs/$run_barcode/samplesheet"
    }
  }
}
ROUTE_MANIFEST_END */
