/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as UserRouteImport } from './routes/_user.route'
import { Route as HomeRouteImport } from './routes/_home.route'
import { Route as HomeIndexImport } from './routes/_home.index'
import { Route as HomeRunsRouteImport } from './routes/_home.runs.route'
import { Route as HomeProjectsRouteImport } from './routes/_home.projects.route'
import { Route as HomeJobsRouteImport } from './routes/_home.jobs.route'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated._home.route'
import { Route as UserRegisterIndexImport } from './routes/_user.register.index'
import { Route as UserPasswordResetIndexImport } from './routes/_user.password-reset.index'
import { Route as UserLoginIndexImport } from './routes/_user.login.index'
import { Route as HomeRunsIndexImport } from './routes/_home.runs.index'
import { Route as HomeProjectsIndexImport } from './routes/_home.projects.index'
import { Route as HomeJobsIndexImport } from './routes/_home.jobs.index'
import { Route as HomeRunsRunbarcodeRouteImport } from './routes/_home.runs.$run_barcode.route'
import { Route as HomeProjectsProjectidRouteImport } from './routes/_home.projects.$project_id.route'
import { Route as HomeJobsJobidRouteImport } from './routes/_home.jobs.$job_id.route'
import { Route as AuthenticatedHomeProfileRouteImport } from './routes/_authenticated._home.profile.route'
import { Route as AuthenticatedHomeAdminRouteImport } from './routes/_authenticated._home.admin.route'
import { Route as HomeRunsRunbarcodeIndexImport } from './routes/_home.runs.$run_barcode.index'
import { Route as HomeProjectsProjectidIndexImport } from './routes/_home.projects.$project_id.index'
import { Route as HomeJobsJobidIndexImport } from './routes/_home.jobs.$job_id.index'
import { Route as AuthenticatedHomeProfileIndexImport } from './routes/_authenticated._home.profile.index'
import { Route as AuthenticatedHomeAdminIndexImport } from './routes/_authenticated._home.admin.index'
import { Route as HomeRunsRunbarcodeSamplesheetRouteImport } from './routes/_home.runs.$run_barcode.samplesheet.route'
import { Route as HomeRunsRunbarcodeIndexqcRouteImport } from './routes/_home.runs.$run_barcode.indexqc.route'
import { Route as AuthenticatedHomeAdminVendorsRouteImport } from './routes/_authenticated._home.admin.vendors.route'
import { Route as AuthenticatedHomeAdminRunSettingsRouteImport } from './routes/_authenticated._home.admin.run-settings.route'
import { Route as AuthenticatedHomeAdminProjectSettingsRouteImport } from './routes/_authenticated._home.admin.project-settings.route'
import { Route as AuthenticatedHomeAdminJobsRouteImport } from './routes/_authenticated._home.admin.jobs.route'
import { Route as HomeRunsRunbarcodeSamplesheetIndexImport } from './routes/_home.runs.$run_barcode.samplesheet.index'
import { Route as HomeRunsRunbarcodeIndexqcIndexImport } from './routes/_home.runs.$run_barcode.indexqc.index'
import { Route as AuthenticatedHomeAdminVendorsIndexImport } from './routes/_authenticated._home.admin.vendors.index'
import { Route as AuthenticatedHomeAdminRunSettingsIndexImport } from './routes/_authenticated._home.admin.run-settings.index'
import { Route as AuthenticatedHomeAdminProjectSettingsIndexImport } from './routes/_authenticated._home.admin.project-settings.index'
import { Route as AuthenticatedHomeAdminJobsIndexImport } from './routes/_authenticated._home.admin.jobs.index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const UserRouteRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const HomeRouteRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)

const HomeRunsRouteRoute = HomeRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => HomeRouteRoute,
} as any)

const HomeProjectsRouteRoute = HomeProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => HomeRouteRoute,
} as any)

const HomeJobsRouteRoute = HomeJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => HomeRouteRoute,
} as any)

const AuthenticatedHomeRouteRoute = AuthenticatedHomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const UserRegisterIndexRoute = UserRegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserPasswordResetIndexRoute = UserPasswordResetIndexImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserLoginIndexRoute = UserLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => UserRouteRoute,
} as any)

const HomeRunsIndexRoute = HomeRunsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRunsRouteRoute,
} as any)

const HomeProjectsIndexRoute = HomeProjectsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeProjectsRouteRoute,
} as any)

const HomeJobsIndexRoute = HomeJobsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeJobsRouteRoute,
} as any)

const HomeRunsRunbarcodeRouteRoute = HomeRunsRunbarcodeRouteImport.update({
  id: '/$run_barcode',
  path: '/$run_barcode',
  getParentRoute: () => HomeRunsRouteRoute,
} as any)

const HomeProjectsProjectidRouteRoute = HomeProjectsProjectidRouteImport.update(
  {
    id: '/$project_id',
    path: '/$project_id',
    getParentRoute: () => HomeProjectsRouteRoute,
  } as any,
)

const HomeJobsJobidRouteRoute = HomeJobsJobidRouteImport.update({
  id: '/$job_id',
  path: '/$job_id',
  getParentRoute: () => HomeJobsRouteRoute,
} as any)

const AuthenticatedHomeProfileRouteRoute =
  AuthenticatedHomeProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedHomeRouteRoute,
  } as any)

const AuthenticatedHomeAdminRouteRoute =
  AuthenticatedHomeAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedHomeRouteRoute,
  } as any)

const HomeRunsRunbarcodeIndexRoute = HomeRunsRunbarcodeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRunsRunbarcodeRouteRoute,
} as any)

const HomeProjectsProjectidIndexRoute = HomeProjectsProjectidIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => HomeProjectsProjectidRouteRoute,
  } as any,
)

const HomeJobsJobidIndexRoute = HomeJobsJobidIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeJobsJobidRouteRoute,
} as any)

const AuthenticatedHomeProfileIndexRoute =
  AuthenticatedHomeProfileIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeProfileRouteRoute,
  } as any)

const AuthenticatedHomeAdminIndexRoute =
  AuthenticatedHomeAdminIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeAdminRouteRoute,
  } as any)

const HomeRunsRunbarcodeSamplesheetRouteRoute =
  HomeRunsRunbarcodeSamplesheetRouteImport.update({
    id: '/samplesheet',
    path: '/samplesheet',
    getParentRoute: () => HomeRunsRunbarcodeRouteRoute,
  } as any)

const HomeRunsRunbarcodeIndexqcRouteRoute =
  HomeRunsRunbarcodeIndexqcRouteImport.update({
    id: '/indexqc',
    path: '/indexqc',
    getParentRoute: () => HomeRunsRunbarcodeRouteRoute,
  } as any)

const AuthenticatedHomeAdminVendorsRouteRoute =
  AuthenticatedHomeAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedHomeAdminRouteRoute,
  } as any)

const AuthenticatedHomeAdminRunSettingsRouteRoute =
  AuthenticatedHomeAdminRunSettingsRouteImport.update({
    id: '/run-settings',
    path: '/run-settings',
    getParentRoute: () => AuthenticatedHomeAdminRouteRoute,
  } as any)

const AuthenticatedHomeAdminProjectSettingsRouteRoute =
  AuthenticatedHomeAdminProjectSettingsRouteImport.update({
    id: '/project-settings',
    path: '/project-settings',
    getParentRoute: () => AuthenticatedHomeAdminRouteRoute,
  } as any)

const AuthenticatedHomeAdminJobsRouteRoute =
  AuthenticatedHomeAdminJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedHomeAdminRouteRoute,
  } as any)

const HomeRunsRunbarcodeSamplesheetIndexRoute =
  HomeRunsRunbarcodeSamplesheetIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HomeRunsRunbarcodeSamplesheetRouteRoute,
  } as any)

const HomeRunsRunbarcodeIndexqcIndexRoute =
  HomeRunsRunbarcodeIndexqcIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HomeRunsRunbarcodeIndexqcRouteRoute,
  } as any)

const AuthenticatedHomeAdminVendorsIndexRoute =
  AuthenticatedHomeAdminVendorsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeAdminVendorsRouteRoute,
  } as any)

const AuthenticatedHomeAdminRunSettingsIndexRoute =
  AuthenticatedHomeAdminRunSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeAdminRunSettingsRouteRoute,
  } as any)

const AuthenticatedHomeAdminProjectSettingsIndexRoute =
  AuthenticatedHomeAdminProjectSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeAdminProjectSettingsRouteRoute,
  } as any)

const AuthenticatedHomeAdminJobsIndexRoute =
  AuthenticatedHomeAdminJobsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHomeAdminJobsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRoute
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_home': {
      id: '/_authenticated/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_home/jobs': {
      id: '/_home/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof HomeJobsRouteImport
      parentRoute: typeof HomeRouteImport
    }
    '/_home/projects': {
      id: '/_home/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof HomeProjectsRouteImport
      parentRoute: typeof HomeRouteImport
    }
    '/_home/runs': {
      id: '/_home/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof HomeRunsRouteImport
      parentRoute: typeof HomeRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof HomeRouteImport
    }
    '/_authenticated/_home/admin': {
      id: '/_authenticated/_home/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedHomeAdminRouteImport
      parentRoute: typeof AuthenticatedHomeRouteImport
    }
    '/_authenticated/_home/profile': {
      id: '/_authenticated/_home/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedHomeProfileRouteImport
      parentRoute: typeof AuthenticatedHomeRouteImport
    }
    '/_home/jobs/$job_id': {
      id: '/_home/jobs/$job_id'
      path: '/$job_id'
      fullPath: '/jobs/$job_id'
      preLoaderRoute: typeof HomeJobsJobidRouteImport
      parentRoute: typeof HomeJobsRouteImport
    }
    '/_home/projects/$project_id': {
      id: '/_home/projects/$project_id'
      path: '/$project_id'
      fullPath: '/projects/$project_id'
      preLoaderRoute: typeof HomeProjectsProjectidRouteImport
      parentRoute: typeof HomeProjectsRouteImport
    }
    '/_home/runs/$run_barcode': {
      id: '/_home/runs/$run_barcode'
      path: '/$run_barcode'
      fullPath: '/runs/$run_barcode'
      preLoaderRoute: typeof HomeRunsRunbarcodeRouteImport
      parentRoute: typeof HomeRunsRouteImport
    }
    '/_home/jobs/': {
      id: '/_home/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof HomeJobsIndexImport
      parentRoute: typeof HomeJobsRouteImport
    }
    '/_home/projects/': {
      id: '/_home/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof HomeProjectsIndexImport
      parentRoute: typeof HomeProjectsRouteImport
    }
    '/_home/runs/': {
      id: '/_home/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof HomeRunsIndexImport
      parentRoute: typeof HomeRunsRouteImport
    }
    '/_user/login/': {
      id: '/_user/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UserLoginIndexImport
      parentRoute: typeof UserRouteImport
    }
    '/_user/password-reset/': {
      id: '/_user/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof UserPasswordResetIndexImport
      parentRoute: typeof UserRouteImport
    }
    '/_user/register/': {
      id: '/_user/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UserRegisterIndexImport
      parentRoute: typeof UserRouteImport
    }
    '/_authenticated/_home/admin/jobs': {
      id: '/_authenticated/_home/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedHomeAdminJobsRouteImport
      parentRoute: typeof AuthenticatedHomeAdminRouteImport
    }
    '/_authenticated/_home/admin/project-settings': {
      id: '/_authenticated/_home/admin/project-settings'
      path: '/project-settings'
      fullPath: '/admin/project-settings'
      preLoaderRoute: typeof AuthenticatedHomeAdminProjectSettingsRouteImport
      parentRoute: typeof AuthenticatedHomeAdminRouteImport
    }
    '/_authenticated/_home/admin/run-settings': {
      id: '/_authenticated/_home/admin/run-settings'
      path: '/run-settings'
      fullPath: '/admin/run-settings'
      preLoaderRoute: typeof AuthenticatedHomeAdminRunSettingsRouteImport
      parentRoute: typeof AuthenticatedHomeAdminRouteImport
    }
    '/_authenticated/_home/admin/vendors': {
      id: '/_authenticated/_home/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedHomeAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedHomeAdminRouteImport
    }
    '/_home/runs/$run_barcode/indexqc': {
      id: '/_home/runs/$run_barcode/indexqc'
      path: '/indexqc'
      fullPath: '/runs/$run_barcode/indexqc'
      preLoaderRoute: typeof HomeRunsRunbarcodeIndexqcRouteImport
      parentRoute: typeof HomeRunsRunbarcodeRouteImport
    }
    '/_home/runs/$run_barcode/samplesheet': {
      id: '/_home/runs/$run_barcode/samplesheet'
      path: '/samplesheet'
      fullPath: '/runs/$run_barcode/samplesheet'
      preLoaderRoute: typeof HomeRunsRunbarcodeSamplesheetRouteImport
      parentRoute: typeof HomeRunsRunbarcodeRouteImport
    }
    '/_authenticated/_home/admin/': {
      id: '/_authenticated/_home/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedHomeAdminIndexImport
      parentRoute: typeof AuthenticatedHomeAdminRouteImport
    }
    '/_authenticated/_home/profile/': {
      id: '/_authenticated/_home/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedHomeProfileIndexImport
      parentRoute: typeof AuthenticatedHomeProfileRouteImport
    }
    '/_home/jobs/$job_id/': {
      id: '/_home/jobs/$job_id/'
      path: '/'
      fullPath: '/jobs/$job_id/'
      preLoaderRoute: typeof HomeJobsJobidIndexImport
      parentRoute: typeof HomeJobsJobidRouteImport
    }
    '/_home/projects/$project_id/': {
      id: '/_home/projects/$project_id/'
      path: '/'
      fullPath: '/projects/$project_id/'
      preLoaderRoute: typeof HomeProjectsProjectidIndexImport
      parentRoute: typeof HomeProjectsProjectidRouteImport
    }
    '/_home/runs/$run_barcode/': {
      id: '/_home/runs/$run_barcode/'
      path: '/'
      fullPath: '/runs/$run_barcode/'
      preLoaderRoute: typeof HomeRunsRunbarcodeIndexImport
      parentRoute: typeof HomeRunsRunbarcodeRouteImport
    }
    '/_authenticated/_home/admin/jobs/': {
      id: '/_authenticated/_home/admin/jobs/'
      path: '/'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthenticatedHomeAdminJobsIndexImport
      parentRoute: typeof AuthenticatedHomeAdminJobsRouteImport
    }
    '/_authenticated/_home/admin/project-settings/': {
      id: '/_authenticated/_home/admin/project-settings/'
      path: '/'
      fullPath: '/admin/project-settings/'
      preLoaderRoute: typeof AuthenticatedHomeAdminProjectSettingsIndexImport
      parentRoute: typeof AuthenticatedHomeAdminProjectSettingsRouteImport
    }
    '/_authenticated/_home/admin/run-settings/': {
      id: '/_authenticated/_home/admin/run-settings/'
      path: '/'
      fullPath: '/admin/run-settings/'
      preLoaderRoute: typeof AuthenticatedHomeAdminRunSettingsIndexImport
      parentRoute: typeof AuthenticatedHomeAdminRunSettingsRouteImport
    }
    '/_authenticated/_home/admin/vendors/': {
      id: '/_authenticated/_home/admin/vendors/'
      path: '/'
      fullPath: '/admin/vendors/'
      preLoaderRoute: typeof AuthenticatedHomeAdminVendorsIndexImport
      parentRoute: typeof AuthenticatedHomeAdminVendorsRouteImport
    }
    '/_home/runs/$run_barcode/indexqc/': {
      id: '/_home/runs/$run_barcode/indexqc/'
      path: '/'
      fullPath: '/runs/$run_barcode/indexqc/'
      preLoaderRoute: typeof HomeRunsRunbarcodeIndexqcIndexImport
      parentRoute: typeof HomeRunsRunbarcodeIndexqcRouteImport
    }
    '/_home/runs/$run_barcode/samplesheet/': {
      id: '/_home/runs/$run_barcode/samplesheet/'
      path: '/'
      fullPath: '/runs/$run_barcode/samplesheet/'
      preLoaderRoute: typeof HomeRunsRunbarcodeSamplesheetIndexImport
      parentRoute: typeof HomeRunsRunbarcodeSamplesheetRouteImport
    }
  }
}

// Create and export the route tree

interface HomeJobsJobidRouteRouteChildren {
  HomeJobsJobidIndexRoute: typeof HomeJobsJobidIndexRoute
}

const HomeJobsJobidRouteRouteChildren: HomeJobsJobidRouteRouteChildren = {
  HomeJobsJobidIndexRoute: HomeJobsJobidIndexRoute,
}

const HomeJobsJobidRouteRouteWithChildren =
  HomeJobsJobidRouteRoute._addFileChildren(HomeJobsJobidRouteRouteChildren)

interface HomeJobsRouteRouteChildren {
  HomeJobsJobidRouteRoute: typeof HomeJobsJobidRouteRouteWithChildren
  HomeJobsIndexRoute: typeof HomeJobsIndexRoute
}

const HomeJobsRouteRouteChildren: HomeJobsRouteRouteChildren = {
  HomeJobsJobidRouteRoute: HomeJobsJobidRouteRouteWithChildren,
  HomeJobsIndexRoute: HomeJobsIndexRoute,
}

const HomeJobsRouteRouteWithChildren = HomeJobsRouteRoute._addFileChildren(
  HomeJobsRouteRouteChildren,
)

interface HomeProjectsProjectidRouteRouteChildren {
  HomeProjectsProjectidIndexRoute: typeof HomeProjectsProjectidIndexRoute
}

const HomeProjectsProjectidRouteRouteChildren: HomeProjectsProjectidRouteRouteChildren =
  {
    HomeProjectsProjectidIndexRoute: HomeProjectsProjectidIndexRoute,
  }

const HomeProjectsProjectidRouteRouteWithChildren =
  HomeProjectsProjectidRouteRoute._addFileChildren(
    HomeProjectsProjectidRouteRouteChildren,
  )

interface HomeProjectsRouteRouteChildren {
  HomeProjectsProjectidRouteRoute: typeof HomeProjectsProjectidRouteRouteWithChildren
  HomeProjectsIndexRoute: typeof HomeProjectsIndexRoute
}

const HomeProjectsRouteRouteChildren: HomeProjectsRouteRouteChildren = {
  HomeProjectsProjectidRouteRoute: HomeProjectsProjectidRouteRouteWithChildren,
  HomeProjectsIndexRoute: HomeProjectsIndexRoute,
}

const HomeProjectsRouteRouteWithChildren =
  HomeProjectsRouteRoute._addFileChildren(HomeProjectsRouteRouteChildren)

interface HomeRunsRunbarcodeIndexqcRouteRouteChildren {
  HomeRunsRunbarcodeIndexqcIndexRoute: typeof HomeRunsRunbarcodeIndexqcIndexRoute
}

const HomeRunsRunbarcodeIndexqcRouteRouteChildren: HomeRunsRunbarcodeIndexqcRouteRouteChildren =
  {
    HomeRunsRunbarcodeIndexqcIndexRoute: HomeRunsRunbarcodeIndexqcIndexRoute,
  }

const HomeRunsRunbarcodeIndexqcRouteRouteWithChildren =
  HomeRunsRunbarcodeIndexqcRouteRoute._addFileChildren(
    HomeRunsRunbarcodeIndexqcRouteRouteChildren,
  )

interface HomeRunsRunbarcodeSamplesheetRouteRouteChildren {
  HomeRunsRunbarcodeSamplesheetIndexRoute: typeof HomeRunsRunbarcodeSamplesheetIndexRoute
}

const HomeRunsRunbarcodeSamplesheetRouteRouteChildren: HomeRunsRunbarcodeSamplesheetRouteRouteChildren =
  {
    HomeRunsRunbarcodeSamplesheetIndexRoute:
      HomeRunsRunbarcodeSamplesheetIndexRoute,
  }

const HomeRunsRunbarcodeSamplesheetRouteRouteWithChildren =
  HomeRunsRunbarcodeSamplesheetRouteRoute._addFileChildren(
    HomeRunsRunbarcodeSamplesheetRouteRouteChildren,
  )

interface HomeRunsRunbarcodeRouteRouteChildren {
  HomeRunsRunbarcodeIndexqcRouteRoute: typeof HomeRunsRunbarcodeIndexqcRouteRouteWithChildren
  HomeRunsRunbarcodeSamplesheetRouteRoute: typeof HomeRunsRunbarcodeSamplesheetRouteRouteWithChildren
  HomeRunsRunbarcodeIndexRoute: typeof HomeRunsRunbarcodeIndexRoute
}

const HomeRunsRunbarcodeRouteRouteChildren: HomeRunsRunbarcodeRouteRouteChildren =
  {
    HomeRunsRunbarcodeIndexqcRouteRoute:
      HomeRunsRunbarcodeIndexqcRouteRouteWithChildren,
    HomeRunsRunbarcodeSamplesheetRouteRoute:
      HomeRunsRunbarcodeSamplesheetRouteRouteWithChildren,
    HomeRunsRunbarcodeIndexRoute: HomeRunsRunbarcodeIndexRoute,
  }

const HomeRunsRunbarcodeRouteRouteWithChildren =
  HomeRunsRunbarcodeRouteRoute._addFileChildren(
    HomeRunsRunbarcodeRouteRouteChildren,
  )

interface HomeRunsRouteRouteChildren {
  HomeRunsRunbarcodeRouteRoute: typeof HomeRunsRunbarcodeRouteRouteWithChildren
  HomeRunsIndexRoute: typeof HomeRunsIndexRoute
}

const HomeRunsRouteRouteChildren: HomeRunsRouteRouteChildren = {
  HomeRunsRunbarcodeRouteRoute: HomeRunsRunbarcodeRouteRouteWithChildren,
  HomeRunsIndexRoute: HomeRunsIndexRoute,
}

const HomeRunsRouteRouteWithChildren = HomeRunsRouteRoute._addFileChildren(
  HomeRunsRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeJobsRouteRoute: typeof HomeJobsRouteRouteWithChildren
  HomeProjectsRouteRoute: typeof HomeProjectsRouteRouteWithChildren
  HomeRunsRouteRoute: typeof HomeRunsRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeJobsRouteRoute: HomeJobsRouteRouteWithChildren,
  HomeProjectsRouteRoute: HomeProjectsRouteRouteWithChildren,
  HomeRunsRouteRoute: HomeRunsRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserLoginIndexRoute: typeof UserLoginIndexRoute
  UserPasswordResetIndexRoute: typeof UserPasswordResetIndexRoute
  UserRegisterIndexRoute: typeof UserRegisterIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserLoginIndexRoute: UserLoginIndexRoute,
  UserPasswordResetIndexRoute: UserPasswordResetIndexRoute,
  UserRegisterIndexRoute: UserRegisterIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AuthenticatedHomeAdminJobsRouteRouteChildren {
  AuthenticatedHomeAdminJobsIndexRoute: typeof AuthenticatedHomeAdminJobsIndexRoute
}

const AuthenticatedHomeAdminJobsRouteRouteChildren: AuthenticatedHomeAdminJobsRouteRouteChildren =
  {
    AuthenticatedHomeAdminJobsIndexRoute: AuthenticatedHomeAdminJobsIndexRoute,
  }

const AuthenticatedHomeAdminJobsRouteRouteWithChildren =
  AuthenticatedHomeAdminJobsRouteRoute._addFileChildren(
    AuthenticatedHomeAdminJobsRouteRouteChildren,
  )

interface AuthenticatedHomeAdminProjectSettingsRouteRouteChildren {
  AuthenticatedHomeAdminProjectSettingsIndexRoute: typeof AuthenticatedHomeAdminProjectSettingsIndexRoute
}

const AuthenticatedHomeAdminProjectSettingsRouteRouteChildren: AuthenticatedHomeAdminProjectSettingsRouteRouteChildren =
  {
    AuthenticatedHomeAdminProjectSettingsIndexRoute:
      AuthenticatedHomeAdminProjectSettingsIndexRoute,
  }

const AuthenticatedHomeAdminProjectSettingsRouteRouteWithChildren =
  AuthenticatedHomeAdminProjectSettingsRouteRoute._addFileChildren(
    AuthenticatedHomeAdminProjectSettingsRouteRouteChildren,
  )

interface AuthenticatedHomeAdminRunSettingsRouteRouteChildren {
  AuthenticatedHomeAdminRunSettingsIndexRoute: typeof AuthenticatedHomeAdminRunSettingsIndexRoute
}

const AuthenticatedHomeAdminRunSettingsRouteRouteChildren: AuthenticatedHomeAdminRunSettingsRouteRouteChildren =
  {
    AuthenticatedHomeAdminRunSettingsIndexRoute:
      AuthenticatedHomeAdminRunSettingsIndexRoute,
  }

const AuthenticatedHomeAdminRunSettingsRouteRouteWithChildren =
  AuthenticatedHomeAdminRunSettingsRouteRoute._addFileChildren(
    AuthenticatedHomeAdminRunSettingsRouteRouteChildren,
  )

interface AuthenticatedHomeAdminVendorsRouteRouteChildren {
  AuthenticatedHomeAdminVendorsIndexRoute: typeof AuthenticatedHomeAdminVendorsIndexRoute
}

const AuthenticatedHomeAdminVendorsRouteRouteChildren: AuthenticatedHomeAdminVendorsRouteRouteChildren =
  {
    AuthenticatedHomeAdminVendorsIndexRoute:
      AuthenticatedHomeAdminVendorsIndexRoute,
  }

const AuthenticatedHomeAdminVendorsRouteRouteWithChildren =
  AuthenticatedHomeAdminVendorsRouteRoute._addFileChildren(
    AuthenticatedHomeAdminVendorsRouteRouteChildren,
  )

interface AuthenticatedHomeAdminRouteRouteChildren {
  AuthenticatedHomeAdminJobsRouteRoute: typeof AuthenticatedHomeAdminJobsRouteRouteWithChildren
  AuthenticatedHomeAdminProjectSettingsRouteRoute: typeof AuthenticatedHomeAdminProjectSettingsRouteRouteWithChildren
  AuthenticatedHomeAdminRunSettingsRouteRoute: typeof AuthenticatedHomeAdminRunSettingsRouteRouteWithChildren
  AuthenticatedHomeAdminVendorsRouteRoute: typeof AuthenticatedHomeAdminVendorsRouteRouteWithChildren
  AuthenticatedHomeAdminIndexRoute: typeof AuthenticatedHomeAdminIndexRoute
}

const AuthenticatedHomeAdminRouteRouteChildren: AuthenticatedHomeAdminRouteRouteChildren =
  {
    AuthenticatedHomeAdminJobsRouteRoute:
      AuthenticatedHomeAdminJobsRouteRouteWithChildren,
    AuthenticatedHomeAdminProjectSettingsRouteRoute:
      AuthenticatedHomeAdminProjectSettingsRouteRouteWithChildren,
    AuthenticatedHomeAdminRunSettingsRouteRoute:
      AuthenticatedHomeAdminRunSettingsRouteRouteWithChildren,
    AuthenticatedHomeAdminVendorsRouteRoute:
      AuthenticatedHomeAdminVendorsRouteRouteWithChildren,
    AuthenticatedHomeAdminIndexRoute: AuthenticatedHomeAdminIndexRoute,
  }

const AuthenticatedHomeAdminRouteRouteWithChildren =
  AuthenticatedHomeAdminRouteRoute._addFileChildren(
    AuthenticatedHomeAdminRouteRouteChildren,
  )

interface AuthenticatedHomeProfileRouteRouteChildren {
  AuthenticatedHomeProfileIndexRoute: typeof AuthenticatedHomeProfileIndexRoute
}

const AuthenticatedHomeProfileRouteRouteChildren: AuthenticatedHomeProfileRouteRouteChildren =
  {
    AuthenticatedHomeProfileIndexRoute: AuthenticatedHomeProfileIndexRoute,
  }

const AuthenticatedHomeProfileRouteRouteWithChildren =
  AuthenticatedHomeProfileRouteRoute._addFileChildren(
    AuthenticatedHomeProfileRouteRouteChildren,
  )

interface AuthenticatedHomeRouteRouteChildren {
  AuthenticatedHomeAdminRouteRoute: typeof AuthenticatedHomeAdminRouteRouteWithChildren
  AuthenticatedHomeProfileRouteRoute: typeof AuthenticatedHomeProfileRouteRouteWithChildren
}

const AuthenticatedHomeRouteRouteChildren: AuthenticatedHomeRouteRouteChildren =
  {
    AuthenticatedHomeAdminRouteRoute:
      AuthenticatedHomeAdminRouteRouteWithChildren,
    AuthenticatedHomeProfileRouteRoute:
      AuthenticatedHomeProfileRouteRouteWithChildren,
  }

const AuthenticatedHomeRouteRouteWithChildren =
  AuthenticatedHomeRouteRoute._addFileChildren(
    AuthenticatedHomeRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRouteRoute: typeof AuthenticatedHomeRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRouteRoute: AuthenticatedHomeRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedHomeRouteRouteWithChildren
  '/jobs': typeof HomeJobsRouteRouteWithChildren
  '/projects': typeof HomeProjectsRouteRouteWithChildren
  '/runs': typeof HomeRunsRouteRouteWithChildren
  '/': typeof HomeIndexRoute
  '/admin': typeof AuthenticatedHomeAdminRouteRouteWithChildren
  '/profile': typeof AuthenticatedHomeProfileRouteRouteWithChildren
  '/jobs/$job_id': typeof HomeJobsJobidRouteRouteWithChildren
  '/projects/$project_id': typeof HomeProjectsProjectidRouteRouteWithChildren
  '/runs/$run_barcode': typeof HomeRunsRunbarcodeRouteRouteWithChildren
  '/jobs/': typeof HomeJobsIndexRoute
  '/projects/': typeof HomeProjectsIndexRoute
  '/runs/': typeof HomeRunsIndexRoute
  '/login': typeof UserLoginIndexRoute
  '/password-reset': typeof UserPasswordResetIndexRoute
  '/register': typeof UserRegisterIndexRoute
  '/admin/jobs': typeof AuthenticatedHomeAdminJobsRouteRouteWithChildren
  '/admin/project-settings': typeof AuthenticatedHomeAdminProjectSettingsRouteRouteWithChildren
  '/admin/run-settings': typeof AuthenticatedHomeAdminRunSettingsRouteRouteWithChildren
  '/admin/vendors': typeof AuthenticatedHomeAdminVendorsRouteRouteWithChildren
  '/runs/$run_barcode/indexqc': typeof HomeRunsRunbarcodeIndexqcRouteRouteWithChildren
  '/runs/$run_barcode/samplesheet': typeof HomeRunsRunbarcodeSamplesheetRouteRouteWithChildren
  '/admin/': typeof AuthenticatedHomeAdminIndexRoute
  '/profile/': typeof AuthenticatedHomeProfileIndexRoute
  '/jobs/$job_id/': typeof HomeJobsJobidIndexRoute
  '/projects/$project_id/': typeof HomeProjectsProjectidIndexRoute
  '/runs/$run_barcode/': typeof HomeRunsRunbarcodeIndexRoute
  '/admin/jobs/': typeof AuthenticatedHomeAdminJobsIndexRoute
  '/admin/project-settings/': typeof AuthenticatedHomeAdminProjectSettingsIndexRoute
  '/admin/run-settings/': typeof AuthenticatedHomeAdminRunSettingsIndexRoute
  '/admin/vendors/': typeof AuthenticatedHomeAdminVendorsIndexRoute
  '/runs/$run_barcode/indexqc/': typeof HomeRunsRunbarcodeIndexqcIndexRoute
  '/runs/$run_barcode/samplesheet/': typeof HomeRunsRunbarcodeSamplesheetIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedHomeRouteRouteWithChildren
  '/': typeof HomeIndexRoute
  '/jobs': typeof HomeJobsIndexRoute
  '/projects': typeof HomeProjectsIndexRoute
  '/runs': typeof HomeRunsIndexRoute
  '/login': typeof UserLoginIndexRoute
  '/password-reset': typeof UserPasswordResetIndexRoute
  '/register': typeof UserRegisterIndexRoute
  '/admin': typeof AuthenticatedHomeAdminIndexRoute
  '/profile': typeof AuthenticatedHomeProfileIndexRoute
  '/jobs/$job_id': typeof HomeJobsJobidIndexRoute
  '/projects/$project_id': typeof HomeProjectsProjectidIndexRoute
  '/runs/$run_barcode': typeof HomeRunsRunbarcodeIndexRoute
  '/admin/jobs': typeof AuthenticatedHomeAdminJobsIndexRoute
  '/admin/project-settings': typeof AuthenticatedHomeAdminProjectSettingsIndexRoute
  '/admin/run-settings': typeof AuthenticatedHomeAdminRunSettingsIndexRoute
  '/admin/vendors': typeof AuthenticatedHomeAdminVendorsIndexRoute
  '/runs/$run_barcode/indexqc': typeof HomeRunsRunbarcodeIndexqcIndexRoute
  '/runs/$run_barcode/samplesheet': typeof HomeRunsRunbarcodeSamplesheetIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_home': typeof HomeRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_home': typeof AuthenticatedHomeRouteRouteWithChildren
  '/_home/jobs': typeof HomeJobsRouteRouteWithChildren
  '/_home/projects': typeof HomeProjectsRouteRouteWithChildren
  '/_home/runs': typeof HomeRunsRouteRouteWithChildren
  '/_home/': typeof HomeIndexRoute
  '/_authenticated/_home/admin': typeof AuthenticatedHomeAdminRouteRouteWithChildren
  '/_authenticated/_home/profile': typeof AuthenticatedHomeProfileRouteRouteWithChildren
  '/_home/jobs/$job_id': typeof HomeJobsJobidRouteRouteWithChildren
  '/_home/projects/$project_id': typeof HomeProjectsProjectidRouteRouteWithChildren
  '/_home/runs/$run_barcode': typeof HomeRunsRunbarcodeRouteRouteWithChildren
  '/_home/jobs/': typeof HomeJobsIndexRoute
  '/_home/projects/': typeof HomeProjectsIndexRoute
  '/_home/runs/': typeof HomeRunsIndexRoute
  '/_user/login/': typeof UserLoginIndexRoute
  '/_user/password-reset/': typeof UserPasswordResetIndexRoute
  '/_user/register/': typeof UserRegisterIndexRoute
  '/_authenticated/_home/admin/jobs': typeof AuthenticatedHomeAdminJobsRouteRouteWithChildren
  '/_authenticated/_home/admin/project-settings': typeof AuthenticatedHomeAdminProjectSettingsRouteRouteWithChildren
  '/_authenticated/_home/admin/run-settings': typeof AuthenticatedHomeAdminRunSettingsRouteRouteWithChildren
  '/_authenticated/_home/admin/vendors': typeof AuthenticatedHomeAdminVendorsRouteRouteWithChildren
  '/_home/runs/$run_barcode/indexqc': typeof HomeRunsRunbarcodeIndexqcRouteRouteWithChildren
  '/_home/runs/$run_barcode/samplesheet': typeof HomeRunsRunbarcodeSamplesheetRouteRouteWithChildren
  '/_authenticated/_home/admin/': typeof AuthenticatedHomeAdminIndexRoute
  '/_authenticated/_home/profile/': typeof AuthenticatedHomeProfileIndexRoute
  '/_home/jobs/$job_id/': typeof HomeJobsJobidIndexRoute
  '/_home/projects/$project_id/': typeof HomeProjectsProjectidIndexRoute
  '/_home/runs/$run_barcode/': typeof HomeRunsRunbarcodeIndexRoute
  '/_authenticated/_home/admin/jobs/': typeof AuthenticatedHomeAdminJobsIndexRoute
  '/_authenticated/_home/admin/project-settings/': typeof AuthenticatedHomeAdminProjectSettingsIndexRoute
  '/_authenticated/_home/admin/run-settings/': typeof AuthenticatedHomeAdminRunSettingsIndexRoute
  '/_authenticated/_home/admin/vendors/': typeof AuthenticatedHomeAdminVendorsIndexRoute
  '/_home/runs/$run_barcode/indexqc/': typeof HomeRunsRunbarcodeIndexqcIndexRoute
  '/_home/runs/$run_barcode/samplesheet/': typeof HomeRunsRunbarcodeSamplesheetIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/jobs'
    | '/projects'
    | '/runs'
    | '/'
    | '/admin'
    | '/profile'
    | '/jobs/$job_id'
    | '/projects/$project_id'
    | '/runs/$run_barcode'
    | '/jobs/'
    | '/projects/'
    | '/runs/'
    | '/login'
    | '/password-reset'
    | '/register'
    | '/admin/jobs'
    | '/admin/project-settings'
    | '/admin/run-settings'
    | '/admin/vendors'
    | '/runs/$run_barcode/indexqc'
    | '/runs/$run_barcode/samplesheet'
    | '/admin/'
    | '/profile/'
    | '/jobs/$job_id/'
    | '/projects/$project_id/'
    | '/runs/$run_barcode/'
    | '/admin/jobs/'
    | '/admin/project-settings/'
    | '/admin/run-settings/'
    | '/admin/vendors/'
    | '/runs/$run_barcode/indexqc/'
    | '/runs/$run_barcode/samplesheet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/jobs'
    | '/projects'
    | '/runs'
    | '/login'
    | '/password-reset'
    | '/register'
    | '/admin'
    | '/profile'
    | '/jobs/$job_id'
    | '/projects/$project_id'
    | '/runs/$run_barcode'
    | '/admin/jobs'
    | '/admin/project-settings'
    | '/admin/run-settings'
    | '/admin/vendors'
    | '/runs/$run_barcode/indexqc'
    | '/runs/$run_barcode/samplesheet'
  id:
    | '__root__'
    | '/_home'
    | '/_user'
    | '/_authenticated'
    | '/_authenticated/_home'
    | '/_home/jobs'
    | '/_home/projects'
    | '/_home/runs'
    | '/_home/'
    | '/_authenticated/_home/admin'
    | '/_authenticated/_home/profile'
    | '/_home/jobs/$job_id'
    | '/_home/projects/$project_id'
    | '/_home/runs/$run_barcode'
    | '/_home/jobs/'
    | '/_home/projects/'
    | '/_home/runs/'
    | '/_user/login/'
    | '/_user/password-reset/'
    | '/_user/register/'
    | '/_authenticated/_home/admin/jobs'
    | '/_authenticated/_home/admin/project-settings'
    | '/_authenticated/_home/admin/run-settings'
    | '/_authenticated/_home/admin/vendors'
    | '/_home/runs/$run_barcode/indexqc'
    | '/_home/runs/$run_barcode/samplesheet'
    | '/_authenticated/_home/admin/'
    | '/_authenticated/_home/profile/'
    | '/_home/jobs/$job_id/'
    | '/_home/projects/$project_id/'
    | '/_home/runs/$run_barcode/'
    | '/_authenticated/_home/admin/jobs/'
    | '/_authenticated/_home/admin/project-settings/'
    | '/_authenticated/_home/admin/run-settings/'
    | '/_authenticated/_home/admin/vendors/'
    | '/_home/runs/$run_barcode/indexqc/'
    | '/_home/runs/$run_barcode/samplesheet/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_home",
        "/_user",
        "/_authenticated"
      ]
    },
    "/_home": {
      "filePath": "_home.route.tsx",
      "children": [
        "/_home/jobs",
        "/_home/projects",
        "/_home/runs",
        "/_home/"
      ]
    },
    "/_user": {
      "filePath": "_user.route.tsx",
      "children": [
        "/_user/login/",
        "/_user/password-reset/",
        "/_user/register/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_home"
      ]
    },
    "/_authenticated/_home": {
      "filePath": "_authenticated._home.route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_home/admin",
        "/_authenticated/_home/profile"
      ]
    },
    "/_home/jobs": {
      "filePath": "_home.jobs.route.tsx",
      "parent": "/_home",
      "children": [
        "/_home/jobs/$job_id",
        "/_home/jobs/"
      ]
    },
    "/_home/projects": {
      "filePath": "_home.projects.route.tsx",
      "parent": "/_home",
      "children": [
        "/_home/projects/$project_id",
        "/_home/projects/"
      ]
    },
    "/_home/runs": {
      "filePath": "_home.runs.route.tsx",
      "parent": "/_home",
      "children": [
        "/_home/runs/$run_barcode",
        "/_home/runs/"
      ]
    },
    "/_home/": {
      "filePath": "_home.index.tsx",
      "parent": "/_home"
    },
    "/_authenticated/_home/admin": {
      "filePath": "_authenticated._home.admin.route.tsx",
      "parent": "/_authenticated/_home",
      "children": [
        "/_authenticated/_home/admin/jobs",
        "/_authenticated/_home/admin/project-settings",
        "/_authenticated/_home/admin/run-settings",
        "/_authenticated/_home/admin/vendors",
        "/_authenticated/_home/admin/"
      ]
    },
    "/_authenticated/_home/profile": {
      "filePath": "_authenticated._home.profile.route.tsx",
      "parent": "/_authenticated/_home",
      "children": [
        "/_authenticated/_home/profile/"
      ]
    },
    "/_home/jobs/$job_id": {
      "filePath": "_home.jobs.$job_id.route.tsx",
      "parent": "/_home/jobs",
      "children": [
        "/_home/jobs/$job_id/"
      ]
    },
    "/_home/projects/$project_id": {
      "filePath": "_home.projects.$project_id.route.tsx",
      "parent": "/_home/projects",
      "children": [
        "/_home/projects/$project_id/"
      ]
    },
    "/_home/runs/$run_barcode": {
      "filePath": "_home.runs.$run_barcode.route.tsx",
      "parent": "/_home/runs",
      "children": [
        "/_home/runs/$run_barcode/indexqc",
        "/_home/runs/$run_barcode/samplesheet",
        "/_home/runs/$run_barcode/"
      ]
    },
    "/_home/jobs/": {
      "filePath": "_home.jobs.index.tsx",
      "parent": "/_home/jobs"
    },
    "/_home/projects/": {
      "filePath": "_home.projects.index.tsx",
      "parent": "/_home/projects"
    },
    "/_home/runs/": {
      "filePath": "_home.runs.index.tsx",
      "parent": "/_home/runs"
    },
    "/_user/login/": {
      "filePath": "_user.login.index.tsx",
      "parent": "/_user"
    },
    "/_user/password-reset/": {
      "filePath": "_user.password-reset.index.tsx",
      "parent": "/_user"
    },
    "/_user/register/": {
      "filePath": "_user.register.index.tsx",
      "parent": "/_user"
    },
    "/_authenticated/_home/admin/jobs": {
      "filePath": "_authenticated._home.admin.jobs.route.tsx",
      "parent": "/_authenticated/_home/admin",
      "children": [
        "/_authenticated/_home/admin/jobs/"
      ]
    },
    "/_authenticated/_home/admin/project-settings": {
      "filePath": "_authenticated._home.admin.project-settings.route.tsx",
      "parent": "/_authenticated/_home/admin",
      "children": [
        "/_authenticated/_home/admin/project-settings/"
      ]
    },
    "/_authenticated/_home/admin/run-settings": {
      "filePath": "_authenticated._home.admin.run-settings.route.tsx",
      "parent": "/_authenticated/_home/admin",
      "children": [
        "/_authenticated/_home/admin/run-settings/"
      ]
    },
    "/_authenticated/_home/admin/vendors": {
      "filePath": "_authenticated._home.admin.vendors.route.tsx",
      "parent": "/_authenticated/_home/admin",
      "children": [
        "/_authenticated/_home/admin/vendors/"
      ]
    },
    "/_home/runs/$run_barcode/indexqc": {
      "filePath": "_home.runs.$run_barcode.indexqc.route.tsx",
      "parent": "/_home/runs/$run_barcode",
      "children": [
        "/_home/runs/$run_barcode/indexqc/"
      ]
    },
    "/_home/runs/$run_barcode/samplesheet": {
      "filePath": "_home.runs.$run_barcode.samplesheet.route.tsx",
      "parent": "/_home/runs/$run_barcode",
      "children": [
        "/_home/runs/$run_barcode/samplesheet/"
      ]
    },
    "/_authenticated/_home/admin/": {
      "filePath": "_authenticated._home.admin.index.tsx",
      "parent": "/_authenticated/_home/admin"
    },
    "/_authenticated/_home/profile/": {
      "filePath": "_authenticated._home.profile.index.tsx",
      "parent": "/_authenticated/_home/profile"
    },
    "/_home/jobs/$job_id/": {
      "filePath": "_home.jobs.$job_id.index.tsx",
      "parent": "/_home/jobs/$job_id"
    },
    "/_home/projects/$project_id/": {
      "filePath": "_home.projects.$project_id.index.tsx",
      "parent": "/_home/projects/$project_id"
    },
    "/_home/runs/$run_barcode/": {
      "filePath": "_home.runs.$run_barcode.index.tsx",
      "parent": "/_home/runs/$run_barcode"
    },
    "/_authenticated/_home/admin/jobs/": {
      "filePath": "_authenticated._home.admin.jobs.index.tsx",
      "parent": "/_authenticated/_home/admin/jobs"
    },
    "/_authenticated/_home/admin/project-settings/": {
      "filePath": "_authenticated._home.admin.project-settings.index.tsx",
      "parent": "/_authenticated/_home/admin/project-settings"
    },
    "/_authenticated/_home/admin/run-settings/": {
      "filePath": "_authenticated._home.admin.run-settings.index.tsx",
      "parent": "/_authenticated/_home/admin/run-settings"
    },
    "/_authenticated/_home/admin/vendors/": {
      "filePath": "_authenticated._home.admin.vendors.index.tsx",
      "parent": "/_authenticated/_home/admin/vendors"
    },
    "/_home/runs/$run_barcode/indexqc/": {
      "filePath": "_home.runs.$run_barcode.indexqc.index.tsx",
      "parent": "/_home/runs/$run_barcode/indexqc"
    },
    "/_home/runs/$run_barcode/samplesheet/": {
      "filePath": "_home.runs.$run_barcode.samplesheet.index.tsx",
      "parent": "/_home/runs/$run_barcode/samplesheet"
    }
  }
}
ROUTE_MANIFEST_END */
