// This file is auto-generated by @hey-api/openapi-ts

import {
  
  
  
  formDataBodySerializer
} from './client'
import { client as _heyApiClient } from './client.gen'
import type {Client, Options as ClientOptions, TDataShape} from './client';
import type {
  AddRunData,
  AddRunErrors,
  AddRunResponses,
  AddSampleToProjectData,
  AddSampleToProjectErrors,
  AddSampleToProjectResponses,
  AddVendorData,
  AddVendorErrors,
  AddVendorResponses,
  CreateProjectData,
  CreateProjectErrors,
  CreateProjectResponses,
  DeleteVendorData,
  DeleteVendorErrors,
  DeleteVendorResponses,
  DemultiplexRunData,
  DemultiplexRunErrors,
  DemultiplexRunResponses,
  GetLatestManifestData,
  GetLatestManifestErrors,
  GetLatestManifestResponses,
  GetMultiplexWorkflowsData,
  GetMultiplexWorkflowsResponses,
  GetProjectByProjectIdData,
  GetProjectByProjectIdErrors,
  GetProjectByProjectIdResponses,
  GetProjectsData,
  GetProjectsErrors,
  GetProjectsResponses,
  GetRunData,
  GetRunErrors,
  GetRunMetricsData,
  GetRunMetricsErrors,
  GetRunMetricsResponses,
  GetRunResponses,
  GetRunSamplesheetData,
  GetRunSamplesheetErrors,
  GetRunSamplesheetResponses,
  GetRunsData,
  GetRunsErrors,
  GetRunsResponses,
  GetSamplesData,
  GetSamplesErrors,
  GetSamplesResponses,
  GetToolConfigData,
  GetToolConfigErrors,
  GetToolConfigResponses,
  GetVendorData,
  GetVendorErrors,
  GetVendorResponses,
  GetVendorsData,
  GetVendorsErrors,
  GetVendorsResponses,
  HealthCheckData,
  HealthCheckResponses,
  ListAvailableToolsData,
  ListAvailableToolsResponses,
  ListFilesData,
  ListFilesErrors,
  ListFilesResponses,
  PostRunSamplesheetData,
  PostRunSamplesheetErrors,
  PostRunSamplesheetResponses,
  ReindexProjectsData,
  ReindexProjectsResponses,
  ReindexRunsData,
  ReindexRunsResponses,
  ReindexSamplesData,
  ReindexSamplesResponses,
  RootData,
  RootResponses,
  SearchData,
  SearchErrors,
  SearchProjectsData,
  SearchProjectsErrors,
  SearchProjectsResponses,
  SearchResponses,
  SearchRunsData,
  SearchRunsErrors,
  SearchRunsResponses,
  UpdateRunData,
  UpdateRunErrors,
  UpdateRunResponses,
  UpdateSampleInProjectData,
  UpdateSampleInProjectErrors,
  UpdateSampleInProjectResponses,
  UpdateVendorData,
  UpdateVendorErrors,
  UpdateVendorResponses,
  UploadManifestData,
  UploadManifestErrors,
  UploadManifestResponses,
  ValidateManifestData,
  ValidateManifestErrors,
  ValidateManifestResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Root
 */
export const root = <ThrowOnError extends boolean = false>(
  options?: Options<RootData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    RootResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/',
    ...options,
  })
}

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    HealthCheckResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/health',
    ...options,
  })
}

/**
 * List Files
 * Browse files and folders at the specified URI.
 *
 * For S3:
 * - Full s3:// URI is required
 * - No navigation outside the initial uri is allowed
 */
export const listFiles = <ThrowOnError extends boolean = false>(
  options: Options<ListFilesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListFilesResponses,
    ListFilesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/files/list',
    ...options,
  })
}

/**
 * Get Projects
 * Returns a paginated list of projects.
 */
export const getProjects = <ThrowOnError extends boolean = false>(
  options?: Options<GetProjectsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetProjectsResponses,
    GetProjectsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects',
    ...options,
  })
}

/**
 * Create Project
 * Create a new project with optional attributes.
 */
export const createProject = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateProjectResponses,
    CreateProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Search Projects
 * Search projects by project_id or name.
 */
export const searchProjects = <ThrowOnError extends boolean = false>(
  options: Options<SearchProjectsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SearchProjectsResponses,
    SearchProjectsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/search',
    ...options,
  })
}

/**
 * Reindex Projects
 * Reindex projects in database with OpenSearch
 */
export const reindexProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ReindexProjectsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    ReindexProjectsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/search',
    ...options,
  })
}

/**
 * Get Project By Project Id
 * Returns a single project by its project_id.
 * Note: This is different from its internal "id".
 */
export const getProjectByProjectId = <ThrowOnError extends boolean = false>(
  options: Options<GetProjectByProjectIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetProjectByProjectIdResponses,
    GetProjectByProjectIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/{project_id}',
    ...options,
  })
}

/**
 * Get Samples
 * Returns a paginated list of samples.
 */
export const getSamples = <ThrowOnError extends boolean = false>(
  options: Options<GetSamplesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetSamplesResponses,
    GetSamplesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/{project_id}/samples',
    ...options,
  })
}

/**
 * Add Sample To Project
 * Create a new sample with optional attributes.
 */
export const addSampleToProject = <ThrowOnError extends boolean = false>(
  options: Options<AddSampleToProjectData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    AddSampleToProjectResponses,
    AddSampleToProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/{project_id}/samples',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Update Sample In Project
 * Update an existing sample in a project.
 */
export const updateSampleInProject = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSampleInProjectData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateSampleInProjectResponses,
    UpdateSampleInProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/projects/{project_id}/samples/{sample_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Runs
 * Retrieve a list of all sequencing runs.
 */
export const getRuns = <ThrowOnError extends boolean = false>(
  options?: Options<GetRunsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetRunsResponses,
    GetRunsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs',
    ...options,
  })
}

/**
 * Add Run
 * Create a new project with optional attributes.
 */
export const addRun = <ThrowOnError extends boolean = false>(
  options: Options<AddRunData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    AddRunResponses,
    AddRunErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Search Runs
 * Search for sequencing runs using OpenSearch.
 */
export const searchRuns = <ThrowOnError extends boolean = false>(
  options: Options<SearchRunsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SearchRunsResponses,
    SearchRunsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs/search',
    ...options,
  })
}

/**
 * Reindex Runs
 * Reindex runs in database with OpenSearch
 */
export const reindexRuns = <ThrowOnError extends boolean = false>(
  options?: Options<ReindexRunsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    ReindexRunsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs/search',
    ...options,
  })
}

/**
 * Get Multiplex Workflows
 * Placeholder endpoint for getting available demultiplex workflows.
 */
export const getMultiplexWorkflows = <ThrowOnError extends boolean = false>(
  options?: Options<GetMultiplexWorkflowsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetMultiplexWorkflowsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs/demultiplex',
    ...options,
  })
}

/**
 * Demultiplex Run
 * Submit a demultiplex job for a specific run.
 */
export const demultiplexRun = <ThrowOnError extends boolean = false>(
  options: Options<DemultiplexRunData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    DemultiplexRunResponses,
    DemultiplexRunErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs/demultiplex',
    ...options,
  })
}

/**
 * Get Run
 * Retrieve a sequencing run.
 */
export const getRun = <ThrowOnError extends boolean = false>(
  options: Options<GetRunData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetRunResponses,
    GetRunErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs/{run_barcode}',
    ...options,
  })
}

/**
 * Update Run
 * Update the status of a specific run.
 * Valid status values are: "In Progress", "Uploading", "Ready", "Resync"
 */
export const updateRun = <ThrowOnError extends boolean = false>(
  options: Options<UpdateRunData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateRunResponses,
    UpdateRunErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs/{run_barcode}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Run Samplesheet
 * Retrieve the sample sheet for a specific run.
 */
export const getRunSamplesheet = <ThrowOnError extends boolean = false>(
  options: Options<GetRunSamplesheetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetRunSamplesheetResponses,
    GetRunSamplesheetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs/{run_barcode}/samplesheet',
    ...options,
  })
}

/**
 * Post Run Samplesheet
 * Upload a samplesheet to a run.
 */
export const postRunSamplesheet = <ThrowOnError extends boolean = false>(
  options: Options<PostRunSamplesheetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostRunSamplesheetResponses,
    PostRunSamplesheetErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/runs/{run_barcode}/samplesheet',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })
}

/**
 * Get Run Metrics
 * Retrieve demultiplexing metrics for a specific run.
 */
export const getRunMetrics = <ThrowOnError extends boolean = false>(
  options: Options<GetRunMetricsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetRunMetricsResponses,
    GetRunMetricsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/runs/{run_barcode}/metrics',
    ...options,
  })
}

/**
 * Reindex Samples
 * Reindex samples in database with OpenSearch
 */
export const reindexSamples = <ThrowOnError extends boolean = false>(
  options?: Options<ReindexSamplesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    ReindexSamplesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/samples/search',
    ...options,
  })
}

/**
 * Search
 * Search across all indices using OpenSearch.
 */
export const search = <ThrowOnError extends boolean = false>(
  options: Options<SearchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SearchResponses,
    SearchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/search',
    ...options,
  })
}

/**
 * List Available Tools
 * List all available tool configurations from S3.
 *
 * Returns a list of tool IDs (config filenames without extensions).
 */
export const listAvailableTools = <ThrowOnError extends boolean = false>(
  options?: Options<ListAvailableToolsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListAvailableToolsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tools/',
    ...options,
  })
}

/**
 * Get Tool Config
 * Retrieve a specific tool configuration.
 *
 * Args:
 * tool_id: The tool identifier (filename without extension)
 *
 * Returns:
 * Complete tool configuration
 */
export const getToolConfig = <ThrowOnError extends boolean = false>(
  options: Options<GetToolConfigData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetToolConfigResponses,
    GetToolConfigErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tools/{tool_id}',
    ...options,
  })
}

/**
 * Get Vendors
 * Retrieve a list of all vendors.
 */
export const getVendors = <ThrowOnError extends boolean = false>(
  options?: Options<GetVendorsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetVendorsResponses,
    GetVendorsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/vendors',
    ...options,
  })
}

/**
 * Add Vendor
 * Create a new vendor with optional attributes.
 */
export const addVendor = <ThrowOnError extends boolean = false>(
  options: Options<AddVendorData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    AddVendorResponses,
    AddVendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/vendors',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Delete Vendor
 * Delete a specific vendor by ID.
 */
export const deleteVendor = <ThrowOnError extends boolean = false>(
  options: Options<DeleteVendorData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteVendorResponses,
    DeleteVendorErrors,
    ThrowOnError
  >({
    url: '/api/v1/vendors/{vendor_id}',
    ...options,
  })
}

/**
 * Get Vendor
 * Retrieve a specific vendor by ID.
 */
export const getVendor = <ThrowOnError extends boolean = false>(
  options: Options<GetVendorData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetVendorResponses,
    GetVendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/vendors/{vendor_id}',
    ...options,
  })
}

/**
 * Update Vendor
 * Update information about a specific vendor.
 */
export const updateVendor = <ThrowOnError extends boolean = false>(
  options: Options<UpdateVendorData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpdateVendorResponses,
    UpdateVendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/vendors/{vendor_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Latest Manifest
 * Retrieve the latest manifest file path from the specified S3 bucket.
 *
 * Searches recursively through the bucket/prefix for files that:
 * - Contain "manifest" (case-insensitive)
 * - End with ".csv"
 *
 * Returns the full S3 path of the most recent matching file.
 *
 * Args:
 * s3_path: S3 path to search (e.g., "s3://bucket-name/path/to/manifests")
 *
 * Returns:
 * Full S3 path to the latest manifest file
 */
export const getLatestManifest = <ThrowOnError extends boolean = false>(
  options: Options<GetLatestManifestData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetLatestManifestResponses,
    GetLatestManifestErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/manifest',
    ...options,
  })
}

/**
 * Upload Manifest
 * Upload a manifest CSV file to the specified S3 path.
 *
 * Args:
 * s3_path: S3 path where the file should be uploaded (e.g., "s3://bucket-name/path/to/manifest.csv")
 * file: The manifest CSV file to upload
 *
 * Returns:
 * ManifestUploadResponse with the uploaded file path and status
 */
export const uploadManifest = <ThrowOnError extends boolean = false>(
  options: Options<UploadManifestData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    UploadManifestResponses,
    UploadManifestErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/manifest',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })
}

/**
 * Validate Manifest
 * Validate a manifest CSV file from S3.
 *
 * Checks the manifest file for:
 * - Required fields
 * - Data format compliance
 * - Value constraints
 *
 * Args:
 * s3_path: S3 path to the manifest CSV file to validate
 * valid: Mock parameter to simulate valid or invalid responses for testing
 *
 * Returns:
 * ManifestValidationResponse with validation status and any errors found
 */
export const validateManifest = <ThrowOnError extends boolean = false>(
  options: Options<ValidateManifestData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ValidateManifestResponses,
    ValidateManifestErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/manifest/validate',
    ...options,
  })
}
