// This file is auto-generated by @hey-api/openapi-ts

/**
 * Attribute
 */
export type Attribute = {
  /**
   * Key
   */
  key: string | null
  /**
   * Value
   */
  value: string | null
}

/**
 * Body_post_run_samplesheet
 */
export type BodyPostRunSamplesheet = {
  /**
   * File
   * File to upload
   */
  file: Blob | File
}

/**
 * ConversionResult
 */
export type ConversionResult = {
  /**
   * Lanenumber
   */
  LaneNumber: number
  /**
   * Totalclustersraw
   */
  TotalClustersRaw: number
  /**
   * Totalclusterspf
   */
  TotalClustersPF: number
  /**
   * Yield
   */
  Yield?: number | null
  /**
   * Demuxresults
   */
  DemuxResults?: Array<DemuxResult> | null
  Undetermined?: UndeterminedType | null
}

/**
 * DemuxResult
 */
export type DemuxResult = {
  /**
   * Sampleid
   */
  SampleId: string
  /**
   * Samplename
   */
  SampleName?: string | null
  /**
   * Indexmetrics
   */
  IndexMetrics?: Array<IndexMetric> | null
  /**
   * Numberreads
   */
  NumberReads?: number
  /**
   * Yield
   */
  Yield?: number | null
  /**
   * Readmetrics
   */
  ReadMetrics?: Array<ReadMetricsType>
}

/**
 * FileBrowserData
 * File browser data structure with separate folders and files
 */
export type FileBrowserData = {
  /**
   * Folders
   */
  folders: Array<FileBrowserFolder>
  /**
   * Files
   */
  files: Array<FileBrowserFile>
}

/**
 * FileBrowserFile
 * File item for file browser
 */
export type FileBrowserFile = {
  /**
   * Name
   */
  name: string
  /**
   * Date
   */
  date: string
  /**
   * Size
   */
  size: number
}

/**
 * FileBrowserFolder
 * Folder item for file browser
 */
export type FileBrowserFolder = {
  /**
   * Name
   */
  name: string
  /**
   * Date
   */
  date: string
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * IlluminaMetricsResponseModel
 */
export type IlluminaMetricsResponseModel = {
  /**
   * Flowcell
   */
  Flowcell?: string | null
  /**
   * Runnumber
   */
  RunNumber?: number | null
  /**
   * Runid
   */
  RunId?: string | null
  /**
   * Readinfosforlanes
   */
  ReadInfosForLanes?: Array<ReadInfosForLane> | null
  /**
   * Conversionresults
   */
  ConversionResults?: Array<ConversionResult> | null
  /**
   * Unknownbarcodes
   */
  UnknownBarcodes?: Array<UnknownBarcode> | null
}

/**
 * IlluminaSampleSheetResponseModel
 */
export type IlluminaSampleSheetResponseModel = {
  /**
   * Summary
   */
  Summary?: {
    [key: string]: string
  } | null
  /**
   * Header
   */
  Header?: {
    [key: string]: string
  } | null
  /**
   * Reads
   */
  Reads?: Array<number> | null
  /**
   * Settings
   */
  Settings?: {
    [key: string]: string
  } | null
  /**
   * Data
   */
  Data?: Array<{
    [key: string]: string
  }> | null
  /**
   * Datacols
   */
  DataCols?: Array<string> | null
}

/**
 * IndexMetric
 */
export type IndexMetric = {
  /**
   * Indexsequence
   */
  IndexSequence?: string | null
  /**
   * Mismatchcounts
   */
  MismatchCounts?: {
    [key: string]: number
  } | null
}

/**
 * ProjectCreate
 */
export type ProjectCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Attributes
   */
  attributes?: Array<Attribute> | null
}

/**
 * ProjectPublic
 */
export type ProjectPublic = {
  /**
   * Project Id
   */
  project_id: string
  /**
   * Name
   */
  name: string | null
  /**
   * Attributes
   */
  attributes: Array<Attribute> | null
}

/**
 * ProjectsPublic
 */
export type ProjectsPublic = {
  /**
   * Data
   */
  data: Array<ProjectPublic>
  /**
   * Total Items
   */
  total_items: number
  /**
   * Total Pages
   */
  total_pages: number
  /**
   * Current Page
   */
  current_page: number
  /**
   * Per Page
   */
  per_page: number
  /**
   * Has Next
   */
  has_next: boolean
  /**
   * Has Prev
   */
  has_prev: boolean
}

/**
 * ReadInfo
 */
export type ReadInfo = {
  /**
   * Number
   */
  Number?: number | null
  /**
   * Numcycles
   */
  NumCycles?: number | null
  /**
   * Isindexedread
   */
  IsIndexedRead?: boolean | null
}

/**
 * ReadInfosForLane
 */
export type ReadInfosForLane = {
  /**
   * Lanenumber
   */
  LaneNumber?: number | null
  /**
   * Readinfos
   */
  ReadInfos?: Array<ReadInfo> | null
}

/**
 * ReadMetricsType
 */
export type ReadMetricsType = {
  /**
   * Readnumber
   */
  ReadNumber?: number | null
  /**
   * Yield
   */
  Yield?: number | null
  /**
   * Yieldq30
   */
  YieldQ30?: number | null
  /**
   * Qualityscoresum
   */
  QualityScoreSum?: number | null
  /**
   * Trimmedbases
   */
  TrimmedBases?: number | null
}

/**
 * RunStatus
 * Enumeration of valid sequencing run statuses
 */
export type RunStatus = 'In Progress' | 'Uploading' | 'Ready' | 'Resync'

/**
 * SampleCreate
 */
export type SampleCreate = {
  /**
   * Sample Id
   */
  sample_id: string
  /**
   * Attributes
   */
  attributes?: Array<Attribute> | null
}

/**
 * SamplePublic
 */
export type SamplePublic = {
  /**
   * Sample Id
   */
  sample_id: string
  /**
   * Project Id
   */
  project_id: string
  /**
   * Attributes
   */
  attributes: Array<Attribute> | null
}

/**
 * SamplesPublic
 */
export type SamplesPublic = {
  /**
   * Data
   */
  data: Array<SamplePublic>
  /**
   * Total Items
   */
  total_items: number
  /**
   * Total Pages
   */
  total_pages: number
  /**
   * Current Page
   */
  current_page: number
  /**
   * Per Page
   */
  per_page: number
  /**
   * Has Next
   */
  has_next: boolean
  /**
   * Has Prev
   */
  has_prev: boolean
}

/**
 * SearchResponse
 */
export type SearchResponse = {
  projects: ProjectsPublic
  runs: SequencingRunsPublic
}

/**
 * SequencingRunCreate
 */
export type SequencingRunCreate = {
  /**
   * Run Date
   */
  run_date: string
  /**
   * Machine Id
   */
  machine_id: string
  /**
   * Run Number
   */
  run_number: number
  /**
   * Flowcell Id
   */
  flowcell_id: string
  /**
   * Experiment Name
   */
  experiment_name?: string | null
  /**
   * Run Folder Uri
   */
  run_folder_uri?: string | null
  status?: RunStatus | null
  /**
   * Run Time
   */
  run_time?: string | null
}

/**
 * SequencingRunPublic
 */
export type SequencingRunPublic = {
  /**
   * Run Date
   */
  run_date: string
  /**
   * Machine Id
   */
  machine_id: string
  /**
   * Run Number
   */
  run_number: number
  /**
   * Flowcell Id
   */
  flowcell_id: string
  /**
   * Experiment Name
   */
  experiment_name: string | null
  /**
   * Run Folder Uri
   */
  run_folder_uri: string | null
  status: RunStatus | null
  /**
   * Run Time
   */
  run_time: string | null
  /**
   * Barcode
   */
  barcode: string | null
}

/**
 * SequencingRunUpdateRequest
 */
export type SequencingRunUpdateRequest = {
  run_status: RunStatus
}

/**
 * SequencingRunsPublic
 */
export type SequencingRunsPublic = {
  /**
   * Data
   */
  data: Array<SequencingRunPublic>
  /**
   * Total Items
   */
  total_items: number
  /**
   * Total Pages
   */
  total_pages: number
  /**
   * Current Page
   */
  current_page: number
  /**
   * Per Page
   */
  per_page: number
  /**
   * Has Next
   */
  has_next: boolean
  /**
   * Has Prev
   */
  has_prev: boolean
}

/**
 * UndeterminedType
 */
export type UndeterminedType = {
  /**
   * Numberreads
   */
  NumberReads?: number | null
  /**
   * Yield
   */
  Yield?: number | null
  /**
   * Readmetrics
   */
  ReadMetrics?: Array<ReadMetricsType> | null
}

/**
 * UnknownBarcode
 */
export type UnknownBarcode = {
  /**
   * Lane
   */
  Lane?: number | null
  /**
   * Barcodes
   */
  Barcodes?: {
    [key: string]: number
  } | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type RootData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ListFilesData = {
  body?: never
  path?: never
  query: {
    /**
     * Uri
     * URI to list (e.g., s3://bucket/folder/)
     */
    uri: string
  }
  url: '/api/v1/files/list'
}

export type ListFilesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors]

export type ListFilesResponses = {
  /**
   * Successful Response
   */
  200: FileBrowserData
}

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses]

export type GetProjectsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/projects'
}

export type GetProjectsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetProjectsError = GetProjectsErrors[keyof GetProjectsErrors]

export type GetProjectsResponses = {
  /**
   * Successful Response
   */
  200: ProjectsPublic
}

export type GetProjectsResponse =
  GetProjectsResponses[keyof GetProjectsResponses]

export type CreateProjectData = {
  body: ProjectCreate
  path?: never
  query?: never
  url: '/api/v1/projects'
}

export type CreateProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors]

export type CreateProjectResponses = {
  /**
   * Successful Response
   */
  201: ProjectPublic
}

export type CreateProjectResponse =
  CreateProjectResponses[keyof CreateProjectResponses]

export type SearchProjectsData = {
  body?: never
  path?: never
  query: {
    /**
     * Query
     * Search query string
     */
    query: string
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: ('project_id' | 'name') | null
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: ('asc' | 'desc') | null
  }
  url: '/api/v1/projects/search'
}

export type SearchProjectsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SearchProjectsError =
  SearchProjectsErrors[keyof SearchProjectsErrors]

export type SearchProjectsResponses = {
  /**
   * Successful Response
   */
  200: ProjectsPublic
}

export type SearchProjectsResponse =
  SearchProjectsResponses[keyof SearchProjectsResponses]

export type GetProjectByProjectIdData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: '/api/v1/projects/{project_id}'
}

export type GetProjectByProjectIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetProjectByProjectIdError =
  GetProjectByProjectIdErrors[keyof GetProjectByProjectIdErrors]

export type GetProjectByProjectIdResponses = {
  /**
   * Successful Response
   */
  200: ProjectPublic
}

export type GetProjectByProjectIdResponse =
  GetProjectByProjectIdResponses[keyof GetProjectByProjectIdResponses]

export type GetSamplesData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: {
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/projects/{project_id}/samples'
}

export type GetSamplesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetSamplesError = GetSamplesErrors[keyof GetSamplesErrors]

export type GetSamplesResponses = {
  /**
   * Successful Response
   */
  200: SamplesPublic
}

export type GetSamplesResponse = GetSamplesResponses[keyof GetSamplesResponses]

export type AddSampleToProjectData = {
  body: SampleCreate
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: '/api/v1/projects/{project_id}/samples'
}

export type AddSampleToProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AddSampleToProjectError =
  AddSampleToProjectErrors[keyof AddSampleToProjectErrors]

export type AddSampleToProjectResponses = {
  /**
   * Successful Response
   */
  201: SamplePublic
}

export type AddSampleToProjectResponse =
  AddSampleToProjectResponses[keyof AddSampleToProjectResponses]

export type GetRunsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/runs'
}

export type GetRunsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRunsError = GetRunsErrors[keyof GetRunsErrors]

export type GetRunsResponses = {
  /**
   * Successful Response
   */
  200: SequencingRunsPublic
}

export type GetRunsResponse = GetRunsResponses[keyof GetRunsResponses]

export type AddRunData = {
  body: SequencingRunCreate
  path?: never
  query?: never
  url: '/api/v1/runs'
}

export type AddRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AddRunError = AddRunErrors[keyof AddRunErrors]

export type AddRunResponses = {
  /**
   * Successful Response
   */
  201: SequencingRunPublic
}

export type AddRunResponse = AddRunResponses[keyof AddRunResponses]

export type SearchRunsData = {
  body?: never
  path?: never
  query: {
    /**
     * Query
     * Search query string
     */
    query: string
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: ('barcode' | 'experiment_name') | null
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: ('asc' | 'desc') | null
  }
  url: '/api/v1/runs/search'
}

export type SearchRunsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SearchRunsError = SearchRunsErrors[keyof SearchRunsErrors]

export type SearchRunsResponses = {
  /**
   * Successful Response
   */
  200: SequencingRunsPublic
}

export type SearchRunsResponse = SearchRunsResponses[keyof SearchRunsResponses]

export type GetRunData = {
  body?: never
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}'
}

export type GetRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRunError = GetRunErrors[keyof GetRunErrors]

export type GetRunResponses = {
  /**
   * Successful Response
   */
  200: SequencingRunPublic
}

export type GetRunResponse = GetRunResponses[keyof GetRunResponses]

export type UpdateRunData = {
  body: SequencingRunUpdateRequest
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}'
}

export type UpdateRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateRunError = UpdateRunErrors[keyof UpdateRunErrors]

export type UpdateRunResponses = {
  /**
   * Successful Response
   */
  200: SequencingRunPublic
}

export type UpdateRunResponse = UpdateRunResponses[keyof UpdateRunResponses]

export type GetRunSamplesheetData = {
  body?: never
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}/samplesheet'
}

export type GetRunSamplesheetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRunSamplesheetError =
  GetRunSamplesheetErrors[keyof GetRunSamplesheetErrors]

export type GetRunSamplesheetResponses = {
  /**
   * Successful Response
   */
  200: IlluminaSampleSheetResponseModel
}

export type GetRunSamplesheetResponse =
  GetRunSamplesheetResponses[keyof GetRunSamplesheetResponses]

export type PostRunSamplesheetData = {
  body: BodyPostRunSamplesheet
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}/samplesheet'
}

export type PostRunSamplesheetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PostRunSamplesheetError =
  PostRunSamplesheetErrors[keyof PostRunSamplesheetErrors]

export type PostRunSamplesheetResponses = {
  /**
   * Successful Response
   */
  201: IlluminaSampleSheetResponseModel
}

export type PostRunSamplesheetResponse =
  PostRunSamplesheetResponses[keyof PostRunSamplesheetResponses]

export type GetRunMetricsData = {
  body?: never
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}/metrics'
}

export type GetRunMetricsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRunMetricsError = GetRunMetricsErrors[keyof GetRunMetricsErrors]

export type GetRunMetricsResponses = {
  /**
   * Successful Response
   */
  200: IlluminaMetricsResponseModel
}

export type GetRunMetricsResponse =
  GetRunMetricsResponses[keyof GetRunMetricsResponses]

export type SearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Query
     * Search query string
     */
    query: string
    /**
     * N Results
     * Number of results to return per index
     */
    n_results?: number
  }
  url: '/api/v1/search'
}

export type SearchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SearchError = SearchErrors[keyof SearchErrors]

export type SearchResponses = {
  /**
   * Successful Response
   */
  200: SearchResponse
}

export type SearchResponse2 = SearchResponses[keyof SearchResponses]

export type ClientOptions = {
  baseURL: 'http://apiserver:3000' | (string & {})
}
