// This file is auto-generated by @hey-api/openapi-ts

/**
 * Attribute
 */
export type Attribute = {
  /**
   * Key
   */
  key: string | null
  /**
   * Value
   */
  value: string | null
}

/**
 * AvailableProvidersResponse
 * Available OAuth providers response
 */
export type AvailableProvidersResponse = {
  /**
   * Count
   */
  count: number
  /**
   * Providers
   */
  providers: Array<OAuthProviderInfo>
}

/**
 * AwsBatchConfig
 * Base schema for AWS Batch job configuration
 */
export type AwsBatchConfig = {
  /**
   * Job Name
   */
  job_name: string
  /**
   * Job Definition
   */
  job_definition: string
  /**
   * Job Queue
   */
  job_queue: string
  /**
   * Command
   */
  command: string
  /**
   * Environment
   */
  environment?: Array<AwsBatchEnvironment> | null
}

/**
 * AwsBatchEnvironment
 * Schema for AWS Batch environment variable
 */
export type AwsBatchEnvironment = {
  /**
   * Name
   */
  name: string
  /**
   * Value
   */
  value: string
}

/**
 * BatchJobPublic
 * Schema for returning a batch job
 */
export type BatchJobPublic = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Command
   */
  command: string
  /**
   * User
   */
  user: string
  /**
   * Submitted On
   */
  submitted_on: string
  /**
   * Aws Job Id
   */
  aws_job_id: string | null
  /**
   * Log Stream Name
   */
  log_stream_name: string | null
  status: JobStatus
  /**
   * Viewed
   */
  viewed: boolean
}

/**
 * BatchJobSubmit
 * Schema for submitting a new batch job to AWS Batch (extends AwsBatchConfig)
 */
export type BatchJobSubmit = {
  /**
   * Job Name
   */
  job_name: string
  /**
   * Job Definition
   */
  job_definition: string
  /**
   * Job Queue
   */
  job_queue: string
  /**
   * Command
   */
  command: string
  /**
   * Environment
   */
  environment?: Array<AwsBatchEnvironment> | null
  /**
   * User
   */
  user: string
}

/**
 * BatchJobUpdate
 * Schema for updating a batch job
 */
export type BatchJobUpdate = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Command
   */
  command?: string | null
  /**
   * Aws Job Id
   */
  aws_job_id?: string | null
  /**
   * Log Stream Name
   */
  log_stream_name?: string | null
  status?: JobStatus | null
  /**
   * Viewed
   */
  viewed?: boolean | null
}

/**
 * BatchJobsPublic
 * Schema for returning multiple batch jobs
 */
export type BatchJobsPublic = {
  /**
   * Data
   */
  data: Array<BatchJobPublic>
  /**
   * Count
   */
  count: number
}

/**
 * Body_create_file
 */
export type BodyCreateFile = {
  /**
   * Filename
   */
  filename: string
  entity_type: EntityType
  /**
   * Entity Id
   */
  entity_id: string
  /**
   * Relative Path
   */
  relative_path?: string | null
  /**
   * Overwrite
   */
  overwrite?: boolean
  /**
   * Description
   */
  description?: string | null
  /**
   * Is Public
   */
  is_public?: boolean
  /**
   * Created By
   */
  created_by?: string | null
  /**
   * Content
   */
  content?: (Blob | File) | null
}

/**
 * Body_login
 */
export type BodyLogin = {
  /**
   * Grant Type
   */
  grant_type?: string | null
  /**
   * Username
   */
  username: string
  /**
   * Password
   */
  password: string
  /**
   * Scope
   */
  scope?: string
  /**
   * Client Id
   */
  client_id?: string | null
  /**
   * Client Secret
   */
  client_secret?: string | null
}

/**
 * Body_post_run_samplesheet
 */
export type BodyPostRunSamplesheet = {
  /**
   * File
   * File to upload
   */
  file: Blob | File
}

/**
 * Body_upload_manifest
 */
export type BodyUploadManifest = {
  /**
   * File
   * Manifest CSV file to upload
   */
  file: Blob | File
}

/**
 * ConversionResult
 */
export type ConversionResult = {
  /**
   * Lanenumber
   */
  LaneNumber: number
  /**
   * Totalclustersraw
   */
  TotalClustersRaw: number
  /**
   * Totalclusterspf
   */
  TotalClustersPF: number
  /**
   * Yield
   */
  Yield?: number | null
  /**
   * Demuxresults
   */
  DemuxResults?: Array<DemuxResult> | null
  Undetermined?: UndeterminedType | null
}

/**
 * DemuxResult
 */
export type DemuxResult = {
  /**
   * Sampleid
   */
  SampleId: string
  /**
   * Samplename
   */
  SampleName?: string | null
  /**
   * Indexmetrics
   */
  IndexMetrics?: Array<IndexMetric> | null
  /**
   * Numberreads
   */
  NumberReads?: number
  /**
   * Yield
   */
  Yield?: number | null
  /**
   * Readmetrics
   */
  ReadMetrics?: Array<ReadMetricsType>
}

/**
 * DemuxWorkflowConfig
 */
export type DemuxWorkflowConfig = {
  /**
   * Version
   */
  version: number
  /**
   * Workflow Id
   */
  workflow_id: string
  /**
   * Workflow Name
   */
  workflow_name: string
  /**
   * Workflow Description
   */
  workflow_description: string
  /**
   * Inputs
   */
  inputs: Array<DemuxWorkflowConfigInput>
  /**
   * Help
   */
  help: string
  /**
   * Tags
   */
  tags: Array<DemuxWorkflowTag>
  aws_batch?: AwsBatchConfig | null
}

/**
 * DemuxWorkflowConfigInput
 */
export type DemuxWorkflowConfigInput = {
  /**
   * Name
   */
  name: string
  /**
   * Desc
   */
  desc: string
  type: InputType
  /**
   * Required
   */
  required?: boolean
  /**
   * Default
   */
  default?: unknown | null
  /**
   * Options
   */
  options?: Array<string> | null
}

/**
 * DemuxWorkflowSubmitBody
 */
export type DemuxWorkflowSubmitBody = {
  /**
   * Workflow Id
   */
  workflow_id: string
  /**
   * Run Barcode
   */
  run_barcode: string
  /**
   * Inputs
   */
  inputs: {
    [key: string]: unknown
  }
}

/**
 * DemuxWorkflowTag
 */
export type DemuxWorkflowTag = {
  /**
   * Name
   */
  name: string
}

/**
 * EmailVerificationRequest
 * Email verification request
 */
export type EmailVerificationRequest = {
  /**
   * Token
   */
  token: string
}

/**
 * EntityType
 * Entity types that can have files
 */
export type EntityType = 'project' | 'run'

/**
 * FileBrowserData
 * File browser data structure with separate folders and files
 */
export type FileBrowserData = {
  /**
   * Folders
   */
  folders: Array<FileBrowserFolder>
  /**
   * Files
   */
  files: Array<FileBrowserFile>
}

/**
 * FileBrowserFile
 * File item for file browser
 */
export type FileBrowserFile = {
  /**
   * Name
   */
  name: string
  /**
   * Date
   */
  date: string
  /**
   * Size
   */
  size: number
}

/**
 * FileBrowserFolder
 * Folder item for file browser
 */
export type FileBrowserFolder = {
  /**
   * Name
   */
  name: string
  /**
   * Date
   */
  date: string
}

/**
 * FilePublic
 * Public file representation
 */
export type FilePublic = {
  /**
   * File Id
   */
  file_id: string
  /**
   * Filename
   */
  filename: string
  /**
   * Original Filename
   */
  original_filename: string
  /**
   * File Size
   */
  file_size: number | null
  /**
   * Mime Type
   */
  mime_type: string | null
  /**
   * Description
   */
  description: string | null
  /**
   * Upload Date
   */
  upload_date: string
  /**
   * Created By
   */
  created_by: string | null
  entity_type: EntityType
  /**
   * Entity Id
   */
  entity_id: string
  /**
   * Is Public
   */
  is_public: boolean
  /**
   * Is Archived
   */
  is_archived: boolean
  storage_backend: StorageBackend
  /**
   * File Path
   */
  file_path?: string | null
  /**
   * Checksum
   */
  checksum?: string | null
  /**
   * Relative Path
   */
  relative_path?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * IlluminaMetricsResponseModel
 */
export type IlluminaMetricsResponseModel = {
  /**
   * Flowcell
   */
  Flowcell?: string | null
  /**
   * Runnumber
   */
  RunNumber?: number | null
  /**
   * Runid
   */
  RunId?: string | null
  /**
   * Readinfosforlanes
   */
  ReadInfosForLanes?: Array<ReadInfosForLane> | null
  /**
   * Conversionresults
   */
  ConversionResults?: Array<ConversionResult> | null
  /**
   * Unknownbarcodes
   */
  UnknownBarcodes?: Array<UnknownBarcode> | null
}

/**
 * IlluminaSampleSheetResponseModel
 */
export type IlluminaSampleSheetResponseModel = {
  /**
   * Summary
   */
  Summary?: {
    [key: string]: string
  } | null
  /**
   * Header
   */
  Header?: {
    [key: string]: string
  } | null
  /**
   * Reads
   */
  Reads?: Array<number> | null
  /**
   * Settings
   */
  Settings?: {
    [key: string]: string
  } | null
  /**
   * Data
   */
  Data?: Array<{
    [key: string]: string
  }> | null
  /**
   * Datacols
   */
  DataCols?: Array<string> | null
}

/**
 * IndexMetric
 */
export type IndexMetric = {
  /**
   * Indexsequence
   */
  IndexSequence?: string | null
  /**
   * Mismatchcounts
   */
  MismatchCounts?: {
    [key: string]: number
  } | null
}

/**
 * InputType
 */
export type InputType = 'Enum' | 'String' | 'Integer' | 'Boolean'

/**
 * JobStatus
 * Enumeration of valid batch job statuses
 */
export type JobStatus =
  | 'Submitted'
  | 'Pending'
  | 'Runnable'
  | 'Starting'
  | 'Running'
  | 'Succeeded'
  | 'Failed'

/**
 * ManifestUploadResponse
 * Response model for manifest file upload
 */
export type ManifestUploadResponse = {
  /**
   * Status
   * Status of the upload operation
   */
  status: string
  /**
   * Message
   * Human-readable message about the upload
   */
  message: string
  /**
   * Path
   * Full S3 path where the file was uploaded
   */
  path: string
  /**
   * Filename
   * Name of the uploaded file
   */
  filename: string
}

/**
 * ManifestValidationResponse
 * Response model for manifest validation
 */
export type ManifestValidationResponse = {
  /**
   * Valid
   * Whether the manifest is valid
   */
  valid: boolean
  /**
   * Message
   * Informational messages about the validation
   */
  message?: {
    [key: string]: string
  }
  /**
   * Error
   * Validation errors grouped by category
   */
  error?: {
    [key: string]: Array<string>
  }
  /**
   * Warning
   * Validation warnings grouped by category
   */
  warning?: {
    [key: string]: Array<string>
  }
}

/**
 * OAuthLinkRequest
 * Link OAuth provider to account
 */
export type OAuthLinkRequest = {
  /**
   * Code
   */
  code: string
}

/**
 * OAuthProviderInfo
 * OAuth provider information
 */
export type OAuthProviderInfo = {
  /**
   * Name
   */
  name: string
  /**
   * Display Name
   */
  display_name: string
  /**
   * Logo Url
   */
  logo_url: string
  /**
   * Authorize Url
   */
  authorize_url: string
}

/**
 * PasswordChange
 * Password change request
 */
export type PasswordChange = {
  /**
   * Current Password
   */
  current_password: string
  /**
   * New Password
   */
  new_password: string
}

/**
 * PasswordResetConfirm
 * Password reset confirmation
 */
export type PasswordResetConfirm = {
  /**
   * Token
   */
  token: string
  /**
   * New Password
   */
  new_password: string
}

/**
 * PasswordResetRequest
 * Password reset request
 */
export type PasswordResetRequest = {
  /**
   * Email
   */
  email: string
}

/**
 * ProjectCreate
 */
export type ProjectCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Attributes
   */
  attributes?: Array<Attribute> | null
}

/**
 * ProjectPublic
 */
export type ProjectPublic = {
  /**
   * Project Id
   */
  project_id: string
  /**
   * Name
   */
  name: string | null
  /**
   * Data Folder Uri
   */
  data_folder_uri: string | null
  /**
   * Results Folder Uri
   */
  results_folder_uri: string | null
  /**
   * Attributes
   */
  attributes: Array<Attribute> | null
}

/**
 * ProjectsPublic
 */
export type ProjectsPublic = {
  /**
   * Data
   */
  data: Array<ProjectPublic>
  /**
   * Total Items
   */
  total_items: number
  /**
   * Total Pages
   */
  total_pages: number
  /**
   * Current Page
   */
  current_page: number
  /**
   * Per Page
   */
  per_page: number
  /**
   * Has Next
   */
  has_next: boolean
  /**
   * Has Prev
   */
  has_prev: boolean
}

/**
 * ReadInfo
 */
export type ReadInfo = {
  /**
   * Number
   */
  Number?: number | null
  /**
   * Numcycles
   */
  NumCycles?: number | null
  /**
   * Isindexedread
   */
  IsIndexedRead?: boolean | null
}

/**
 * ReadInfosForLane
 */
export type ReadInfosForLane = {
  /**
   * Lanenumber
   */
  LaneNumber?: number | null
  /**
   * Readinfos
   */
  ReadInfos?: Array<ReadInfo> | null
}

/**
 * ReadMetricsType
 */
export type ReadMetricsType = {
  /**
   * Readnumber
   */
  ReadNumber?: number | null
  /**
   * Yield
   */
  Yield?: number | null
  /**
   * Yieldq30
   */
  YieldQ30?: number | null
  /**
   * Qualityscoresum
   */
  QualityScoreSum?: number | null
  /**
   * Trimmedbases
   */
  TrimmedBases?: number | null
}

/**
 * RefreshTokenRequest
 * Refresh token request
 */
export type RefreshTokenRequest = {
  /**
   * Refresh Token
   */
  refresh_token: string
}

/**
 * ResendVerificationRequest
 * Resend verification email request
 */
export type ResendVerificationRequest = {
  /**
   * Email
   */
  email: string
}

/**
 * RunStatus
 * Enumeration of valid sequencing run statuses
 */
export type RunStatus = 'In Progress' | 'Uploading' | 'Ready' | 'Resync'

/**
 * SampleCreate
 */
export type SampleCreate = {
  /**
   * Sample Id
   */
  sample_id: string
  /**
   * Attributes
   */
  attributes?: Array<Attribute> | null
}

/**
 * SamplePublic
 */
export type SamplePublic = {
  /**
   * Sample Id
   */
  sample_id: string
  /**
   * Project Id
   */
  project_id: string
  /**
   * Attributes
   */
  attributes: Array<Attribute> | null
}

/**
 * SamplesPublic
 */
export type SamplesPublic = {
  /**
   * Data
   */
  data: Array<SamplePublic>
  /**
   * Data Cols
   */
  data_cols?: Array<string> | null
  /**
   * Total Items
   */
  total_items: number
  /**
   * Total Pages
   */
  total_pages: number
  /**
   * Current Page
   */
  current_page: number
  /**
   * Per Page
   */
  per_page: number
  /**
   * Has Next
   */
  has_next: boolean
  /**
   * Has Prev
   */
  has_prev: boolean
}

/**
 * SearchResponse
 */
export type SearchResponse = {
  projects: ProjectsPublic
  runs: SequencingRunsPublic
}

/**
 * SequencingRunCreate
 */
export type SequencingRunCreate = {
  /**
   * Run Date
   */
  run_date: string
  /**
   * Machine Id
   */
  machine_id: string
  /**
   * Run Number
   */
  run_number: number
  /**
   * Flowcell Id
   */
  flowcell_id: string
  /**
   * Experiment Name
   */
  experiment_name?: string | null
  /**
   * Run Folder Uri
   */
  run_folder_uri?: string | null
  status?: RunStatus | null
  /**
   * Run Time
   */
  run_time?: string | null
}

/**
 * SequencingRunPublic
 */
export type SequencingRunPublic = {
  /**
   * Run Date
   */
  run_date: string
  /**
   * Machine Id
   */
  machine_id: string
  /**
   * Run Number
   */
  run_number: number
  /**
   * Flowcell Id
   */
  flowcell_id: string
  /**
   * Experiment Name
   */
  experiment_name: string | null
  /**
   * Run Folder Uri
   */
  run_folder_uri: string | null
  status: RunStatus | null
  /**
   * Run Time
   */
  run_time: string | null
  /**
   * Barcode
   */
  barcode: string | null
}

/**
 * SequencingRunUpdateRequest
 */
export type SequencingRunUpdateRequest = {
  run_status: RunStatus
}

/**
 * SequencingRunsPublic
 */
export type SequencingRunsPublic = {
  /**
   * Data
   */
  data: Array<SequencingRunPublic>
  /**
   * Total Items
   */
  total_items: number
  /**
   * Total Pages
   */
  total_pages: number
  /**
   * Current Page
   */
  current_page: number
  /**
   * Per Page
   */
  per_page: number
  /**
   * Has Next
   */
  has_next: boolean
  /**
   * Has Prev
   */
  has_prev: boolean
}

/**
 * Setting
 * Represents an application setting with a fixed key.
 * Keys are used as primary identifiers and cannot be changed.
 */
export type Setting = {
  /**
   * Key
   */
  key: string
  /**
   * Value
   */
  value: string
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Tags
   */
  tags?: Array<{
    [key: string]: string
  }> | null
  /**
   * Created At
   */
  created_at?: string | null
  /**
   * Updated At
   */
  updated_at?: string | null
}

/**
 * SettingUpdate
 * Represents the data needed to update a setting.
 * Note: key cannot be updated as it's the primary key.
 */
export type SettingUpdate = {
  /**
   * Value
   */
  value?: string | null
  /**
   * Name
   */
  name?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Tags
   */
  tags?: Array<{
    [key: string]: string
  }> | null
}

/**
 * StorageBackend
 * Storage backend types
 */
export type StorageBackend = 'local' | 's3' | 'azure' | 'gcs'

/**
 * TokenResponse
 * Authentication token response
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Refresh Token
   */
  refresh_token: string
  /**
   * Token Type
   */
  token_type?: string
  /**
   * Expires In
   */
  expires_in: number
}

/**
 * UndeterminedType
 */
export type UndeterminedType = {
  /**
   * Numberreads
   */
  NumberReads?: number | null
  /**
   * Yield
   */
  Yield?: number | null
  /**
   * Readmetrics
   */
  ReadMetrics?: Array<ReadMetricsType> | null
}

/**
 * UnknownBarcode
 */
export type UnknownBarcode = {
  /**
   * Lane
   */
  Lane?: number | null
  /**
   * Barcodes
   */
  Barcodes?: {
    [key: string]: number
  } | null
}

/**
 * UserPublic
 * Public user information
 */
export type UserPublic = {
  /**
   * Email
   */
  email: string
  /**
   * Username
   */
  username: string
  /**
   * Full Name
   */
  full_name: string | null
  /**
   * Is Active
   */
  is_active: boolean
  /**
   * Is Verified
   */
  is_verified: boolean
  /**
   * Is Superuser
   */
  is_superuser: boolean
  /**
   * Created At
   */
  created_at: string
  /**
   * Last Login
   */
  last_login: string | null
  /**
   * Oauth Providers
   */
  oauth_providers?: Array<string>
}

/**
 * UserRegister
 * User registration request
 */
export type UserRegister = {
  /**
   * Email
   */
  email: string
  /**
   * Username
   */
  username: string
  /**
   * Password
   */
  password: string
  /**
   * Full Name
   */
  full_name?: string | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

/**
 * VendorCreate
 * Represents the data needed to create a vendor
 */
export type VendorCreate = {
  /**
   * Vendor Id
   */
  vendor_id: string
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string
  /**
   * Bucket
   */
  bucket?: string | null
}

/**
 * VendorPublic
 * Represents a public view of a vendor
 */
export type VendorPublic = {
  /**
   * Vendor Id
   */
  vendor_id: string
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string
  /**
   * Bucket
   */
  bucket?: string | null
}

/**
 * VendorUpdate
 * Represents the data that can be updated for a vendor
 */
export type VendorUpdate = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Bucket
   */
  bucket?: string | null
}

/**
 * VendorsPublic
 * Represents a paginated list of vendors
 */
export type VendorsPublic = {
  /**
   * Data
   */
  data: Array<VendorPublic>
  /**
   * Total Items
   */
  total_items: number
  /**
   * Total Pages
   */
  total_pages: number
  /**
   * Current Page
   */
  current_page: number
  /**
   * Per Page
   */
  per_page: number
  /**
   * Has Next
   */
  has_next: boolean
  /**
   * Has Prev
   */
  has_prev: boolean
}

/**
 * WorkflowCreate
 */
export type WorkflowCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Definition Uri
   */
  definition_uri: string
  /**
   * Engine
   */
  engine: string
  /**
   * Attributes
   */
  attributes?: Array<Attribute> | null
}

/**
 * WorkflowPublic
 */
export type WorkflowPublic = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Engine
   */
  engine: string | null
  /**
   * Engine Id
   */
  engine_id: string | null
  /**
   * Attributes
   */
  attributes: Array<Attribute> | null
}

export type RootData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type HealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/health'
}

export type HealthCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type RegisterData = {
  body: UserRegister
  path?: never
  query?: never
  url: '/api/v1/auth/register'
}

export type RegisterErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RegisterError = RegisterErrors[keyof RegisterErrors]

export type RegisterResponses = {
  /**
   * Successful Response
   */
  201: UserPublic
}

export type RegisterResponse = RegisterResponses[keyof RegisterResponses]

export type LoginData = {
  body: BodyLogin
  path?: never
  query?: never
  url: '/api/v1/auth/login'
}

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LoginError = LoginErrors[keyof LoginErrors]

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse
}

export type LoginResponse = LoginResponses[keyof LoginResponses]

export type RefreshTokenData = {
  body: RefreshTokenRequest
  path?: never
  query?: never
  url: '/api/v1/auth/refresh'
}

export type RefreshTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors]

export type RefreshTokenResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse
}

export type RefreshTokenResponse =
  RefreshTokenResponses[keyof RefreshTokenResponses]

export type LogoutData = {
  body: RefreshTokenRequest
  path?: never
  query?: never
  url: '/api/v1/auth/logout'
}

export type LogoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LogoutError = LogoutErrors[keyof LogoutErrors]

export type LogoutResponses = {
  /**
   * Response Logout
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type LogoutResponse = LogoutResponses[keyof LogoutResponses]

export type GetCurrentUserInfoData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/me'
}

export type GetCurrentUserInfoResponses = {
  /**
   * Successful Response
   */
  200: UserPublic
}

export type GetCurrentUserInfoResponse =
  GetCurrentUserInfoResponses[keyof GetCurrentUserInfoResponses]

export type RequestPasswordResetData = {
  body: PasswordResetRequest
  path?: never
  query?: never
  url: '/api/v1/auth/password-reset/request'
}

export type RequestPasswordResetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RequestPasswordResetError =
  RequestPasswordResetErrors[keyof RequestPasswordResetErrors]

export type RequestPasswordResetResponses = {
  /**
   * Response Request Password Reset
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type RequestPasswordResetResponse =
  RequestPasswordResetResponses[keyof RequestPasswordResetResponses]

export type ConfirmPasswordResetData = {
  body: PasswordResetConfirm
  path?: never
  query?: never
  url: '/api/v1/auth/password-reset/confirm'
}

export type ConfirmPasswordResetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ConfirmPasswordResetError =
  ConfirmPasswordResetErrors[keyof ConfirmPasswordResetErrors]

export type ConfirmPasswordResetResponses = {
  /**
   * Response Confirm Password Reset
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type ConfirmPasswordResetResponse =
  ConfirmPasswordResetResponses[keyof ConfirmPasswordResetResponses]

export type ChangePasswordData = {
  body: PasswordChange
  path?: never
  query?: never
  url: '/api/v1/auth/password/change'
}

export type ChangePasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ChangePasswordError =
  ChangePasswordErrors[keyof ChangePasswordErrors]

export type ChangePasswordResponses = {
  /**
   * Response Change Password
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type ChangePasswordResponse =
  ChangePasswordResponses[keyof ChangePasswordResponses]

export type VerifyEmailData = {
  body: EmailVerificationRequest
  path?: never
  query?: never
  url: '/api/v1/auth/verify-email'
}

export type VerifyEmailErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors]

export type VerifyEmailResponses = {
  /**
   * Response Verify Email
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type VerifyEmailResponse =
  VerifyEmailResponses[keyof VerifyEmailResponses]

export type ResendVerificationData = {
  body: ResendVerificationRequest
  path?: never
  query?: never
  url: '/api/v1/auth/resend-verification'
}

export type ResendVerificationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ResendVerificationError =
  ResendVerificationErrors[keyof ResendVerificationErrors]

export type ResendVerificationResponses = {
  /**
   * Response Resend Verification
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type ResendVerificationResponse =
  ResendVerificationResponses[keyof ResendVerificationResponses]

export type GetAvailableOauthProvidersData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/oauth/providers'
}

export type GetAvailableOauthProvidersResponses = {
  /**
   * Successful Response
   */
  200: AvailableProvidersResponse
}

export type GetAvailableOauthProvidersResponse =
  GetAvailableOauthProvidersResponses[keyof GetAvailableOauthProvidersResponses]

export type OauthAuthorizeData = {
  body?: never
  path: {
    /**
     * Provider
     */
    provider: string
  }
  query?: {
    /**
     * Redirect Uri
     */
    redirect_uri?: string | null
  }
  url: '/api/v1/auth/oauth/{provider}/authorize'
}

export type OauthAuthorizeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type OauthAuthorizeError =
  OauthAuthorizeErrors[keyof OauthAuthorizeErrors]

export type OauthAuthorizeResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type OauthCallbackData = {
  body?: never
  path: {
    /**
     * Provider
     */
    provider: string
  }
  query: {
    /**
     * Code
     */
    code: string
    /**
     * State
     */
    state?: string | null
    /**
     * Redirect Uri
     */
    redirect_uri?: string | null
  }
  url: '/api/v1/auth/oauth/{provider}/callback'
}

export type OauthCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type OauthCallbackError = OauthCallbackErrors[keyof OauthCallbackErrors]

export type OauthCallbackResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse
}

export type OauthCallbackResponse =
  OauthCallbackResponses[keyof OauthCallbackResponses]

export type LinkOauthProviderData = {
  body: OAuthLinkRequest
  path: {
    /**
     * Provider
     */
    provider: string
  }
  query?: never
  url: '/api/v1/auth/oauth/{provider}/link'
}

export type LinkOauthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LinkOauthProviderError =
  LinkOauthProviderErrors[keyof LinkOauthProviderErrors]

export type LinkOauthProviderResponses = {
  /**
   * Response Link Oauth Provider
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type LinkOauthProviderResponse =
  LinkOauthProviderResponses[keyof LinkOauthProviderResponses]

export type UnlinkOauthProviderData = {
  body?: never
  path: {
    /**
     * Provider
     */
    provider: string
  }
  query?: never
  url: '/api/v1/auth/oauth/{provider}/unlink'
}

export type UnlinkOauthProviderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UnlinkOauthProviderError =
  UnlinkOauthProviderErrors[keyof UnlinkOauthProviderErrors]

export type UnlinkOauthProviderResponses = {
  /**
   * Response Unlink Oauth Provider
   * Successful Response
   */
  200: {
    [key: string]: unknown
  }
}

export type UnlinkOauthProviderResponse =
  UnlinkOauthProviderResponses[keyof UnlinkOauthProviderResponses]

export type CreateFileData = {
  body: BodyCreateFile
  path?: never
  query?: never
  url: '/api/v1/files'
}

export type CreateFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateFileError = CreateFileErrors[keyof CreateFileErrors]

export type CreateFileResponses = {
  /**
   * Successful Response
   */
  201: FilePublic
}

export type CreateFileResponse = CreateFileResponses[keyof CreateFileResponses]

export type ListFilesData = {
  body?: never
  path?: never
  query: {
    /**
     * Uri
     * URI to list (e.g., s3://bucket/folder/)
     */
    uri: string
  }
  url: '/api/v1/files/list'
}

export type ListFilesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors]

export type ListFilesResponses = {
  /**
   * Successful Response
   */
  200: FileBrowserData
}

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses]

export type DownloadFileData = {
  body?: never
  path?: never
  query: {
    /**
     * Path
     * S3 URI of the file to download (e.g., s3://bucket/path/file.txt)
     */
    path: string
  }
  url: '/api/v1/files/download'
}

export type DownloadFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DownloadFileError = DownloadFileErrors[keyof DownloadFileErrors]

export type DownloadFileResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetFileData = {
  body?: never
  path: {
    /**
     * File Id
     */
    file_id: string
  }
  query?: never
  url: '/api/v1/files/{file_id}'
}

export type GetFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetFileError = GetFileErrors[keyof GetFileErrors]

export type GetFileResponses = {
  /**
   * Successful Response
   */
  200: FilePublic
}

export type GetFileResponse = GetFileResponses[keyof GetFileResponses]

export type GetJobsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
    /**
     * User
     * Filter by user
     */
    user?: string | null
    /**
     * Status Filter
     * Filter by status
     */
    status_filter?: JobStatus | null
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/jobs'
}

export type GetJobsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetJobsError = GetJobsErrors[keyof GetJobsErrors]

export type GetJobsResponses = {
  /**
   * Successful Response
   */
  200: BatchJobsPublic
}

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses]

export type SubmitJobData = {
  body: BatchJobSubmit
  path?: never
  query?: never
  url: '/api/v1/jobs'
}

export type SubmitJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SubmitJobError = SubmitJobErrors[keyof SubmitJobErrors]

export type SubmitJobResponses = {
  /**
   * Successful Response
   */
  201: BatchJobPublic
}

export type SubmitJobResponse = SubmitJobResponses[keyof SubmitJobResponses]

export type GetJobData = {
  body?: never
  path: {
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: '/api/v1/jobs/{job_id}'
}

export type GetJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetJobError = GetJobErrors[keyof GetJobErrors]

export type GetJobResponses = {
  /**
   * Successful Response
   */
  200: BatchJobPublic
}

export type GetJobResponse = GetJobResponses[keyof GetJobResponses]

export type UpdateJobData = {
  body: BatchJobUpdate
  path: {
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: '/api/v1/jobs/{job_id}'
}

export type UpdateJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateJobError = UpdateJobErrors[keyof UpdateJobErrors]

export type UpdateJobResponses = {
  /**
   * Successful Response
   */
  200: BatchJobPublic
}

export type UpdateJobResponse = UpdateJobResponses[keyof UpdateJobResponses]

export type GetProjectsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/projects'
}

export type GetProjectsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetProjectsError = GetProjectsErrors[keyof GetProjectsErrors]

export type GetProjectsResponses = {
  /**
   * Successful Response
   */
  200: ProjectsPublic
}

export type GetProjectsResponse =
  GetProjectsResponses[keyof GetProjectsResponses]

export type CreateProjectData = {
  body: ProjectCreate
  path?: never
  query?: never
  url: '/api/v1/projects'
}

export type CreateProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors]

export type CreateProjectResponses = {
  /**
   * Successful Response
   */
  201: ProjectPublic
}

export type CreateProjectResponse =
  CreateProjectResponses[keyof CreateProjectResponses]

export type SearchProjectsData = {
  body?: never
  path?: never
  query: {
    /**
     * Query
     * Search query string
     */
    query: string
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: ('project_id' | 'name') | null
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: ('asc' | 'desc') | null
  }
  url: '/api/v1/projects/search'
}

export type SearchProjectsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SearchProjectsError =
  SearchProjectsErrors[keyof SearchProjectsErrors]

export type SearchProjectsResponses = {
  /**
   * Successful Response
   */
  200: ProjectsPublic
}

export type SearchProjectsResponse =
  SearchProjectsResponses[keyof SearchProjectsResponses]

export type ReindexProjectsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/projects/search'
}

export type ReindexProjectsResponses = {
  /**
   * Successful Response
   */
  201: unknown
}

export type GetProjectByProjectIdData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: '/api/v1/projects/{project_id}'
}

export type GetProjectByProjectIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetProjectByProjectIdError =
  GetProjectByProjectIdErrors[keyof GetProjectByProjectIdErrors]

export type GetProjectByProjectIdResponses = {
  /**
   * Successful Response
   */
  200: ProjectPublic
}

export type GetProjectByProjectIdResponse =
  GetProjectByProjectIdResponses[keyof GetProjectByProjectIdResponses]

export type GetSamplesData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: {
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/projects/{project_id}/samples'
}

export type GetSamplesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetSamplesError = GetSamplesErrors[keyof GetSamplesErrors]

export type GetSamplesResponses = {
  /**
   * Successful Response
   */
  200: SamplesPublic
}

export type GetSamplesResponse = GetSamplesResponses[keyof GetSamplesResponses]

export type AddSampleToProjectData = {
  body: SampleCreate
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: '/api/v1/projects/{project_id}/samples'
}

export type AddSampleToProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AddSampleToProjectError =
  AddSampleToProjectErrors[keyof AddSampleToProjectErrors]

export type AddSampleToProjectResponses = {
  /**
   * Successful Response
   */
  201: SamplePublic
}

export type AddSampleToProjectResponse =
  AddSampleToProjectResponses[keyof AddSampleToProjectResponses]

export type UpdateSampleInProjectData = {
  body: Attribute
  path: {
    /**
     * Project Id
     */
    project_id: string
    /**
     * Sample Id
     */
    sample_id: string
  }
  query?: never
  url: '/api/v1/projects/{project_id}/samples/{sample_id}'
}

export type UpdateSampleInProjectErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateSampleInProjectError =
  UpdateSampleInProjectErrors[keyof UpdateSampleInProjectErrors]

export type UpdateSampleInProjectResponses = {
  /**
   * Successful Response
   */
  200: SamplePublic
}

export type UpdateSampleInProjectResponse =
  UpdateSampleInProjectResponses[keyof UpdateSampleInProjectResponses]

export type GetRunsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/runs'
}

export type GetRunsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRunsError = GetRunsErrors[keyof GetRunsErrors]

export type GetRunsResponses = {
  /**
   * Successful Response
   */
  200: SequencingRunsPublic
}

export type GetRunsResponse = GetRunsResponses[keyof GetRunsResponses]

export type AddRunData = {
  body: SequencingRunCreate
  path?: never
  query?: never
  url: '/api/v1/runs'
}

export type AddRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AddRunError = AddRunErrors[keyof AddRunErrors]

export type AddRunResponses = {
  /**
   * Successful Response
   */
  201: SequencingRunPublic
}

export type AddRunResponse = AddRunResponses[keyof AddRunResponses]

export type SearchRunsData = {
  body?: never
  path?: never
  query: {
    /**
     * Query
     * Search query string
     */
    query: string
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: ('barcode' | 'experiment_name') | null
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: ('asc' | 'desc') | null
  }
  url: '/api/v1/runs/search'
}

export type SearchRunsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SearchRunsError = SearchRunsErrors[keyof SearchRunsErrors]

export type SearchRunsResponses = {
  /**
   * Successful Response
   */
  200: SequencingRunsPublic
}

export type SearchRunsResponse = SearchRunsResponses[keyof SearchRunsResponses]

export type ReindexRunsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/runs/search'
}

export type ReindexRunsResponses = {
  /**
   * Successful Response
   */
  201: unknown
}

export type ListDemultiplexWorkflowsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/runs/demultiplex'
}

export type ListDemultiplexWorkflowsResponses = {
  /**
   * Response List Demultiplex Workflows
   * Successful Response
   */
  200: Array<string>
}

export type ListDemultiplexWorkflowsResponse =
  ListDemultiplexWorkflowsResponses[keyof ListDemultiplexWorkflowsResponses]

export type SubmitDemultiplexWorkflowJobData = {
  body: DemuxWorkflowSubmitBody
  path?: never
  query?: never
  url: '/api/v1/runs/demultiplex'
}

export type SubmitDemultiplexWorkflowJobErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SubmitDemultiplexWorkflowJobError =
  SubmitDemultiplexWorkflowJobErrors[keyof SubmitDemultiplexWorkflowJobErrors]

export type SubmitDemultiplexWorkflowJobResponses = {
  /**
   * Successful Response
   */
  200: BatchJobPublic
}

export type SubmitDemultiplexWorkflowJobResponse =
  SubmitDemultiplexWorkflowJobResponses[keyof SubmitDemultiplexWorkflowJobResponses]

export type GetDemultiplexWorkflowConfigData = {
  body?: never
  path: {
    /**
     * Workflow Id
     */
    workflow_id: string
  }
  query?: {
    /**
     * Run Barcode
     * Run barcode to prepopulate s3_run_folder_path
     */
    run_barcode?: string
  }
  url: '/api/v1/runs/demultiplex/{workflow_id}'
}

export type GetDemultiplexWorkflowConfigErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetDemultiplexWorkflowConfigError =
  GetDemultiplexWorkflowConfigErrors[keyof GetDemultiplexWorkflowConfigErrors]

export type GetDemultiplexWorkflowConfigResponses = {
  /**
   * Successful Response
   */
  200: DemuxWorkflowConfig
}

export type GetDemultiplexWorkflowConfigResponse =
  GetDemultiplexWorkflowConfigResponses[keyof GetDemultiplexWorkflowConfigResponses]

export type GetRunData = {
  body?: never
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}'
}

export type GetRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRunError = GetRunErrors[keyof GetRunErrors]

export type GetRunResponses = {
  /**
   * Successful Response
   */
  200: SequencingRunPublic
}

export type GetRunResponse = GetRunResponses[keyof GetRunResponses]

export type UpdateRunData = {
  body: SequencingRunUpdateRequest
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}'
}

export type UpdateRunErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateRunError = UpdateRunErrors[keyof UpdateRunErrors]

export type UpdateRunResponses = {
  /**
   * Successful Response
   */
  200: SequencingRunPublic
}

export type UpdateRunResponse = UpdateRunResponses[keyof UpdateRunResponses]

export type GetRunSamplesheetData = {
  body?: never
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}/samplesheet'
}

export type GetRunSamplesheetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRunSamplesheetError =
  GetRunSamplesheetErrors[keyof GetRunSamplesheetErrors]

export type GetRunSamplesheetResponses = {
  /**
   * Successful Response
   */
  200: IlluminaSampleSheetResponseModel
}

export type GetRunSamplesheetResponse =
  GetRunSamplesheetResponses[keyof GetRunSamplesheetResponses]

export type PostRunSamplesheetData = {
  body: BodyPostRunSamplesheet
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}/samplesheet'
}

export type PostRunSamplesheetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PostRunSamplesheetError =
  PostRunSamplesheetErrors[keyof PostRunSamplesheetErrors]

export type PostRunSamplesheetResponses = {
  /**
   * Successful Response
   */
  201: IlluminaSampleSheetResponseModel
}

export type PostRunSamplesheetResponse =
  PostRunSamplesheetResponses[keyof PostRunSamplesheetResponses]

export type GetRunMetricsData = {
  body?: never
  path: {
    /**
     * Run Barcode
     */
    run_barcode: string
  }
  query?: never
  url: '/api/v1/runs/{run_barcode}/metrics'
}

export type GetRunMetricsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRunMetricsError = GetRunMetricsErrors[keyof GetRunMetricsErrors]

export type GetRunMetricsResponses = {
  /**
   * Successful Response
   */
  200: IlluminaMetricsResponseModel
}

export type GetRunMetricsResponse =
  GetRunMetricsResponses[keyof GetRunMetricsResponses]

export type ReindexSamplesData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/samples/search'
}

export type ReindexSamplesResponses = {
  /**
   * Successful Response
   */
  201: unknown
}

export type SearchData = {
  body?: never
  path?: never
  query: {
    /**
     * Query
     * Search query string
     */
    query: string
    /**
     * N Results
     * Number of results to return per index
     */
    n_results?: number
  }
  url: '/api/v1/search'
}

export type SearchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SearchError = SearchErrors[keyof SearchErrors]

export type SearchResponses = {
  /**
   * Successful Response
   */
  200: SearchResponse
}

export type SearchResponse2 = SearchResponses[keyof SearchResponses]

export type GetSettingsByTagData = {
  body?: never
  path?: never
  query: {
    /**
     * Tag Key
     * Tag key to filter by
     */
    tag_key: string
    /**
     * Tag Value
     * Tag value to filter by
     */
    tag_value: string
  }
  url: '/api/v1/settings'
}

export type GetSettingsByTagErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetSettingsByTagError =
  GetSettingsByTagErrors[keyof GetSettingsByTagErrors]

export type GetSettingsByTagResponses = {
  /**
   * Response Get Settings By Tag
   * Successful Response
   */
  200: Array<Setting>
}

export type GetSettingsByTagResponse =
  GetSettingsByTagResponses[keyof GetSettingsByTagResponses]

export type GetSettingData = {
  body?: never
  path: {
    /**
     * Key
     */
    key: string
  }
  query?: never
  url: '/api/v1/settings/{key}'
}

export type GetSettingErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetSettingError = GetSettingErrors[keyof GetSettingErrors]

export type GetSettingResponses = {
  /**
   * Successful Response
   */
  200: Setting
}

export type GetSettingResponse = GetSettingResponses[keyof GetSettingResponses]

export type UpdateSettingData = {
  body: SettingUpdate
  path: {
    /**
     * Key
     */
    key: string
  }
  query?: never
  url: '/api/v1/settings/{key}'
}

export type UpdateSettingErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateSettingError = UpdateSettingErrors[keyof UpdateSettingErrors]

export type UpdateSettingResponses = {
  /**
   * Successful Response
   */
  200: Setting
}

export type UpdateSettingResponse =
  UpdateSettingResponses[keyof UpdateSettingResponses]

export type GetVendorsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/vendors'
}

export type GetVendorsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetVendorsError = GetVendorsErrors[keyof GetVendorsErrors]

export type GetVendorsResponses = {
  /**
   * Successful Response
   */
  200: VendorsPublic
}

export type GetVendorsResponse = GetVendorsResponses[keyof GetVendorsResponses]

export type AddVendorData = {
  body: VendorCreate
  path?: never
  query?: never
  url: '/api/v1/vendors'
}

export type AddVendorErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AddVendorError = AddVendorErrors[keyof AddVendorErrors]

export type AddVendorResponses = {
  /**
   * Successful Response
   */
  201: VendorPublic
}

export type AddVendorResponse = AddVendorResponses[keyof AddVendorResponses]

export type DeleteVendorData = {
  body?: never
  path: {
    /**
     * Vendor Id
     */
    vendor_id: string
  }
  query?: never
  url: '/api/v1/vendors/{vendor_id}'
}

export type DeleteVendorErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteVendorError = DeleteVendorErrors[keyof DeleteVendorErrors]

export type DeleteVendorResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteVendorResponse =
  DeleteVendorResponses[keyof DeleteVendorResponses]

export type GetVendorData = {
  body?: never
  path: {
    /**
     * Vendor Id
     */
    vendor_id: string
  }
  query?: never
  url: '/api/v1/vendors/{vendor_id}'
}

export type GetVendorErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetVendorError = GetVendorErrors[keyof GetVendorErrors]

export type GetVendorResponses = {
  /**
   * Successful Response
   */
  200: VendorPublic
}

export type GetVendorResponse = GetVendorResponses[keyof GetVendorResponses]

export type UpdateVendorData = {
  body: VendorUpdate
  path: {
    /**
     * Vendor Id
     */
    vendor_id: string
  }
  query?: never
  url: '/api/v1/vendors/{vendor_id}'
}

export type UpdateVendorErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateVendorError = UpdateVendorErrors[keyof UpdateVendorErrors]

export type UpdateVendorResponses = {
  /**
   * Successful Response
   */
  200: VendorPublic
}

export type UpdateVendorResponse =
  UpdateVendorResponses[keyof UpdateVendorResponses]

export type GetLatestManifestData = {
  body?: never
  path?: never
  query: {
    /**
     * S3 Path
     * S3 bucket path to search for manifest files
     */
    s3_path: string
  }
  url: '/api/v1/manifest'
}

export type GetLatestManifestErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetLatestManifestError =
  GetLatestManifestErrors[keyof GetLatestManifestErrors]

export type GetLatestManifestResponses = {
  /**
   * Response Get Latest Manifest
   * Successful Response
   */
  200: string
}

export type GetLatestManifestResponse =
  GetLatestManifestResponses[keyof GetLatestManifestResponses]

export type UploadManifestData = {
  body: BodyUploadManifest
  path?: never
  query: {
    /**
     * S3 Path
     * S3 path where the manifest file should be uploaded
     */
    s3_path: string
  }
  url: '/api/v1/manifest'
}

export type UploadManifestErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UploadManifestError =
  UploadManifestErrors[keyof UploadManifestErrors]

export type UploadManifestResponses = {
  /**
   * Successful Response
   */
  201: ManifestUploadResponse
}

export type UploadManifestResponse =
  UploadManifestResponses[keyof UploadManifestResponses]

export type ValidateManifestData = {
  body?: never
  path?: never
  query: {
    /**
     * S3 Path
     * S3 path to the manifest CSV file to validate
     */
    s3_path: string
    /**
     * Manifest Version
     * Manifest version to validate against (e.g., 'DTS12.1')
     */
    manifest_version?: string | null
    /**
     * Files Bucket
     * S3 bucket where manifest files are located
     */
    files_bucket?: string | null
    /**
     * Files Prefix
     * S3 prefix/path where manifest files are located
     */
    files_prefix?: string | null
  }
  url: '/api/v1/manifest/validate'
}

export type ValidateManifestErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ValidateManifestError =
  ValidateManifestErrors[keyof ValidateManifestErrors]

export type ValidateManifestResponses = {
  /**
   * Successful Response
   */
  200: ManifestValidationResponse
}

export type ValidateManifestResponse =
  ValidateManifestResponses[keyof ValidateManifestResponses]

export type GetWorkflowsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     * Page number (1-indexed)
     */
    page?: number
    /**
     * Per Page
     * Number of items per page
     */
    per_page?: number
    /**
     * Sort By
     * Field to sort by
     */
    sort_by?: string
    /**
     * Sort Order
     * Sort order (asc or desc)
     */
    sort_order?: 'asc' | 'desc'
  }
  url: '/api/v1/workflows'
}

export type GetWorkflowsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetWorkflowsError = GetWorkflowsErrors[keyof GetWorkflowsErrors]

export type GetWorkflowsResponses = {
  /**
   * Response Get Workflows
   * Successful Response
   */
  200: Array<WorkflowPublic>
}

export type GetWorkflowsResponse =
  GetWorkflowsResponses[keyof GetWorkflowsResponses]

export type CreateWorkflowData = {
  body: WorkflowCreate
  path?: never
  query?: never
  url: '/api/v1/workflows'
}

export type CreateWorkflowErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateWorkflowError =
  CreateWorkflowErrors[keyof CreateWorkflowErrors]

export type CreateWorkflowResponses = {
  /**
   * Successful Response
   */
  201: WorkflowPublic
}

export type CreateWorkflowResponse =
  CreateWorkflowResponses[keyof CreateWorkflowResponses]

export type GetWorkflowByWorkflowIdData = {
  body?: never
  path: {
    /**
     * Workflow Id
     */
    workflow_id: string
  }
  query?: never
  url: '/api/v1/workflows/{workflow_id}'
}

export type GetWorkflowByWorkflowIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetWorkflowByWorkflowIdError =
  GetWorkflowByWorkflowIdErrors[keyof GetWorkflowByWorkflowIdErrors]

export type GetWorkflowByWorkflowIdResponses = {
  /**
   * Successful Response
   */
  200: WorkflowPublic
}

export type GetWorkflowByWorkflowIdResponse =
  GetWorkflowByWorkflowIdResponses[keyof GetWorkflowByWorkflowIdResponses]

export type ClientOptions = {
  baseURL: 'http://apiserver:3000' | (string & {})
}
